### ISSUE TITLE
Possible code-gen problem

### ISSUE THREAD

**Issue by halvko** [flix/flix#1116]
When trying to use a parser combinator, this small piece of seemingly correct code, compiles, but crashes on runtime:

```flix
type alias Parser[a] = List[Char] -> Option[(List[Char], a)]

def main(): Unit & Impure = match ('a' :: Nil) |> char() {
    case Some((Nil, 'a')) => Console.printLine("true")
    case _ => Console.printLine("false")
}

pub def char(): Parser[Char] = input -> match input {
    case Nil => None
    case x :: xs => Some((xs, x))
}
```

It crashes with the message:
```
Exception in thread "main" java.lang.ClassCastException: class Cons$Char cannot be cast to class IList$Obj (Cons$Char and IList$Obj are in unnamed module of loader ca.uwaterloo.flix.language.phase.jvm.FlixClassLoader @56f6d40b)
	at Clo$char$56432.invoke(Unknown Source)
	at Def$main.invoke(Unknown Source)
	at Ns.m_main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.$anonfun$link$1(JvmBackend.scala:261)
	at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.$anonfun$getCompiledDefs$2(JvmBackend.scala:234)
	at ca.uwaterloo.flix.runtime.CompilationResult.evalToString(CompilationResult.scala:90)
	at ca.uwaterloo.flix.Main$.$anonfun$main$6(Main.scala:187)
	at ca.uwaterloo.flix.util.Timer.<init>(Timer.scala:28)
	at ca.uwaterloo.flix.Main$.main(Main.scala:187)
	at ca.uwaterloo.flix.Main.main(Main.scala)
```

**Comment by halvko** [comment]
@magnus-madsen

**Comment by magnus-madsen** [comment]
If I inline the type alias I get:

```
-- Type Error -------------------------------------------------- foo.flix

>> The type scheme: '∀(44613). Unit -> List[a] -> Option[(List[a], a)]' cannot be generalized to '∀(a). Unit -> List[Char] -> Option[(List[Char], a)]'.

7 | pub def char(): List[Char] -> Option[(List[Char], a)] = input -> match input {
            ^^^^
            unable to generalize the type scheme.

Possible fixes:

  (1) The function is declared as too polymorphic. Remove some type variables.
  (2) The expression body of the function is incorrect.

```

**Comment by magnus-madsen** [comment]
This compiles:

```

def main(): Unit & Impure = match ('a' :: Nil) |> foo() {
    case Some((Nil, 'a')) => Console.printLine("true")
    case _ => Console.printLine("false")
}

pub def foo(): List[Char] -> Option[(List[Char], Char)] = input -> match input {
    case Nil => None
    case x :: xs => Some((xs, x: Char))
}
```

**Comment by magnus-madsen** [comment]
This part of `Typer`:

```
      case ResolvedAst.Pattern.Tag(sym, tag, pat, tvar, loc) =>
        // Lookup the enum declaration.
        val decl = root.enums(sym)

        // Generate a fresh type variable for each type parameters.
        val subst = Substitution(decl.tparams.map {
          case param => param.tpe -> Type.freshTypeVar()
        }.toMap)

        // Retrieve the enum type.
        val enumType = decl.tpe

        // Substitute the fresh type variables into the enum type.
        val freshEnumType = subst(enumType)

        // Retrieve the case type.
        val caseType = decl.cases(tag).tpe

        // Substitute the fresh type variables into the case type.
        val freshCaseType = subst(caseType)
        for (
          innerType <- visit(pat);
          _________ <- unifyTypM(innerType, freshCaseType, loc);
          resultType <- unifyTypM(tvar, freshEnumType, loc)
        ) yield resultType
```

is definitely wrong :)

An enum should have a scheme. I will need to look further into it. For now, I suggest you just work with the appropriate cast(s).

**Comment by magnus-madsen** [comment]
I think every `ResolvedAst.Case` should have a type scheme and then it should be instantiated in the above.

**Comment by magnus-madsen** [comment]
Fixed in master.
