### ISSUE TITLE
Think I found an infinite loop in type unification

### ISSUE THREAD

**Issue by racerand** [flix/flix#1142]
I got this error that just keeps on with the same 5 lines (the one repeated once here):

```
Exception in thread "Thread-1" java.lang.StackOverflowError
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.apply(Substitution.scala:82)
	at ca.uwaterloo.flix.language.phase.unification.Unification$.$anonfun$unifyTypes$3(Unification.scala:97)
	at ca.uwaterloo.flix.util.Result.flatMap(Result.scala:51)
	at ca.uwaterloo.flix.util.Result.flatMap$(Result.scala:50)
	at ca.uwaterloo.flix.util.Result$Ok.flatMap(Result.scala:70)
	at ca.uwaterloo.flix.language.phase.unification.Unification$.unifyTypes(Unification.scala:94)
	at ca.uwaterloo.flix.language.phase.unification.Unification$.$anonfun$unifyTypes$3(Unification.scala:97)
	at ca.uwaterloo.flix.util.Result.flatMap(Result.scala:51)
	at ca.uwaterloo.flix.util.Result.flatMap$(Result.scala:50)
	at ca.uwaterloo.flix.util.Result$Ok.flatMap(Result.scala:70)
	at ca.uwaterloo.flix.language.phase.unification.Unification$.unifyTypes(Unification.scala:94)
	at ca.uwaterloo.flix.language.phase.unification.Unification$.$anonfun$unifyTypes$3(Unification.scala:97)
```

After trying to run 

```
rel Train(src: City, dst: City)
rel Bus(src: City, dst: City)
rel Path(src: City, dst: City)

type alias City = Int

def travel(tg: #{Train| r}, bg: #{Bus| r}, src:City ,dst:City): Option[#{Path}] =
    let p = #{
        Path(x,y) :- Train(x,y).
        Path(x,z) :- Path(x,y), Train(y,z).
        Path(x,y) :- Bus(x,y),not Train(x,y).
        Path(x,z) :- Path(x,y), Bus(y,z),not Train(x,y).
    };
    let m = solve (tg <+> bg <+> p);
    if (m |= Path(src, dst).)
        Some(project Path m)
    else
        None
```
And I know that the type of travel does not make sense, but I don't like getting an error like this from the compiler.

**Comment by magnus-madsen** [comment]
Not sure what the problem is; but it looks like a bug.

If you change the signature of `tg` and `bg` to list all the predicates then the problem appears to go away.

**Comment by magnus-madsen** [comment]
I don't have time to look into this right away, but I suggest that you try to keep the signatures of `tg` and `bg` the same.

**Comment by racerand** [comment]
Exactly, it's not a big issue, as I can use more descriptive types, just felt like it would be a good thing to have it reported for later.

**Comment by magnus-madsen** [comment]
Yes, thanks.
