### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1352]
```
def foo(): String = "bar"
def main(): String = foo()
d
```

```
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: offset 55, count 2, length 56
	at java.base/java.lang.String.checkBoundsOffCount(String.java:3717)
	at java.base/java.lang.String.rangeCheck(String.java:298)
	at java.base/java.lang.String.<init>(String.java:294)
	at org.parboiled2.ParserInput$CharArrayBasedParserInput.sliceString(ParserInput.scala:118)
	at org.parboiled2.ErrorFormatter.formatProblem(ErrorFormatter.scala:80)
	at org.parboiled2.ErrorFormatter.format(ErrorFormatter.scala:58)
	at org.parboiled2.ErrorFormatter.format(ErrorFormatter.scala:51)
	at org.parboiled2.Parser.formatError(Parser.scala:106)
	at ca.uwaterloo.flix.language.phase.Parser$.parseRoot(Parser.scala:57)
	at ca.uwaterloo.flix.language.phase.Parser$.$anonfun$run$2(Parser.scala:39)
	at scala.collection.parallel.mutable.ParArray$Map.leaf(ParArray.scala:664)
	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:52)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:55)
	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:49)
	at scala.collection.parallel.mutable.ParArray$Map.tryLeaf(ParArray.scala:655)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:152)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:148)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:303)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by mlutze** [comment]
I think I hacked around this previously by creating a copy of `CharArrayBasedParserInput` (therein lies the bug) and changing some of the values.

**Comment by magnus-madsen** [comment]
Good to know.

Let us see what they say: https://github.com/sirthias/parboiled2/issues/213
