### ISSUE TITLE
`main` returning `Nil` causes runtime exception

### ISSUE THREAD

**Issue by racerand** [flix/flix#1396]
I just tried running the program
```
def main() : List[Int] =
    Nil
```
I get a runtime exception:
```
Exception in thread "main" java.lang.UnsupportedOperationException: toString method shouldn't be called
	at List$Nil$Obj.toString(List$Nil$Obj)
	at flix.runtime.ProxyObject.toString(ProxyObject.java:107)
	at ca.uwaterloo.flix.runtime.CompilationResult.evalToString(CompilationResult.scala:92)
	at ca.uwaterloo.flix.Main$.$anonfun$main$6(Main.scala:187)
	at ca.uwaterloo.flix.util.Timer.<init>(Timer.scala:28)
	at ca.uwaterloo.flix.Main$.main(Main.scala:187)
	at ca.uwaterloo.flix.Main.main(Main.scala)
```
Seems like the `Nil` can't be converted to a string by itselft, but works with a `cons`: 
```
def main() : List[Int] =
    1 :: Nil
```
Outputting `Cons((1, Nil(())))`

**Comment by magnus-madsen** [comment]
Main now has a fixed type signature.
