### ISSUE TITLE
LSP: Refusing to overwrite non-class file

### ISSUE THREAD

**Issue by plougsgaard** [flix/flix#1466]
I stumbled upon this error while playing around with the VSCode Plugin. Happened when running `main`. Resolved by removing the `target` directory.

```
ca.uwaterloo.flix.util.InternalCompilerException: Refusing to overwrite non-class file: 'c:\anonymized\.\target\flix\Tuple2$Obj$Obj.class'.
	at ca.uwaterloo.flix.language.phase.jvm.JvmOps$.writeClass(JvmOps.scala:1201)
	at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.$anonfun$run$6(JvmBackend.scala:184)
	at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.$anonfun$run$6$adapted(JvmBackend.scala:183)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:921)
	at scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:891)
	at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.$anonfun$run$4(JvmBackend.scala:183)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at ca.uwaterloo.flix.api.Flix.subphase(Flix.scala:357)
	at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.$anonfun$run$1(JvmBackend.scala:183)
	at ca.uwaterloo.flix.api.Flix.phase(Flix.scala:318)
	at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.run(JvmBackend.scala:43)
	at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.run(JvmBackend.scala:33)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.$anonfun$run$1(Phase.scala:42)
	at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
	at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
	at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:74)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
	at ca.uwaterloo.flix.api.Flix.codeGen(Flix.scala:292)
	at ca.uwaterloo.flix.api.Flix.$anonfun$compile$1(Flix.scala:306)
	at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
	at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
	at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:74)
	at ca.uwaterloo.flix.api.Flix.compile(Flix.scala:305)
	at ca.uwaterloo.flix.api.lsp.LanguageServer.runMain(LanguageServer.scala:346)
	at ca.uwaterloo.flix.api.lsp.LanguageServer.processRequest(LanguageServer.scala:212)
	at ca.uwaterloo.flix.api.lsp.LanguageServer.onMessage(LanguageServer.scala:128)
	at org.java_websocket.server.WebSocketServer.onWebsocketMessage(WebSocketServer.java:569)
	at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:709)
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:367)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:212)
	at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:925)
```

**Comment by magnus-madsen** [comment]
Weird. This means that the file existed, but did not contain the CAFE BABE bytes. Maybe the file was empty? 

I will add a check where the file is allowed to be overwritten if it is empty.
