### ISSUE TITLE
this program type checks  and then crashes

### ISSUE THREAD

**Issue by jacopol** [flix/flix#1756]
```
def allvals(vars:Int):List[List[Bool]] =
    if (vars < 0) Nil::Nil
    else (
        let short = allvals(vars-1);
        List.map(x->false::x,short) + List.map(x->true::x,short))

def main():List[List[Bool]] = allvals(3)
```

Error message:
`Unexpected type: 'Some(Enum(List,Type -> Type))' near ???:5:9.`

Stack trace:
```
ca.uwaterloo.flix.util.InternalCompilerException: Unexpected type: 'Some(Enum(List,Type -> Type))' near file:///c%3A/Users/au616260/Repositories/Formulas/form.flix:51:9.
	at ca.uwaterloo.flix.language.phase.Simplifier$.visitExp$1(Simplifier.scala:181)
	at ca.uwaterloo.flix.language.phase.Simplifier$.visitExp$1(Simplifier.scala:365)
	at ca.uwaterloo.flix.language.phase.Simplifier$.visitExp$1(Simplifier.scala:359)
	at ca.uwaterloo.flix.language.phase.Simplifier$.visitDef$1(Simplifier.scala:61)
	at ca.uwaterloo.flix.language.phase.Simplifier$.$anonfun$run$44(Simplifier.scala:1236)
	at scala.collection.StrictOptimizedMapOps.map(StrictOptimizedMapOps.scala:30)
	at scala.collection.StrictOptimizedMapOps.map$(StrictOptimizedMapOps.scala:29)
	at scala.collection.immutable.HashMap.map(HashMap.scala:38)
	at ca.uwaterloo.flix.language.phase.Simplifier$.$anonfun$run$1(Simplifier.scala:1236)
	at ca.uwaterloo.flix.api.Flix.phase(Flix.scala:318)
	at ca.uwaterloo.flix.language.phase.Simplifier$.run(Simplifier.scala:35)
	at ca.uwaterloo.flix.language.phase.Simplifier$.run(Simplifier.scala:31)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.$anonfun$run$1(Phase.scala:42)
	at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
	at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
	at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:74)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
	at ca.uwaterloo.flix.api.Flix.codeGen(Flix.scala:292)
	at ca.uwaterloo.flix.api.Flix.$anonfun$compile$1(Flix.scala:306)
	at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
	at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
	at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:74)
	at ca.uwaterloo.flix.api.Flix.compile(Flix.scala:305)
	at ca.uwaterloo.flix.api.lsp.LanguageServer.runMain(LanguageServer.scala:349)
	at ca.uwaterloo.flix.api.lsp.LanguageServer.processRequest(LanguageServer.scala:210)
	at ca.uwaterloo.flix.api.lsp.LanguageServer.onMessage(LanguageServer.scala:128)
	at org.java_websocket.server.WebSocketServer.onWebsocketMessage(WebSocketServer.java:569)
	at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:709)
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:367)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:212)
	at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:925)
```

**Comment by magnus-madsen** [comment]
You are adding two lists? What should that give? Did you mean append (List.append or :::)

In newest version of Flix you get this:

[cid:5c059318-abf5-47bb-adbc-11141a4d471c]

If this is a new/separate project I could easily setup you up with the newest nightly...



________________________________

**Comment by magnus-madsen** [comment]
Wow. I thought I was replying to a private email and then it ends up on GitHub. Hmmm.

**Comment by jacopol** [comment]
Yes, I meant :::
The type checker should have caught that?

**Comment by magnus-madsen** [comment]
> 
> 
> Yes, I meant :::
> The type checker should have caught that?

Yes, and it does in the newest version of Flix:


![image](https://user-images.githubusercontent.com/2287953/109953867-e9aed600-7ce0-11eb-882a-561ae071e929.png)

**Comment by magnus-madsen** [comment]
I am closing this because it is already fixed :) Just need to wait for the next stable release!
