### ISSUE TITLE
Compiler crash in PatternExhaustiveness

### ISSUE THREAD

**Issue by bdahse** [flix/flix#1836]
A match statement like the following crashes the compiler:
```
pub enum RelSym {
    case Full(String, Int32)
    case Delta(String, Int32)
    case New(String, Int32)
}

instance Order[RelSym] {
    pub def compare(a: RelSym, b: RelSym): Comparison = match (a, b) {
        case (Full(s1, _), Full(s2, _))   => s1 <=> s2
        case (Delta(s1, _), Delta(s2, _)) => s1 <=> s2
        case (New(s1, _), New(s2, _))     => s1 <=> s2
        case (Full(_), _) => GreaterThan
        case (_, Full(_)) => LessThan
        case (Delta(_), New(_)) => GreaterThan
        case (New(_), Delta(_)) => LessThan
    }
}
```
The stacktrace is:
```
java.util.NoSuchElementException: head of empty list
	at scala.collection.immutable.Nil$.head(List.scala:629)
	at scala.collection.immutable.Nil$.head(List.scala:628)
	at ca.uwaterloo.flix.language.phase.PatternExhaustiveness$Expressions$.rootCtor$1(PatternExhaustiveness.scala:593)
	at ca.uwaterloo.flix.language.phase.PatternExhaustiveness$Expressions$.$anonfun$rootCtors$1(PatternExhaustiveness.scala:600)
	at scala.collection.immutable.List.foldRight(List.scala:352)
	at ca.uwaterloo.flix.language.phase.PatternExhaustiveness$Expressions$.rootCtors(PatternExhaustiveness.scala:600)
	at ca.uwaterloo.flix.language.phase.PatternExhaustiveness$Expressions$.findNonMatchingPat(PatternExhaustiveness.scala:421)
	at ca.uwaterloo.flix.language.phase.PatternExhaustiveness$Expressions$.findNonMatchingPat(PatternExhaustiveness.scala:454)
	at ca.uwaterloo.flix.language.phase.PatternExhaustiveness$Expressions$.findNonMatchingPat(PatternExhaustiveness.scala:454)
	at ca.uwaterloo.flix.language.phase.PatternExhaustiveness$Expressions$.$anonfun$findNonMatchingPat$1(PatternExhaustiveness.scala:442)
	at scala.collection.immutable.List.map(List.scala:246)
	at ca.uwaterloo.flix.language.phase.PatternExhaustiveness$Expressions$.findNonMatchingPat(PatternExhaustiveness.scala:441)
	at ca.uwaterloo.flix.language.phase.PatternExhaustiveness$Expressions$.$anonfun$findNonMatchingPat$1(PatternExhaustiveness.scala:442)
	at scala.collection.immutable.List.map(List.scala:246)
	at ca.uwaterloo.flix.language.phase.PatternExhaustiveness$Expressions$.findNonMatchingPat(PatternExhaustiveness.scala:441)
	at ca.uwaterloo.flix.language.phase.PatternExhaustiveness$Expressions$.checkRules(PatternExhaustiveness.scala:398)
	at ca.uwaterloo.flix.language.phase.PatternExhaustiveness$Expressions$.$anonfun$checkPats$17(PatternExhaustiveness.scala:184)
	at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
	at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
	at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:74)
	at ca.uwaterloo.flix.language.phase.PatternExhaustiveness$Expressions$.checkPats(PatternExhaustiveness.scala:183)
	at ca.uwaterloo.flix.language.phase.PatternExhaustiveness$.checkPats(PatternExhaustiveness.scala:128)
	at ca.uwaterloo.flix.language.phase.PatternExhaustiveness$.$anonfun$run$3(PatternExhaustiveness.scala:112)
	at ca.uwaterloo.flix.util.Validation$.$anonfun$fastTraverse$1(Validation.scala:133)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at ca.uwaterloo.flix.util.Validation$.fastTraverse(Validation.scala:132)
	at ca.uwaterloo.flix.util.Validation$.traverse(Validation.scala:110)
	at ca.uwaterloo.flix.util.Validation$.traverseX(Validation.scala:116)
	at ca.uwaterloo.flix.language.phase.PatternExhaustiveness$.$anonfun$run$1(PatternExhaustiveness.scala:112)
	at ca.uwaterloo.flix.api.Flix.phase(Flix.scala:402)
	at ca.uwaterloo.flix.language.phase.PatternExhaustiveness$.run(PatternExhaustiveness.scala:110)
	at ca.uwaterloo.flix.language.phase.PatternExhaustiveness$.run(PatternExhaustiveness.scala:46)
	at ...
```
Note that it's not clear what code chokes it. This is just one example where I've managed to track it down to a small snippet, because it's so tedious when it happens. The match above can be rewritten as a workaround:
```
    pub def compare(a: RelSym, b: RelSym): Comparison = match a {
        case Full(s1, _) => match b {
            case Full(s2, _) => s1 <=> s2
            case _ => GreaterThan
        }
        case Delta(s1, _) => match b {
            case Delta(s2, _) => s1 <=> s2
            case New(_) => GreaterThan
            case Full(_) => LessThan
        }
        case New(s1, _) => match b {
            case New(s2, _) => s1 <=> s2
            case _ => LessThan
        }
    }
```
But it's not really practical since you first have to track down the offending code and then trial-and-error your way through rewrites while restarting the compiler each time.

**Comment by magnus-madsen** [comment]
We have hundreds of pattern matches that do not fail. What is special about this one? :/

**Comment by magnus-madsen** [comment]
Could it be because you sometimes match on Full as `Full(_)` and other times as `Full(_, _)`.

Its obviously a compiler bug. I am just trying to understand why it occurs.

**Comment by bdahse** [comment]
> Could it be because you sometimes match on Full as `Full(_)` and other times as `Full(_, _)`.
> 
> Its obviously a compiler bug. I am just trying to understand why it occurs.

I also do that in the workaround, although not in the same match.

I don't know if it's related, but when I'm missing a case, it sometimes nags me about bogus cases like `Denotation(Full(...), ...)` which makes no sense when you consider the structure of the types. I don't have a reproducible example of that unfortunately.

**Comment by bdahse** [comment]
I'll see if I can come up with a small example next time it happens. Until this is fixed I can always disable the PatternExhaustiveness phase if necessary, as a workaround.

**Comment by magnus-madsen** [comment]
> 
> 
> I'll see if I can come up with a small example next time it happens. Until this is fixed I can always disable the PatternExhaustiveness phase if necessary, as a workaround.

No, please don't do that. Try to see if it works when you pattern match on `Full` etc. "consistently".

**Comment by bdahse** [comment]
This is an example where it gets confused:
```
match (a, b) {
    case (Full(s1, _), Full(s2, _))   => s1 <=> s2
    case (Delta(s1, _), Delta(s2, _)) => s1 <=> s2
    case (New(s1, _), New(s2, _))     => s1 <=> s2
    case (Full(_, _), _) => GreaterThan
    case (_, Full(_, _)) => LessThan
    case (Delta(_), New(_)) => GreaterThan
    case (New(_), Delta(_)) => LessThan
}
```
This covers exactly the same set of cases as the original, but the compiler complains about a missing case:
`Non-Exhaustive Pattern. Missing case: (Delta(_, Full(New(_, _), _, _))) in match expression.`
Also note that the "missing" case makes absolutely no sense :)

**Comment by bdahse** [comment]
> > I'll see if I can come up with a small example next time it happens. Until this is fixed I can always disable the PatternExhaustiveness phase if necessary, as a workaround.
> 
> No, please don't do that. Try to see if it works when you pattern match on `Full` etc. "consistently".

If all constructors are matched with consistent arity in all rules, it also works.
```
pub def compare(a: RelSym, b: RelSym): Comparison = match (a, b) {
    case (Full(s1, _), Full(s2, _))   => s1 <=> s2
    case (Delta(s1, _), Delta(s2, _)) => s1 <=> s2
    case (New(s1, _), New(s2, _))     => s1 <=> s2
    case (Full(_, _), _) => GreaterThan
    case (_, Full(_, _)) => LessThan
    case (Delta(_, _), New(_, _)) => GreaterThan
    case (New(_, _), Delta(_, _)) => LessThan
}
```

**Comment by magnus-madsen** [comment]
> 
> 
> > > I'll see if I can come up with a small example next time it happens. Until this is fixed I can always disable the PatternExhaustiveness phase if necessary, as a workaround.
> > 
> > 
> > No, please don't do that. Try to see if it works when you pattern match on `Full` etc. "consistently".
> 
> If all constructors are matched with consistent arity in all rules, it also works.
> 
> ```
> pub def compare(a: RelSym, b: RelSym): Comparison = match (a, b) {
>     case (Full(s1, _), Full(s2, _))   => s1 <=> s2
>     case (Delta(s1, _), Delta(s2, _)) => s1 <=> s2
>     case (New(s1, _), New(s2, _))     => s1 <=> s2
>     case (Full(_, _), _) => GreaterThan
>     case (_, Full(_, _)) => LessThan
>     case (Delta(_, _), New(_, _)) => GreaterThan
>     case (New(_, _), Delta(_, _)) => LessThan
> }
> ```

OK, please do that and then we will get this bug fixed in the future. Thanks for reporting it!

**Comment by magnus-madsen** [comment]
Fixed in master.
