### ISSUE TITLE
Datalog: Introduce `project ... into ...` as a replacement/supplement for `<+>`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1876]
We need a quick way to inject facts into relation. Imagine you could write:

```ocaml
let xs = ... list of tuples ...
let ys = ... option of tuple ...
project xs, ys into A, B // return a constraint set #{A(...), B(...)}
```

Today the same can be done, but it requires a fold and `<+>`.

This could probably use the `Foldable` type class.

**Comment by magnus-madsen** [comment]
@bdahse 

Do you think this function can be implemented on your side in `Solver.flix`?:

```
    pub def project3[f: Type -> Type, t1: Type, t2: Type, t3: Type, v: Type](p: PredSym, ts: f[(t1, t2, t3)]): 
        Datalog[v] with Boxable[t1], Boxable[t2], Boxable[t3], Foldable[f] =
        ???
```

**Comment by magnus-madsen** [comment]
@bdahse

If you could paste a draft of that function here then I can use it in my PR #1882

**Comment by bdahse** [comment]
> @bdahse
> 
> If you could paste a draft of that function here then I can use it in my PR #1882

I have a draft. Unfortunately it crashes the compiler :)
The proposal:
```
///
/// Insert all facts in the given sequence `f` into the given relation `p`.
///
/// I.e. returns a Datalog program corresponding to `#{p(t1, t2, t3). p(t1', t2', t3').}`
/// given the sequence `(t1, t2, t3), (t1', t2', t3')`.
///
pub def projectInto3[f: Type -> Type, t1: Type, t2: Type, t3: Type, v: Type](p: PredSym, ts: f[(t1, t2, t3)]):
    Datalog[v] with Boxable[t1], Boxable[t2], Boxable[t3], Foldable[f] =
    use Boxable.box;
    let facts = Foldable.foldRight((v1, v2, v3) -> acc -> {
        Constraint(HeadAtom(p, Denotation.Relational,
                            [HeadTerm.Lit(box(v1), Unknown),
                             HeadTerm.Lit(box(v2), Unknown),
                             HeadTerm.Lit(box(v3), Unknown)],
                            Unknown),
                    [], Unknown) :: acc
    }, Nil, ts) as & Pure;
    Datalog(List.toArray(facts), []) as & Pure
```
The crash: 
```
ca.uwaterloo.flix.util.InternalCompilerException: Unexpected type: 'class ca.uwaterloo.flix.language.ast.Type$Apply'.
	at ca.uwaterloo.flix.language.debug.FormatType$.visit$1(FormatType.scala:101)
	at ca.uwaterloo.flix.language.debug.FormatType$.$anonfun$formatType$9(FormatType.scala:214)
	at scala.collection.immutable.List.map(List.scala:250)
	at ca.uwaterloo.flix.language.debug.FormatType$.visit$1(FormatType.scala:214)
	at ca.uwaterloo.flix.language.debug.FormatType$.formatType(FormatType.scala:249)
	at ca.uwaterloo.flix.language.ast.Type.toString(Type.scala:157)
	at ca.uwaterloo.flix.language.ast.Type.toString$(Type.scala:157)
	at ca.uwaterloo.flix.language.ast.Type$Apply.toString(Type.scala:369)
	at java.base/java.lang.String.valueOf(String.java:2951)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:168)
	at ca.uwaterloo.flix.language.errors.TypeError$MismatchedTypes.summary(TypeError.scala:68)
	at ca.uwaterloo.flix.api.lsp.Diagnostic$.from(Diagnostic.scala:30)
	at ca.uwaterloo.flix.api.lsp.PublishDiagnosticsParams$.$anonfun$from$3(PublishDiagnosticsParams.scala:37)
	at scala.collection.immutable.List.map(List.scala:246)
	at ca.uwaterloo.flix.api.lsp.PublishDiagnosticsParams$.$anonfun$from$2(PublishDiagnosticsParams.scala:37)
	at scala.collection.IterableOnceOps.foldLeft(IterableOnce.scala:646)
	at scala.collection.IterableOnceOps.foldLeft$(IterableOnce.scala:642)
	at scala.collection.AbstractIterable.foldLeft(Iterable.scala:919)
	at ca.uwaterloo.flix.api.lsp.PublishDiagnosticsParams$.from(PublishDiagnosticsParams.scala:35)
	at ca.uwaterloo.flix.api.lsp.LanguageServer.processCheck(LanguageServer.scala:271)
	at ca.uwaterloo.flix.api.lsp.LanguageServer.processRequest(LanguageServer.scala:214)
	at ca.uwaterloo.flix.api.lsp.LanguageServer.onMessage(LanguageServer.scala:128)
	at org.java_websocket.server.WebSocketServer.onWebsocketMessage(WebSocketServer.java:569)
	at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:709)
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:367)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:212)
	at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:925)
```

**Comment by magnus-madsen** [comment]
In the newest compiler your program has a type error

**Comment by magnus-madsen** [comment]
But indeed the compiler also seems pretty unhappy.

**Comment by magnus-madsen** [comment]
This is closer:

```
    // TODO: DOC
    pub def projectInto3[f: Type -> Type, t1: Type, t2: Type, t3: Type](p: PredSym, ts: f[(t1, t2, t3)]):
        Datalog[Boxed] with Boxable[t1], Boxable[t2], Boxable[t3], Foldable[f] =
        use Boxable.box;
        use Fixpoint/Ast.SourceLocation.{Unknown};
        let facts = Foldable.foldRight(vs -> acc -> {
            let (v1, v2, v3) = vs;
            Constraint(HeadAtom(p, Denotation.Relational,
                                [HeadTerm.Lit(box(v1), Unknown),
                                 HeadTerm.Lit(box(v2), Unknown),
                                 HeadTerm.Lit(box(v3), Unknown)],
                                Unknown),
                        [], Unknown) :: acc
        }, Nil, ts) as & Pure;
        Datalog(List.toArray(facts), []) as & Pure
```

but still does not work entirely.

**Comment by magnus-madsen** [comment]
OK, seems close to working. Thanks for the first draft. Ill keep you posted.

**Comment by bdahse** [comment]
> In the newest compiler your program has a type error

In a build from master I don't see a type error in vscode. But the crash is there. Does it crash before the typer?

**Comment by bdahse** [comment]
> This is closer:
> 
> ```
>     // TODO: DOC
>     pub def projectInto3[f: Type -> Type, t1: Type, t2: Type, t3: Type](p: PredSym, ts: f[(t1, t2, t3)]):
>         Datalog[Boxed] with Boxable[t1], Boxable[t2], Boxable[t3], Foldable[f] =
>         use Boxable.box;
>         use Fixpoint/Ast.SourceLocation.{Unknown};
>         let facts = Foldable.foldRight(vs -> acc -> {
>             let (v1, v2, v3) = vs;
>             Constraint(HeadAtom(p, Denotation.Relational,
>                                 [HeadTerm.Lit(box(v1), Unknown),
>                                  HeadTerm.Lit(box(v2), Unknown),
>                                  HeadTerm.Lit(box(v3), Unknown)],
>                                 Unknown),
>                         [], Unknown) :: acc
>         }, Nil, ts) as & Pure;
>         Datalog(List.toArray(facts), []) as & Pure
> ```
> 
> but still does not work entirely.

Ah okay I see, there was supposed to be a `match` i.e. `match (v1, v2, v3) -> acc -> ...` but I didn't see the type error because of the crash.

**Comment by magnus-madsen** [comment]
It works in the PR! :) (For n=3 exactly).

**Comment by magnus-madsen** [comment]
```
pub def main(_: Array[String]): Int32 & Impure =
    let x = (1, 2, 3) :: (4, 5, 6) :: Nil;
    let h = project x into A;
    (query h select (w, u, v) from A(w, u, v)) |> println;
    println("hello");
    2
```

**Comment by bdahse** [comment]
> ```
> pub def main(_: Array[String]): Int32 & Impure =
>     let x = (1, 2, 3) :: (4, 5, 6) :: Nil;
>     let h = project x into A;
>     (query h select (w, u, v) from A(w, u, v)) |> println;
>     println("hello");
>     2
> ```

What would happen if `A` was a lattice?

**Comment by magnus-madsen** [comment]
> 
> 
> > ```
> > pub def main(_: Array[String]): Int32 & Impure =
> >     let x = (1, 2, 3) :: (4, 5, 6) :: Nil;
> >     let h = project x into A;
> >     (query h select (w, u, v) from A(w, u, v)) |> println;
> >     println("hello");
> >     2
> > ```
> 
> What would happen if `A` was a lattice?

You cannot project into a lattice. 

If you try to mix a relation and a lattice you get a type error.

**Comment by magnus-madsen** [comment]
We can talk about how to better support lattices.

**Comment by bdahse** [comment]
I'm working on getting this working for n =/= 3 but I'm still running into the crash from before. For now I've been able to hack around it in the compiler, but I'm not sure if it's the correct fix.
