### ISSUE TITLE
static resource '/web/js/lib/react-dom.min.js'.

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#192]
```
Exception in thread "main" java.io.IOException: Unable to load static resource '/web/js/lib/react-dom.min.js'.
        at ca.uwaterloo.flix.runtime.debugger.RestServer$FileHandler$$anonfun$loadResources$1.apply(RestServer.scala:101)
        at ca.uwaterloo.flix.runtime.debugger.RestServer$FileHandler$$anonfun$loadResources$1.apply(RestServer.scala:88)
        at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:155)
        at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:155)
        at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:322)
        at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:978)
        at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:155)
        at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
        at ca.uwaterloo.flix.runtime.debugger.RestServer$FileHandler.loadResources(RestServer.scala:88)
        at ca.uwaterloo.flix.runtime.debugger.RestServer$FileHandler.<init>(RestServer.scala:118)
        at ca.uwaterloo.flix.runtime.debugger.RestServer.start(RestServer.scala:374)
        at ca.uwaterloo.flix.runtime.Solver.initSolver(Solver.scala:248)
        at ca.uwaterloo.flix.runtime.Solver.solve(Solver.scala:192)
        at ca.uwaterloo.flix.api.Flix$$anonfun$solve$1.apply(Flix.scala:238)
        at ca.uwaterloo.flix.api.Flix$$anonfun$solve$1.apply(Flix.scala:237)
        at ca.uwaterloo.flix.util.Validation$class.map(Validation.scala:36)
        at ca.uwaterloo.flix.util.Validation$Success.map(Validation.scala:276)
        at ca.uwaterloo.flix.api.Flix.solve(Flix.scala:237)
        at ca.uwaterloo.flix.Main$.main(Main.scala:94)
        at ca.uwaterloo.flix.Main.main(Main.scala)
```

Fix is to use `LocalResource` for the `RestServer`.

**Comment by magnus-madsen** [comment]
Fixed.
