### ISSUE TITLE
Compiler Crashes with too large file

### ISSUE THREAD

**Issue by jaschdoc** [flix/flix#2205]
The `TestLazyList.flix` file is 3937 lines in total and compiler crashes when trying to load in the file. The test suite is able to run all other tests, but `TestLazyList.flix` is skipped. [Here are the tests that caused the issue](https://gist.github.com/jaschdoc/e21c0316850732d0278a861791468352). They were generated and copied into `TestLazyList.flix` all at once. Running with `-Xmx8g` does not solve the issue. I get two stack traces.

From the compiler
```
Testing started at 19.30 ...
java.lang.RuntimeException: Method code too large!
	at org.objectweb.asm.MethodWriter.a(Unknown Source)
	at org.objectweb.asm.ClassWriter.toByteArray(Unknown Source)
	at ca.uwaterloo.flix.language.phase.jvm.GenNamespaces$.genBytecode(GenNamespaces.scala:79)
	at ca.uwaterloo.flix.language.phase.jvm.GenNamespaces$.$anonfun$gen$1(GenNamespaces.scala:41)
	at scala.collection.IterableOnceOps.foldLeft(IterableOnce.scala:646)
	at scala.collection.IterableOnceOps.foldLeft$(IterableOnce.scala:642)
	at scala.collection.AbstractIterable.foldLeft(Iterable.scala:919)
	at ca.uwaterloo.flix.language.phase.jvm.GenNamespaces$.gen(GenNamespaces.scala:37)
	at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.$anonfun$run$2(JvmBackend.scala:81)
	at ca.uwaterloo.flix.api.Flix.subphase(Flix.scala:436)
	at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.$anonfun$run$1(JvmBackend.scala:46)
	at ca.uwaterloo.flix.api.Flix.phase(Flix.scala:397)
	at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.run(JvmBackend.scala:38)
	at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.run(JvmBackend.scala:33)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.$anonfun$run$1(Phase.scala:42)
	at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
	at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
	at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:74)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
	at ca.uwaterloo.flix.api.Flix.codeGen(Flix.scala:371)
	at ca.uwaterloo.flix.api.Flix.$anonfun$compile$1(Flix.scala:385)
	at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
	at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
	at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:74)
	at ca.uwaterloo.flix.api.Flix.compile(Flix.scala:384)
	at ca.uwaterloo.flix.util.FlixTest.init(FlixTest.scala:47)
	at ca.uwaterloo.flix.util.FlixTest.<init>(FlixTest.scala:100)
	at ca.uwaterloo.flix.util.FlixTest.<init>(FlixTest.scala:28)
	at ca.uwaterloo.flix.library.LibrarySuite.<init>(LibrarySuite.scala:42)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:350)
	at java.base/java.lang.Class.newInstance(Class.java:645)
	at org.scalatest.tools.Runner$.genSuiteConfig(Runner.scala:1431)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$8(Runner.scala:1239)
	at scala.collection.immutable.List.map(List.scala:246)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1238)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:1033)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:1011)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1509)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1011)
	at org.scalatest.tools.Runner$.run(Runner.scala:850)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2or3(ScalaTestRunner.java:38)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:25)
```

From the test suite runner
```
Unable to load: 'TestLazyList'.
ScalaTestFailureLocation: ca.uwaterloo.flix.util.FlixTest at (FlixTest.scala:62)
org.scalatest.exceptions.TestFailedException: Unable to load: 'TestLazyList'.
	at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:530)
	at org.scalatest.Assertions.newAssertionFailedException$(Assertions.scala:529)
	at org.scalatest.FunSuite.newAssertionFailedException(FunSuite.scala:1560)
	at org.scalatest.Assertions.fail(Assertions.scala:1091)
	at org.scalatest.Assertions.fail$(Assertions.scala:1087)
	at org.scalatest.FunSuite.fail(FunSuite.scala:1560)
	at ca.uwaterloo.flix.util.FlixTest.$anonfun$init$4(FlixTest.scala:62)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at org.scalatest.FunSuite.withFixture(FunSuite.scala:1560)
	at org.scalatest.FunSuiteLike.invokeWithFixture$1(FunSuiteLike.scala:184)
	at org.scalatest.FunSuiteLike.$anonfun$runTest$1(FunSuiteLike.scala:196)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:286)
	at org.scalatest.FunSuiteLike.runTest(FunSuiteLike.scala:196)
	at org.scalatest.FunSuiteLike.runTest$(FunSuiteLike.scala:178)
	at org.scalatest.FunSuite.runTest(FunSuite.scala:1560)
	at org.scalatest.FunSuiteLike.$anonfun$runTests$1(FunSuiteLike.scala:229)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:393)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:381)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:376)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:458)
	at org.scalatest.FunSuiteLike.runTests(FunSuiteLike.scala:229)
	at org.scalatest.FunSuiteLike.runTests$(FunSuiteLike.scala:228)
	at org.scalatest.FunSuite.runTests(FunSuite.scala:1560)
	at org.scalatest.Suite.run(Suite.scala:1124)
	at org.scalatest.Suite.run$(Suite.scala:1106)
	at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1560)
	at org.scalatest.FunSuiteLike.$anonfun$run$1(FunSuiteLike.scala:233)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:518)
	at org.scalatest.FunSuiteLike.run(FunSuiteLike.scala:233)
	at org.scalatest.FunSuiteLike.run$(FunSuiteLike.scala:232)
	at org.scalatest.FunSuite.run(FunSuite.scala:1560)
	at org.scalatest.Suite.callExecuteOnSuite$1(Suite.scala:1187)
	at org.scalatest.Suite.$anonfun$runNestedSuites$1(Suite.scala:1234)
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
	at org.scalatest.Suite.runNestedSuites(Suite.scala:1232)
	at org.scalatest.Suite.runNestedSuites$(Suite.scala:1166)
	at org.scalatest.Suites.runNestedSuites(Suites.scala:56)
	at org.scalatest.Suite.run(Suite.scala:1121)
	at org.scalatest.Suite.run$(Suite.scala:1106)
	at org.scalatest.Suites.run(Suites.scala:56)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1349)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1343)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1343)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:1033)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:1011)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1509)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1011)
	at org.scalatest.tools.Runner$.run(Runner.scala:850)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2or3(ScalaTestRunner.java:38)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:25)
```

**Comment by JonathanStarup** [comment]
Each method in a namespace corresponds to a field and a method in the generated Ns class, this is bounded by the 65535 JVM limit, but the fields are initialized in the constructor which can only be 65535 bytes in size, which apparently reduces this limit to about 836 methods in a namespace since there is a couple instructions for each field.

This could be solved by creating a little list/tree of constructor functions of fixed size to allow the full 65535 methods.

It will not be a problem in the new backend since the fields are not needed.

@magnus-madsen do you want me to work on the fix?

**Comment by magnus-madsen** [comment]
I think we should just wait for the new backed.

**Comment by magnus-madsen** [comment]
@jaschdoc Meanwhile you could add some extra namespaces (that we can remove later).
