### ISSUE TITLE
Bug with predicates containing tuples

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#2353]
I didn't understand how predicates with tuple values worked so I experimented with the following:
```
def main(_args: Array[String]): Int32 & Impure =
    let l5 = #{
        B(1, 2). B(2, 3).
        A(x) :- B(x).

        // This line is allowed (which seems conflicting) but it doesn't influence the problem
        // A(x, y) :- C(x, y).
    };

    // This line works fine, result: [(1, 2), (2, 3)]
    // query l5 select x from B(x) |> println;

    // This line results in:
    //     java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
    query l5 select x from A(x) |> println;

    // this line works fine, result: [(1, 2), (2, 3)]
    // query l5 select (x, y) from A(x, y) |> println;
    0
```
Which results in this error:
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at Fixpoint.Clo$facts2$109960$130877.invoke(Unknown Source)
	at Fixpoint.Clo$factsOf$111108$130579.invoke(Unknown Source)
	at RedBlackTree.Def$foreach$111799.invoke(Unknown Source)
	at RedBlackTree.Def$queryWith$111795.invoke(Unknown Source)
	at Fixpoint.Def$factsOf$111108.invoke(Unknown Source)
	at Fixpoint.Def$facts2$109960.invoke(Unknown Source)
	at Def$main.invoke(Unknown Source)
	at Ns.m_main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.$anonfun$link$1(JvmBackend.scala:277)
	at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.$anonfun$getCompiledMain$2(JvmBackend.scala:238)
	at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.$anonfun$getCompiledMain$2$adapted(JvmBackend.scala:236)
	at ca.uwaterloo.flix.Main$.main(Main.scala:191)
	at ca.uwaterloo.flix.Main.main(Main.scala)

Process finished with exit code 1
```

**Comment by JonathanStarup** [comment]
from gitter:
```
def main(_args: Array[String]): Int32 & Impure = 

    let facts = #{
        MakesColor("yellow", "green"). MakesColor("blue", "green").
        MakesColor("red", "orange"). MakesColor("yellow", "orange").
        MakesColor("blue", "purple"). MakesColor("red", "purple").
    };

    let rules = #{
        MakesColor(x, y) :- MakesColor(y, x).
        MakesColor(x, y) :- MakesColor(x, z), MakesColor(z, y).
        };

    query facts, rules select (y) from MakesColor(y) |> println;
    0
```

**Comment by JonathanStarup** [comment]
This program works fine (even though it should be wrong
```flix
def main(_args: Array[String]): Int32 & Impure =
    let p = #{
        A(1, 2).
    };
    query p select x from A(x) |> Array.toList |> println;
    println("Hello World!");
    0
```
The type system is too fancy with tuple types. I sees a predicate with a single tuple term and a predicate with multiple terms as the same thing. The runtime doesn't agree

**Comment by JonathanStarup** [comment]
Here is a handful examples
```
/// OK: tuple pred can be quried as a unary pred
def main(): Unit \ IO = {
    let lp = #{
        Res(1, 2).
    };
    println(query lp select x from Res(x))
}

// CRASH: Unary pred (looks like multiarity on the type) queried as tuple
def main(): Unit \ IO = {
    let lp = #{
        Res((1, 2)).
    };
    println(query lp select (x, y) from Res(x, y))
}

// CRASH: tuple flow into unary
def main(): Unit \ IO = {
    let lp = #{
        Res(1, 2).
        Res((x, y)) :- Res(x, y).
    };
    println(query lp select (x, y) from Res(x, y))
}

// OK: inject (tuple) used as unary
def main(): Unit \ IO = {
    let lp = inject (1, 2) :: (2, 3) :: Nil into Res;
    println(query lp select x from Res(x))
}

// CRASH: inject (tuple) used as unary
def main(): Unit \ IO = {
    let data = inject (1, 2) :: (2, 3) :: Nil into Data;
    let lp = #{
        Res(x) :- Data(x).
    };
    println(query data, lp select x from Res(x))
}
```
I'm not sure how to fix this. We could disallow unary tuple predicates `Pred((1, 2))` which doesn't sound good, or we could stop using tuples for multiarity predicates. What do you think @magnus-madsen?

**Comment by magnus-madsen** [comment]
Not sure either.

**Comment by magnus-madsen** [comment]
Fixed in master.
