### ISSUE TITLE
Iterator `NoSuchElementException`

### ISSUE THREAD

**Issue by jaschdoc** [flix/flix#2484]
The code below throws a `NoSuchElementException`. The errors seems to be tied to the `k` function in the helper function, since using a normal accumulator and reversing the list afterwards works.

## Erroneous Code
```scala
    ///
    /// Returns the contents of `iter` as a list. Consumes the entire iterator.
    ///
    pub def toList(iter: Iterator[a]): List[a] & ef =
        let Iterator(done, next) = iter;
        toListAcc(done, next, ks -> ks) as & ef

    ///
    /// Helper function for `toList`.
    ///
    def toListAcc(done: Done, next: Next[a], k: List[a] -> List[a] & ef): List[a] & ef =
        if (done()) {
            k(Nil)
        }
        else {
            let x = next();
            toListAcc(done, next, ks -> k(x :: ks))
        }
```
## Stack trace
```
head of empty list
java.util.NoSuchElementException: head of empty list
	at scala.collection.immutable.Nil$.head(List.scala:629)
	at scala.collection.immutable.Nil$.head(List.scala:628)
	at ca.uwaterloo.flix.language.debug.FormatType$.visit$1(FormatType.scala:241)
	at ca.uwaterloo.flix.language.debug.FormatType$.$anonfun$formatType$7(FormatType.scala:243)
	at scala.collection.immutable.List.map(List.scala:246)
	at ca.uwaterloo.flix.language.debug.FormatType$.visit$1(FormatType.scala:243)
	at ca.uwaterloo.flix.language.debug.FormatType$.formatType(FormatType.scala:280)
	at ca.uwaterloo.flix.language.debug.FormatScheme$.formatSchemeWithoutConstraints(FormatScheme.scala:50)
	at ca.uwaterloo.flix.language.errors.TypeError$GeneralizationError.message(TypeError.scala:48)
	at ca.uwaterloo.flix.util.FlixTest.$anonfun$init$3(FlixTest.scala:52)
	at ca.uwaterloo.flix.util.FlixTest.$anonfun$init$3$adapted(FlixTest.scala:51)
	at scala.collection.immutable.LazyList.foreach(LazyList.scala:343)
	at ca.uwaterloo.flix.util.FlixTest.$anonfun$init$2(FlixTest.scala:51)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at org.scalatest.FunSuite.withFixture(FunSuite.scala:1560)
	at org.scalatest.FunSuiteLike.invokeWithFixture$1(FunSuiteLike.scala:184)
	at org.scalatest.FunSuiteLike.$anonfun$runTest$1(FunSuiteLike.scala:196)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:286)
	at org.scalatest.FunSuiteLike.runTest(FunSuiteLike.scala:196)
	at org.scalatest.FunSuiteLike.runTest$(FunSuiteLike.scala:178)
	at org.scalatest.FunSuite.runTest(FunSuite.scala:1560)
	at org.scalatest.FunSuiteLike.$anonfun$runTests$1(FunSuiteLike.scala:229)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:393)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:381)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:376)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:458)
	at org.scalatest.FunSuiteLike.runTests(FunSuiteLike.scala:229)
	at org.scalatest.FunSuiteLike.runTests$(FunSuiteLike.scala:228)
	at org.scalatest.FunSuite.runTests(FunSuite.scala:1560)
	at org.scalatest.Suite.run(Suite.scala:1124)
	at org.scalatest.Suite.run$(Suite.scala:1106)
	at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1560)
	at org.scalatest.FunSuiteLike.$anonfun$run$1(FunSuiteLike.scala:233)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:518)
	at org.scalatest.FunSuiteLike.run(FunSuiteLike.scala:233)
	at org.scalatest.FunSuiteLike.run$(FunSuiteLike.scala:232)
	at org.scalatest.FunSuite.run(FunSuite.scala:1560)
	at org.scalatest.Suite.callExecuteOnSuite$1(Suite.scala:1187)
	at org.scalatest.Suite.$anonfun$runNestedSuites$1(Suite.scala:1234)
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
	at org.scalatest.Suite.runNestedSuites(Suite.scala:1232)
	at org.scalatest.Suite.runNestedSuites$(Suite.scala:1166)
	at org.scalatest.Suites.runNestedSuites(Suites.scala:56)
	at org.scalatest.Suite.run(Suite.scala:1121)
	at org.scalatest.Suite.run$(Suite.scala:1106)
	at org.scalatest.Suites.run(Suites.scala:56)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1349)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1343)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1343)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:1033)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:1011)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1509)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1011)
	at org.scalatest.tools.Runner$.run(Runner.scala:850)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2or3(ScalaTestRunner.java:38)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:25)
```

## Working code
```scala
    ///
    /// Returns the contents of `iter` as a list. Consumes the entire iterator.
    ///
    pub def toList(iter: Iterator[a]): List[a] & ef =
        let Iterator(done, next) = iter;
        (toListAcc(done, next, Nil) |> List.reverse) as & ef

    ///
    /// Helper function for `toList`.
    ///
    def toListAcc(done: Done, next: Next[a], acc: List[a]): List[a] & Impure =
        if (done()) {
            acc
        }
        else {
            toListAcc(done, next, next() :: acc)
        }
```

**Comment by magnus-madsen** [comment]
Fixed? The merge is not in yet

**Comment by mlutze** [comment]
Not fixed yet :(

**Comment by jaschdoc** [comment]
Sorry! I saw the error in flix code in the above comment and thought we had this tracked somewhere else... I'm not quite sure what I was thinking :thinking:

**Comment by magnus-madsen** [comment]
Fixed in master.
