### ISSUE TITLE
Resolver error using type alias

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#2566]
This program `type alias PrecedenceEdge = Int` (Int is not important, it can even be a type variable) results in the error below. same both on latest release and master.
```
Exception in thread "main" ca.uwaterloo.flix.util.InternalCompilerException: Unexpected ambiguity: Duplicate types / classes should have been resolved.
        at ca.uwaterloo.flix.language.phase.Resolver$.semiResolveType(Resolver.scala:1496)
        at ca.uwaterloo.flix.language.phase.Resolver$.$anonfun$semiResolveType$29(Resolver.scala:1599)
        at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
        at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
        at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:74)
        at ca.uwaterloo.flix.language.phase.Resolver$.semiResolveType(Resolver.scala:1598)
        at ca.uwaterloo.flix.language.phase.Resolver$.resolveType(Resolver.scala:1681)
        at ca.uwaterloo.flix.language.phase.Resolver$.$anonfun$resolveEnum$1(Resolver.scala:354)
        at ca.uwaterloo.flix.util.Validation$.$anonfun$fastTraverse$1(Validation.scala:133)
        at scala.collection.immutable.Map$Map1.foreach(Map.scala:260)
        at ca.uwaterloo.flix.util.Validation$.fastTraverse(Validation.scala:132)
        at ca.uwaterloo.flix.util.Validation$.traverse(Validation.scala:110)
        at ca.uwaterloo.flix.language.phase.Resolver$.resolveEnum(Resolver.scala:351)
        at ca.uwaterloo.flix.language.phase.Resolver$.$anonfun$run$12(Resolver.scala:87)
        at scala.collection.StrictOptimizedIterableOps.map(StrictOptimizedIterableOps.scala:99)
        at scala.collection.StrictOptimizedIterableOps.map$(StrictOptimizedIterableOps.scala:86)
        at scala.collection.immutable.HashMap.map(HashMap.scala:39)
        at ca.uwaterloo.flix.language.phase.Resolver$.$anonfun$run$11(Resolver.scala:86)
        at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:117)
        at scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:104)
        at scala.collection.immutable.HashMap.flatMap(HashMap.scala:39)
        at ca.uwaterloo.flix.language.phase.Resolver$.$anonfun$run$2(Resolver.scala:85)
        at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
        at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
        at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:74)
        at ca.uwaterloo.flix.language.phase.Resolver$.$anonfun$run$1(Resolver.scala:57)
        at ca.uwaterloo.flix.api.Flix.phase(Flix.scala:419)
        at ca.uwaterloo.flix.language.phase.Resolver$.run(Resolver.scala:57)
        at ca.uwaterloo.flix.language.phase.Resolver$.run(Resolver.scala:33)
        at ca.uwaterloo.flix.language.phase.Phase$$anon$1.$anonfun$run$1(Phase.scala:42)
        at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
        at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
        at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:74)
        at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
        at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
        at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
        at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
        at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
        at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
        at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
        at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
        at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
        at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
        at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
        at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
        at ca.uwaterloo.flix.api.Flix.check(Flix.scala:349)
        at ca.uwaterloo.flix.api.Flix.compile(Flix.scala:402)
        at ca.uwaterloo.flix.Main$.$anonfun$main$5(Main.scala:186)
        at ca.uwaterloo.flix.util.Timer.<init>(Timer.scala:28)
        at ca.uwaterloo.flix.Main$.main(Main.scala:186)
        at ca.uwaterloo.flix.Main.main(Main.scala)
```

**Comment by JonathanStarup** [comment]
PredSym instead of PrecedenceGraph triggers the same behaviour
