### ISSUE TITLE
JVM interop - "creating interfaces"

### ISSUE THREAD

**Issue by stephentetley** [flix/flix#3328]
This is related to Non-Research Priorities #3314 (JVM Interop) - currently I have to write a Java stub rather than write `newPath` directly in Flix...

I can't _create_ a `java.nio.file.Path` in Flix. Although `java.nio.file.Path` is actually an interface, whichever class implements it is hidden in Java, however in Java I can still create a Path with `Path.of`:

~~~

  public static void testPath() throws Exception {    
      Path p1 = Path.of("///E/", new String[]{"coding", "flix"});
      System.out.println("p1: " + p1.normalize());
  }

~~~

The following Flix code tries to wrap `Path.of` into a reusable function, it type checks and compiles but fails with a runtime error:

~~~

def main(_args: Array[String]) : Int32 & Impure = 
    let p1 = newPath("///G/");
    toString(p1) |> println;
    0

pub def newPath(s: String): ##java.nio.file.Path & Impure =
    import static java.nio.file.Path.of(String, Array[String]): ##java.nio.file.Path & Impure as of1;
    try {
        of1(s, [])
    } catch {
        case _: ##java.lang.Exception => bug!("newPath")
    }

pub def toString(p1: ##java.nio.file.Path): String =
    import java.nio.file.Path.toString(): String & Pure;
    toString(p1)

~~~

The error is: 

~~~

> java -jar ..\..\bin\flix-working.jar .\test-marshal-arr.flix
Exception in thread "main" java.lang.IncompatibleClassChangeError: Method 'java.nio.file.Path java.nio.file.Path.of(java.lang.String, java.lang.String[])' must be InterfaceMethodref constant
        at Clo%newPath%820299.invoke(Unknown Source)
        at Cont%Obj.unwind(Cont%Obj)
        at Def%newPath.invoke(Unknown Source)
        at Cont%Obj.unwind(Cont%Obj)
        at Def%main.invoke(Unknown Source)
        at Cont%Int32.unwind(Cont%Int32)
        at Ns.m_main(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.$anonfun$link$1(JvmBackend.scala:285)
        at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.$anonfun$getCompiledMain$2(JvmBackend.scala:246)
        at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.$anonfun$getCompiledMain$2$adapted(JvmBackend.scala:244)
        at ca.uwaterloo.flix.Main$.main(Main.scala:217)
        at ca.uwaterloo.flix.Main.main(Main.scala)

~~~

**Comment by magnus-madsen** [comment]
@JonathanStarup Can you take a look? I suspect it is "just" a matter of emitting the right bytecode instruction.

**Comment by magnus-madsen** [comment]
See https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala#L898

**Comment by magnus-madsen** [comment]
@stephentetley Should be fixed now. Let us know how it works :)

**Comment by stephentetley** [comment]
Wow - thanks Magnus and Jonathan that was quick!

It also makes the other JVM array marshaling error easier to reproduce so I'll file a new report.
