### ISSUE TITLE
JVM interop - marshaling "constructed" arrays causes crash ("literal" arrays don't crash)

### ISSUE THREAD

**Issue by stephentetley** [flix/flix#3332]
Java interop has a problem where "constructed" arrays (e.g by `List.toArray`) cause a crash when they are passed to a native Java method. Literal arrays (i.e. statically specified with Flix's array syntax) can be passed successfully to the native Java method:

Toggling the version of `newPath` in the code below shows the problem:

~~~

def main(_args: Array[String]): Int32 & Impure = 
    println("Test1...");
    newPath("/home", Nil) |> pathToString |> println;
    println("Test2...");
    newPath("/home", "work" :: "flix" :: Nil) |> pathToString |> println;
    0

pub def newPath(s: String, rest: List[String]): ##java.nio.file.Path & Impure =
    import static java.nio.file.Path.of(String, Array[String]): ##java.nio.file.Path & Impure as of1;
    let arr1 = List.toArray(rest);    
    of1(s, arr1)


/// pub def newPath(s: String, _rest: List[String]): ##java.nio.file.Path & Impure =
///     import static java.nio.file.Path.of(String, Array[String]): ##java.nio.file.Path & Impure as of1;
///     let arr1 = ["work", "flix"];
///     of1(s, arr1)


pub def pathToString(p1: ##java.nio.file.Path): String =
    import java.nio.file.Path.toString(): String & Pure;
    toString(p1)

~~~

The error message from using the proper version of `newPath` - note that via the implementation of `List.toArray` Test1 actually uses an array created with the literal syntax: 

~~~

> java -jar ..\bin\flix-working.jar .\temp\test-marshal-arr2.flix
Test1...
\home
Test2...
Exception in thread "main" java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class [Ljava.lang.String; ([Ljava.lang.Object; and [Ljava.lang.String; are in module java.base of loader 'bootstrap')
        at Clo%newPath%819994.invoke(Unknown Source)
        at Cont%Obj.unwind(Cont%Obj)
        at Def%main.invoke(Unknown Source)
        at Cont%Int32.unwind(Cont%Int32)
        at Ns.m_main(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.$anonfun$link$1(JvmBackend.scala:285)
        at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.$anonfun$getCompiledMain$2(JvmBackend.scala:246)
        at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.$anonfun$getCompiledMain$2$adapted(JvmBackend.scala:244)
        at ca.uwaterloo.flix.Main$.main(Main.scala:217)
        at ca.uwaterloo.flix.Main.main(Main.scala)

~~~

**Comment by magnus-madsen** [comment]
@stephentetley This issue is more difficult, hence it will take more time before a solution is in place.

**Comment by stephentetley** [comment]
Thanks Magnus - I can manage with marshaling via Java's ArrayList so it's not a showstopper.

**Comment by magnus-madsen** [comment]
> Thanks Magnus - I can manage with marshaling via Java's ArrayList so it's not a showstopper.

Well, I would be pleased if we can get rid of all "trivial" Java wrappers.

**Comment by magnus-madsen** [comment]
I have a partial fix here: https://github.com/flix/flix/pull/5640

I tested it with the example from the ticket, but not generally. Let me know if it works.

(It does not work for multidim arrays).

Man, the JVM is a beast. I think with the new module system, the codegen phase is the last ugly part of the compiler that we need to eventually rewrite)

**Comment by stephentetley** [comment]
Thanks Magnus, I'll test it with my libs today.

**Comment by magnus-madsen** [comment]
I think this is fixed?
