### ISSUE TITLE
Kind Inference Issue?

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3345]
This program:

```scala
opaque type MutSet2[t: Type, r: Region] = ScopedRef[Set[t], r]

instance Newable[MutSet2[t]] {
    pub def new(r: Region[r]): MutSet2[t, r] & reg(r) = MutSet2.emptyWithRegion(r)
}

def main(_args: Array[String]): Int32 & Impure = 
    let len = region r {
        // let s = MutSet2.emptyWithRegion(r);  // works 
        let s = Newable.new(r);                 // crashes
        MutSet2.add!("abc", s);
        MutSet2.size(s)
    };
    println(len);
    0

namespace MutSet2 {

    pub def emptyWithRegion(r: Region[r]): MutSet2[a, r] & reg(r) =
        MutSet2(ref Set.empty() @ r)

    pub def add!(x: a, s: MutSet2[a, r]): Unit & reg(r) with Order[a] =
        let MutSet2(ms) = s;
        ms := Set.insert(x, deref ms)

    pub def size(s: MutSet2[a, r]): Int32 & reg(r) =
        let MutSet2(ms) = s;
        Set.size(deref ms)
}
```

gives:

```
Exception in thread "main" ca.uwaterloo.flix.util.InternalCompilerException: Illegal kind: '???' of type '_760812'.
        at ca.uwaterloo.flix.language.ast.Type$Apply.kind$lzycompute(Type.scala:473)
        at ca.uwaterloo.flix.language.ast.Type$Apply.kind(Type.scala:462)
```

where 

```
///
/// A type class for types that can be allocated in a region.
///
lawless class Newable[n: Region -> Type] {
    ///
    /// Returns a fresh `n` parameterized by `t` allocated in region `r`.
    ///
    pub def new[r: Region](r: Region[r]): n[r] & reg(r)
}
```

**Comment by magnus-madsen** [comment]
@mlutze Can you take a look? :)

**Comment by magnus-madsen** [comment]
Details: 
`Region` is sugar for just `Bool`. 
`reg(r)` is sugar for just `r`.

**Comment by magnus-madsen** [comment]
Works like a charm!
