### ISSUE TITLE
Compiler Bug

### ISSUE THREAD

**Issue by jaschdoc** [flix/flix#3634]
Got this when working on #3626 (merging master, 8d99585 into 066775f).

Note that this is probably not that critical as the program **should not compile** (`Array` is used in the tests but the function has been refactored to use `ScopedArray`):
```scala
namespace String {
    pub def toArray(s: String, r: Region[r]): ScopedArray[Char, r] \ Write(r) =
        Array.init(i -> charAt(i, s), length(s), r)
}

@test
def toArray01(): Bool & Impure = Array.sameElements(String.toArray(""), []: Array[Char])

@test
def toArray02(): Bool & Impure = Array.sameElements(String.toArray("ABC"), ['A', 'B', 'C'])

@test
def toArray03(): Bool & Impure = Array.sameElements(String.toArray("1 2 3"), ['1', ' ', '2', ' ', '3'])
```

```
#
# An unexpected error has been detected by the Flix compiler:
#
#   Unexpected non-Bool kind: 'Type -> Bool -> Type'.
#
# This is a bug in the Flix compiler. Please report it here:
#
# https://github.com/flix/flix/issues
#
# -- Flix Compiler --
#
# Flix Version : v0.27.0
#   incremental: All
#
# -- Java Virtual Machine --
#
# JVM Version  : 17.0.1 (2021-10-19)
# JVM Vendor   : Oracle Corporation
# JAVA_HOME    : /home/jaschn/.sdkman/candidates/java/17.0.1-open
# System       : Linux (5.17.4-200.fc35.x86_64)
#
# -- Stack Trace --
ca.uwaterloo.flix.util.InternalCompilerException: Unexpected non-Bool kind: 'Type -> Bool -> Type'.
	at ca.uwaterloo.flix.language.phase.unification.BoolTable$.minimizeType(BoolTable.scala:87)
	at ca.uwaterloo.flix.language.phase.unification.BoolUnification$.successiveVariableElimination(BoolUnification.scala:140)
	at ca.uwaterloo.flix.language.phase.unification.BoolUnification$.booleanUnification(BoolUnification.scala:86)
	at ca.uwaterloo.flix.language.phase.unification.BoolUnification$.unify(BoolUnification.scala:65)
	at ca.uwaterloo.flix.language.phase.unification.Unification$.unifyTypes(Unification.scala:76)
	at ca.uwaterloo.flix.language.phase.unification.Unification$.unifiesWith(Unification.scala:480)
	at ca.uwaterloo.flix.language.phase.unification.Unification$.getUnderOrOverAppliedError(Unification.scala:316)
	at ca.uwaterloo.flix.language.phase.unification.Unification$.$anonfun$unifyTypeM$1(Unification.scala:249)
	at ca.uwaterloo.flix.language.phase.unification.InferMonad.runNext$2(InferMonad.scala:70)
	at ca.uwaterloo.flix.language.phase.unification.InferMonad.$anonfun$flatMap$2(InferMonad.scala:78)
	at ca.uwaterloo.flix.language.phase.unification.InferMonad.$anonfun$flatMap$1(InferMonad.scala:73)
	at ca.uwaterloo.flix.util.Result.flatMap(Result.scala:51)
	at ca.uwaterloo.flix.util.Result.flatMap$(Result.scala:50)
	at ca.uwaterloo.flix.util.Result$Ok.flatMap(Result.scala:77)
	at ca.uwaterloo.flix.language.phase.unification.InferMonad.runNext$2(InferMonad.scala:70)
	at ca.uwaterloo.flix.language.phase.unification.InferMonad.$anonfun$flatMap$2(InferMonad.scala:78)
	at ca.uwaterloo.flix.language.phase.unification.InferMonad.$anonfun$flatMap$1(InferMonad.scala:73)
	at ca.uwaterloo.flix.util.Result.flatMap(Result.scala:51)
	at ca.uwaterloo.flix.util.Result.flatMap$(Result.scala:50)
	at ca.uwaterloo.flix.util.Result$Ok.flatMap(Result.scala:77)
	at ca.uwaterloo.flix.language.phase.unification.InferMonad.runNext$2(InferMonad.scala:70)
	at ca.uwaterloo.flix.language.phase.unification.InferMonad.$anonfun$flatMap$2(InferMonad.scala:78)
	at ca.uwaterloo.flix.language.phase.unification.InferMonad.$anonfun$withFilter$1(InferMonad.scala:97)
	at ca.uwaterloo.flix.language.phase.unification.InferMonad.runNext$1(InferMonad.scala:56)
	at ca.uwaterloo.flix.language.phase.unification.InferMonad.$anonfun$map$2(InferMonad.scala:61)
	at ca.uwaterloo.flix.language.phase.Typer$.typeCheckDecl(Typer.scala:229)
	at ca.uwaterloo.flix.language.phase.Typer$.visitDefn(Typer.scala:142)
	at ca.uwaterloo.flix.language.phase.Typer$.$anonfun$visitDefs$2(Typer.scala:188)
	at scala.collection.parallel.mutable.ParArray$Map.leaf(ParArray.scala:664)
	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:52)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:97)
	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:55)
	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:49)
	at scala.collection.parallel.mutable.ParArray$Map.tryLeaf(ParArray.scala:655)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:159)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:156)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:303)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:149)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:148)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:303)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
	Suppressed: ca.uwaterloo.flix.util.InternalCompilerException: Unexpected non-Bool kind: 'Type -> Bool -> Type'.
		at ca.uwaterloo.flix.language.phase.unification.BoolTable$.minimizeType(BoolTable.scala:87)
		at ca.uwaterloo.flix.language.phase.unification.BoolUnification$.successiveVariableElimination(BoolUnification.scala:140)
		at ca.uwaterloo.flix.language.phase.unification.BoolUnification$.booleanUnification(BoolUnification.scala:86)
		at ca.uwaterloo.flix.language.phase.unification.BoolUnification$.unify(BoolUnification.scala:65)
		at ca.uwaterloo.flix.language.phase.unification.Unification$.unifyTypes(Unification.scala:76)
		at ca.uwaterloo.flix.language.phase.unification.Unification$.unifiesWith(Unification.scala:480)
		at ca.uwaterloo.flix.language.phase.unification.Unification$.getUnderOrOverAppliedError(Unification.scala:316)
		at ca.uwaterloo.flix.language.phase.unification.Unification$.$anonfun$unifyTypeM$1(Unification.scala:249)
		at ca.uwaterloo.flix.language.phase.unification.InferMonad.runNext$2(InferMonad.scala:70)
		at ca.uwaterloo.flix.language.phase.unification.InferMonad.$anonfun$flatMap$2(InferMonad.scala:78)
		at ca.uwaterloo.flix.language.phase.unification.InferMonad.$anonfun$flatMap$1(InferMonad.scala:73)
		at ca.uwaterloo.flix.util.Result.flatMap(Result.scala:51)
		at ca.uwaterloo.flix.util.Result.flatMap$(Result.scala:50)
		at ca.uwaterloo.flix.util.Result$Ok.flatMap(Result.scala:77)
		at ca.uwaterloo.flix.language.phase.unification.InferMonad.runNext$2(InferMonad.scala:70)
		at ca.uwaterloo.flix.language.phase.unification.InferMonad.$anonfun$flatMap$2(InferMonad.scala:78)
		at ca.uwaterloo.flix.language.phase.unification.InferMonad.$anonfun$flatMap$1(InferMonad.scala:73)
		at ca.uwaterloo.flix.util.Result.flatMap(Result.scala:51)
		at ca.uwaterloo.flix.util.Result.flatMap$(Result.scala:50)
		at ca.uwaterloo.flix.util.Result$Ok.flatMap(Result.scala:77)
		at ca.uwaterloo.flix.language.phase.unification.InferMonad.runNext$2(InferMonad.scala:70)
		at ca.uwaterloo.flix.language.phase.unification.InferMonad.$anonfun$flatMap$2(InferMonad.scala:78)
		at ca.uwaterloo.flix.language.phase.unification.InferMonad.$anonfun$withFilter$1(InferMonad.scala:97)
		at ca.uwaterloo.flix.language.phase.unification.InferMonad.runNext$1(InferMonad.scala:56)
		at ca.uwaterloo.flix.language.phase.unification.InferMonad.$anonfun$map$2(InferMonad.scala:61)
		at ca.uwaterloo.flix.language.phase.Typer$.typeCheckDecl(Typer.scala:229)
		at ca.uwaterloo.flix.language.phase.Typer$.visitDefn(Typer.scala:142)
		at ca.uwaterloo.flix.language.phase.Typer$.$anonfun$visitDefs$2(Typer.scala:188)
		at scala.collection.parallel.mutable.ParArray$Map.leaf(ParArray.scala:664)
		at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:52)
		at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
		at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:97)
		at scala.collection.parallel.Task.tryLeaf(Tasks.scala:55)
		at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:49)
		at scala.collection.parallel.mutable.ParArray$Map.tryLeaf(ParArray.scala:655)
		at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:169)
		... 11 more
	Suppressed: ca.uwaterloo.flix.util.InternalCompilerException: Unexpected non-Bool kind: 'Type -> Bool -> Type'.
		at ca.uwaterloo.flix.language.phase.unification.BoolTable$.minimizeType(BoolTable.scala:87)
		at ca.uwaterloo.flix.language.phase.unification.BoolUnification$.successiveVariableElimination(BoolUnification.scala:140)
		at ca.uwaterloo.flix.language.phase.unification.BoolUnification$.booleanUnification(BoolUnification.scala:86)
		at ca.uwaterloo.flix.language.phase.unification.BoolUnification$.unify(BoolUnification.scala:65)
		at ca.uwaterloo.flix.language.phase.unification.Unification$.unifyTypes(Unification.scala:76)
		at ca.uwaterloo.flix.language.phase.unification.Unification$.unifiesWith(Unification.scala:480)
		at ca.uwaterloo.flix.language.phase.unification.Unification$.getUnderOrOverAppliedError(Unification.scala:316)
		at ca.uwaterloo.flix.language.phase.unification.Unification$.$anonfun$unifyTypeM$1(Unification.scala:249)
		at ca.uwaterloo.flix.language.phase.unification.InferMonad.runNext$2(InferMonad.scala:70)
		at ca.uwaterloo.flix.language.phase.unification.InferMonad.$anonfun$flatMap$2(InferMonad.scala:78)
		at ca.uwaterloo.flix.language.phase.unification.InferMonad.$anonfun$flatMap$1(InferMonad.scala:73)
		at ca.uwaterloo.flix.util.Result.flatMap(Result.scala:51)
		at ca.uwaterloo.flix.util.Result.flatMap$(Result.scala:50)
		at ca.uwaterloo.flix.util.Result$Ok.flatMap(Result.scala:77)
		at ca.uwaterloo.flix.language.phase.unification.InferMonad.runNext$2(InferMonad.scala:70)
		at ca.uwaterloo.flix.language.phase.unification.InferMonad.$anonfun$flatMap$2(InferMonad.scala:78)
		at ca.uwaterloo.flix.language.phase.unification.InferMonad.$anonfun$flatMap$1(InferMonad.scala:73)
		at ca.uwaterloo.flix.util.Result.flatMap(Result.scala:51)
		at ca.uwaterloo.flix.util.Result.flatMap$(Result.scala:50)
		at ca.uwaterloo.flix.util.Result$Ok.flatMap(Result.scala:77)
		at ca.uwaterloo.flix.language.phase.unification.InferMonad.runNext$2(InferMonad.scala:70)
		at ca.uwaterloo.flix.language.phase.unification.InferMonad.$anonfun$flatMap$2(InferMonad.scala:78)
		at ca.uwaterloo.flix.language.phase.unification.InferMonad.$anonfun$withFilter$1(InferMonad.scala:97)
		at ca.uwaterloo.flix.language.phase.unification.InferMonad.runNext$1(InferMonad.scala:56)
		at ca.uwaterloo.flix.language.phase.unification.InferMonad.$anonfun$map$2(InferMonad.scala:61)
		at ca.uwaterloo.flix.language.phase.Typer$.typeCheckDecl(Typer.scala:229)
		at ca.uwaterloo.flix.language.phase.Typer$.visitDefn(Typer.scala:142)
		at ca.uwaterloo.flix.language.phase.Typer$.$anonfun$visitDefs$2(Typer.scala:188)
		at scala.collection.parallel.mutable.ParArray$Map.leaf(ParArray.scala:664)
		at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:52)
		at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
		at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:97)
		at scala.collection.parallel.Task.tryLeaf(Tasks.scala:55)
		at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:49)
		at scala.collection.parallel.mutable.ParArray$Map.tryLeaf(ParArray.scala:655)
		at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:169)
		... 11 more
```
The error does state that it should be reported, so doing it s.t. the experts can decide what to do (if anything should be done) :)

Maybe this has something to do with the fact that tests are lazily compiled / evaluated so the type system would not have caught this until running the code?

**Comment by magnus-madsen** [comment]
@mlutze Looks like a kind error no? Maybe with the ascription?

**Comment by jaschdoc** [comment]
Btw I've been getting lots of these errors since I posted this. Instead of returning with a type error, telling me where I've made an error, it just crashes like this now.

**Comment by mlutze** [comment]
Looks like this is a result of some of the specific error message creation.

Type unification implicitly assumes that when we try to unify two types, they have the same kind. This is generally the case because the Kinder ensures it. But the manipulation we do to get specific type error messages (e.g., over- or underapplication) violates this assumption.

I _think_ we can fix this by changing a couple of lines in Unification, which would eliminate this assumption, but I'm not 100% sure.

**Comment by jaschdoc** [comment]
Feel free to give this issue a more descriptive title btw :)

**Comment by magnus-madsen** [comment]
> Looks like this is a result of some of the specific error message creation.
> 
> Type unification implicitly assumes that when we try to unify two types, they have the same kind. This is generally the case because the Kinder ensures it. But the manipulation we do to get specific type error messages (e.g., over- or underapplication) violates this assumption.
> 
> I _think_ we can fix this by changing a couple of lines in Unification, which would eliminate this assumption, but I'm not 100% sure.

Ah! Its an error during error construction!
