### ISSUE TITLE
Bug in Typer

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#364]
```
def differenceWith01: Bool =
    let m1 = Map.differenceWith((v1, v2) -> if (v1 > v2) Some(v1) else None, @{}, @{});
    let m2 = @{};
    Map.eq(m1, m2)
```

```
Exception in thread "main" ca.uwaterloo.flix.util.InternalCompilerException: Can't apply Greater to type Unit.
	at ca.uwaterloo.flix.language.phase.Codegen$.compileComparisonExpr(Codegen.scala:1075)
	at ca.uwaterloo.flix.language.phase.Codegen$.ca$uwaterloo$flix$language$phase$Codegen$$compileExpression(Codegen.scala:470)
	at ca.uwaterloo.flix.language.phase.Codegen$.ca$uwaterloo$flix$language$phase$Codegen$$compileExpression(Codegen.scala:478)
	at ca.uwaterloo.flix.language.phase.Codegen$.ca$uwaterloo$flix$language$phase$Codegen$$compileFunction(Codegen.scala:220)
	at ca.uwaterloo.flix.language.phase.Codegen$$anonfun$compile$2.apply(Codegen.scala:170)
	at ca.uwaterloo.flix.language.phase.Codegen$$anonfun$compile$2.apply(Codegen.scala:170)
	at scala.collection.immutable.List.foreach(List.scala:381)
```

Looks like a free variable getting monomorphed to Unit.

**Comment by magnus-madsen** [comment]
Adding a type annotation on e.g. `m2` fixes the issue.

**Comment by magnus-madsen** [comment]
This still crashes the compiler:

```
def differenceWith01(): Bool =
    let m1 = Map.differenceWith((v1, v2) -> if (v1 > v2) Some(v1) else None, Map#{}, Map#{});
    let m2 = Map#{};
    ???(m1, m2)
```

**Comment by magnus-madsen** [comment]
The problem is that the type of v1/v2 is under-specified.

**Comment by magnus-madsen** [comment]
Fixed in master.
