### ISSUE TITLE
Optimizer should not remove prints in `bug!`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#3719]
The optimizer is happy to rewrite this:

```
pub def bug!(m: String): a =
    let f = () -> {
        import static get java.lang.System.err: ##java.io.PrintStream & Pure as getErr;
        import java.io.PrintStream.println(String): Unit & Impure;
        import java.lang.String.repeat(Int32): ##java.lang.String & Pure;
        let prt = println(getErr());
        prt(repeat("*", 80));
        prt("**") ;
        prt("**  BUG: ${m}") ;
        prt("**") ;
        prt(repeat("*", 80));
        prt("")
    };
    let _ = f() as & Pure;
    ?panic
```

Do want a DontOptimize annotation or something like that temporarily?

**Comment by magnus-madsen** [comment]
I thought `addSourceLocation` in GenBytecode did this?

**Comment by JonathanStarup** [comment]
This program
```
def main(): Int32 = f(2)
def f(i: Int32): Int32 = g(i+2)
def g(_i: Int32): Int32 = bug!("error")
```
Causes error:
```
Exception in thread "main" dev.flix.runtime.HoleError: Hole '?panic' at Prelude.flix:158:5
	at Def%bug%exclamation%836744.invoke(Unknown Source)
	at Cont%Int32.unwind(Cont%Int32)
	at Def%main%.invoke(Unknown Source)
	at Cont%Obj.unwind(Cont%Obj)
	at Ns.m_main%(Unknown Source)
	at Main.main(Main)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at ca.uwaterloo.flix.language.phase.jvm.Bootstrap$.mainFunction$1(Bootstrap.scala:79)
	at ca.uwaterloo.flix.language.phase.jvm.Bootstrap$.$anonfun$bootstrap$9(Bootstrap.scala:88)
	at ca.uwaterloo.flix.language.phase.jvm.Bootstrap$.$anonfun$bootstrap$9$adapted(Bootstrap.scala:88)
	at ca.uwaterloo.flix.Main$.main(Main.scala:226)
	at ca.uwaterloo.flix.Main.main(Main.scala)
```
The location is the location of the ?hole which is in prelude. You can't really see here that the error was in `g`.
