### ISSUE TITLE
Regions: Monomorph crash

### ISSUE THREAD

**Issue by jaschdoc** [flix/flix#3734]
Commit 96e1802 on #3733 produces the following error. You can see in the diff from the previous commit that only `Array.toIterator` was changed to accomodate `ScopedArray`.

```
#
# An unexpected error has been detected by the Flix compiler:
#
#   Unable to unify: 'ScopedArray[t646931, b15899] -> DelayList[t646931] & b15899 and b647029 and b15904!' and 'ScopedArray[Int32, true] -> DelayList[Int32]'.
#
# This is a bug in the Flix compiler. Please report it here:
#
# https://github.com/flix/flix/issues
#
# -- Flix Compiler --
#
# Flix Version : v0.28.0
#   incremental: All
#
# -- Java Virtual Machine --
#
# JVM Version  : 17.0.1 (2021-10-19)
# JVM Vendor   : Oracle Corporation
# JAVA_HOME    : /home/jaschn/.sdkman/candidates/java/17.0.1-open
# System       : Linux (5.17.6-200.fc35.x86_64)
#
# -- Stack Trace --
ca.uwaterloo.flix.util.InternalCompilerException: Unable to unify: 'ScopedArray[t646931, b15899] -> DelayList[t646931] & b15899 and b647029 and b15904!' and 'ScopedArray[Int32, true] -> DelayList[Int32]'.
	at ca.uwaterloo.flix.language.phase.Monomorph$.infallibleUnify(Monomorph.scala:929)
	at ca.uwaterloo.flix.language.phase.Monomorph$.specializeDef(Monomorph.scala:748)
	at ca.uwaterloo.flix.language.phase.Monomorph$.specializeDefSym(Monomorph.scala:695)
	at ca.uwaterloo.flix.language.phase.Monomorph$.visitExp$1(Monomorph.scala:267)
	at ca.uwaterloo.flix.language.phase.Monomorph$.visitExp$1(Monomorph.scala:332)
	at ca.uwaterloo.flix.language.phase.Monomorph$.visitExp$1(Monomorph.scala:328)
	at ca.uwaterloo.flix.language.phase.Monomorph$.$anonfun$specialize$1(Monomorph.scala:333)
	at scala.collection.immutable.List.map(List.scala:250)
	at ca.uwaterloo.flix.language.phase.Monomorph$.visitExp$1(Monomorph.scala:333)
	at ca.uwaterloo.flix.language.phase.Monomorph$.$anonfun$specialize$1(Monomorph.scala:333)
	at scala.collection.immutable.List.map(List.scala:246)
	at ca.uwaterloo.flix.language.phase.Monomorph$.visitExp$1(Monomorph.scala:333)
	at ca.uwaterloo.flix.language.phase.Monomorph$.visitExp$1(Monomorph.scala:332)
	at ca.uwaterloo.flix.language.phase.Monomorph$.$anonfun$specialize$1(Monomorph.scala:333)
	at scala.collection.immutable.List.map(List.scala:246)
	at ca.uwaterloo.flix.language.phase.Monomorph$.visitExp$1(Monomorph.scala:333)
	at ca.uwaterloo.flix.language.phase.Monomorph$.visitExp$1(Monomorph.scala:352)
	at ca.uwaterloo.flix.language.phase.Monomorph$.specialize(Monomorph.scala:678)
	at ca.uwaterloo.flix.language.phase.Monomorph$.$anonfun$run$4(Monomorph.scala:200)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:926)
	at scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:896)
	at ca.uwaterloo.flix.language.phase.Monomorph$.$anonfun$run$1(Monomorph.scala:191)
	at ca.uwaterloo.flix.api.Flix.phase(Flix.scala:566)
	at ca.uwaterloo.flix.language.phase.Monomorph$.run(Monomorph.scala:167)
	at ca.uwaterloo.flix.api.Flix.$anonfun$codeGen$2(Flix.scala:519)
	at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
	at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
	at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:74)
	at ca.uwaterloo.flix.api.Flix.$anonfun$codeGen$1(Flix.scala:518)
	at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
	at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
	at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:74)
	at ca.uwaterloo.flix.api.Flix.codeGen(Flix.scala:517)
	at ca.uwaterloo.flix.api.Flix.$anonfun$compile$1(Flix.scala:551)
	at ca.uwaterloo.flix.util.Validation$.flatMapN(Validation.scala:252)
	at ca.uwaterloo.flix.api.Flix.compile(Flix.scala:551)
	at ca.uwaterloo.flix.util.FlixSuite.compileAndRun(FlixSuite.scala:65)
	at ca.uwaterloo.flix.util.FlixSuite.$anonfun$mkTest$1(FlixSuite.scala:48)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at org.scalatest.FunSuite.withFixture(FunSuite.scala:1560)
	at org.scalatest.FunSuiteLike.invokeWithFixture$1(FunSuiteLike.scala:184)
	at org.scalatest.FunSuiteLike.$anonfun$runTest$1(FunSuiteLike.scala:196)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:286)
	at org.scalatest.FunSuiteLike.runTest(FunSuiteLike.scala:196)
	at org.scalatest.FunSuiteLike.runTest$(FunSuiteLike.scala:178)
	at org.scalatest.FunSuite.runTest(FunSuite.scala:1560)
	at org.scalatest.FunSuiteLike.$anonfun$runTests$1(FunSuiteLike.scala:229)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:393)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:381)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:376)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:458)
	at org.scalatest.FunSuiteLike.runTests(FunSuiteLike.scala:229)
	at org.scalatest.FunSuiteLike.runTests$(FunSuiteLike.scala:228)
	at org.scalatest.FunSuite.runTests(FunSuite.scala:1560)
	at org.scalatest.Suite.run(Suite.scala:1124)
	at org.scalatest.Suite.run$(Suite.scala:1106)
	at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1560)
	at org.scalatest.FunSuiteLike.$anonfun$run$1(FunSuiteLike.scala:233)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:518)
	at org.scalatest.FunSuiteLike.run(FunSuiteLike.scala:233)
	at org.scalatest.FunSuiteLike.run$(FunSuiteLike.scala:232)
	at org.scalatest.FunSuite.run(FunSuite.scala:1560)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1349)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1343)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1343)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:1033)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:1011)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1509)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1011)
	at org.scalatest.tools.Runner$.run(Runner.scala:850)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2or3(ScalaTestRunner.java:38)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:25)




Unable to unify: 'ScopedArray[t646931, b15899] -> DelayList[t646931] & b15899 and b647029 and b15904!' and 'ScopedArray[Int32, true] -> DelayList[Int32]'.
ca.uwaterloo.flix.util.InternalCompilerException: Unable to unify: 'ScopedArray[t646931, b15899] -> DelayList[t646931] & b15899 and b647029 and b15904!' and 'ScopedArray[Int32, true] -> DelayList[Int32]'.
	at ca.uwaterloo.flix.language.phase.Monomorph$.infallibleUnify(Monomorph.scala:929)
	at ca.uwaterloo.flix.language.phase.Monomorph$.specializeDef(Monomorph.scala:748)
	at ca.uwaterloo.flix.language.phase.Monomorph$.specializeDefSym(Monomorph.scala:695)
	at ca.uwaterloo.flix.language.phase.Monomorph$.visitExp$1(Monomorph.scala:267)
	at ca.uwaterloo.flix.language.phase.Monomorph$.visitExp$1(Monomorph.scala:332)
	at ca.uwaterloo.flix.language.phase.Monomorph$.visitExp$1(Monomorph.scala:328)
	at ca.uwaterloo.flix.language.phase.Monomorph$.$anonfun$specialize$1(Monomorph.scala:333)
	at scala.collection.immutable.List.map(List.scala:250)
	at ca.uwaterloo.flix.language.phase.Monomorph$.visitExp$1(Monomorph.scala:333)
	at ca.uwaterloo.flix.language.phase.Monomorph$.$anonfun$specialize$1(Monomorph.scala:333)
	at scala.collection.immutable.List.map(List.scala:246)
	at ca.uwaterloo.flix.language.phase.Monomorph$.visitExp$1(Monomorph.scala:333)
	at ca.uwaterloo.flix.language.phase.Monomorph$.visitExp$1(Monomorph.scala:332)
	at ca.uwaterloo.flix.language.phase.Monomorph$.$anonfun$specialize$1(Monomorph.scala:333)
	at scala.collection.immutable.List.map(List.scala:246)
	at ca.uwaterloo.flix.language.phase.Monomorph$.visitExp$1(Monomorph.scala:333)
	at ca.uwaterloo.flix.language.phase.Monomorph$.visitExp$1(Monomorph.scala:352)
	at ca.uwaterloo.flix.language.phase.Monomorph$.specialize(Monomorph.scala:678)
	at ca.uwaterloo.flix.language.phase.Monomorph$.$anonfun$run$4(Monomorph.scala:200)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:926)
	at scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:896)
	at ca.uwaterloo.flix.language.phase.Monomorph$.$anonfun$run$1(Monomorph.scala:191)
	at ca.uwaterloo.flix.api.Flix.phase(Flix.scala:566)
	at ca.uwaterloo.flix.language.phase.Monomorph$.run(Monomorph.scala:167)
	at ca.uwaterloo.flix.api.Flix.$anonfun$codeGen$2(Flix.scala:519)
	at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
	at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
	at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:74)
	at ca.uwaterloo.flix.api.Flix.$anonfun$codeGen$1(Flix.scala:518)
	at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
	at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
	at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:74)
	at ca.uwaterloo.flix.api.Flix.codeGen(Flix.scala:517)
	at ca.uwaterloo.flix.api.Flix.$anonfun$compile$1(Flix.scala:551)
	at ca.uwaterloo.flix.util.Validation$.flatMapN(Validation.scala:252)
	at ca.uwaterloo.flix.api.Flix.compile(Flix.scala:551)
	at ca.uwaterloo.flix.util.FlixSuite.compileAndRun(FlixSuite.scala:65)
	at ca.uwaterloo.flix.util.FlixSuite.$anonfun$mkTest$1(FlixSuite.scala:48)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at org.scalatest.FunSuite.withFixture(FunSuite.scala:1560)
	at org.scalatest.FunSuiteLike.invokeWithFixture$1(FunSuiteLike.scala:184)
	at org.scalatest.FunSuiteLike.$anonfun$runTest$1(FunSuiteLike.scala:196)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:286)
	at org.scalatest.FunSuiteLike.runTest(FunSuiteLike.scala:196)
	at org.scalatest.FunSuiteLike.runTest$(FunSuiteLike.scala:178)
	at org.scalatest.FunSuite.runTest(FunSuite.scala:1560)
	at org.scalatest.FunSuiteLike.$anonfun$runTests$1(FunSuiteLike.scala:229)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:393)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:381)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:376)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:458)
	at org.scalatest.FunSuiteLike.runTests(FunSuiteLike.scala:229)
	at org.scalatest.FunSuiteLike.runTests$(FunSuiteLike.scala:228)
	at org.scalatest.FunSuite.runTests(FunSuite.scala:1560)
	at org.scalatest.Suite.run(Suite.scala:1124)
	at org.scalatest.Suite.run$(Suite.scala:1106)
	at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1560)
	at org.scalatest.FunSuiteLike.$anonfun$run$1(FunSuiteLike.scala:233)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:518)
	at org.scalatest.FunSuiteLike.run(FunSuiteLike.scala:233)
	at org.scalatest.FunSuiteLike.run$(FunSuiteLike.scala:232)
	at org.scalatest.FunSuite.run(FunSuite.scala:1560)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1349)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1343)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1343)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:1033)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:1011)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1509)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1011)
	at org.scalatest.tools.Runner$.run(Runner.scala:850)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2or3(ScalaTestRunner.java:38)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:25)
```

**Comment by magnus-madsen** [comment]
I need a minimal example, because the commit does not include all the changes.

**Comment by magnus-madsen** [comment]
This -- cobbled together -- seems to work:

```
namespace Array {

   ///
   /// Returns an iterator over `a`.
   ///
   pub def toIterator(a: ScopedArray[a, r]): Iterator[a] & Impure =
       let len = Array.length(a);
       let copy = copyOfRangeRegion(0, len, a, static);
       let i = ref 0;
       let done = () -> (deref i) >= len;
       let next = () -> {
           let j = deref i;
           let x = copy[j];
           i := j + 1;
           x
       };
       Iterator(done, next)


pub def copyOfRangeRegion(b: Int32, e: Int32, a: ScopedArray[a, r1], _: Region[r2]): ScopedArray[a, r2] \ { Read(r1), Write(r2) } =
        match (reifyType a) {
            case ErasedType =>
                let arr = a as Array[##java.lang.Object];
                import static java.util.Arrays.copyOfRange(Array[##java.lang.Object], Int32, Int32): ScopedArray[##java.lang.Object, r2] & r1 and r2 as copy;
                copy(arr, b, e) as ScopedArray[a, r2]
            case ReifiedUnit =>
                let arr = a as Array[Unit];
                import static java.util.Arrays.copyOfRange(Array[Unit], Int32, Int32): ScopedArray[Unit, r2] & r1 and r2 as copy;
                copy(arr, b, e) as ScopedArray[a, r2]
            case ReifiedBool =>
                let arr = a as Array[Bool];
                import static java.util.Arrays.copyOfRange(Array[Bool], Int32, Int32): ScopedArray[Bool, r2] & r1 and r2 as copy;
                copy(arr, b, e) as ScopedArray[a, r2]
            case ReifiedChar =>
                let arr = a as Array[Char];
                import static java.util.Arrays.copyOfRange(Array[Char], Int32, Int32): ScopedArray[Char, r2] & r1 and r2 as copy;
                copy(arr, b, e) as ScopedArray[a, r2]
            case ReifiedFloat32 =>
                let arr = a as Array[Float32];
                import static java.util.Arrays.copyOfRange(Array[Float32], Int32, Int32): ScopedArray[Float32, r2] & r1 and r2 as copy;
                copy(arr, b, e) as ScopedArray[a, r2]
            case ReifiedFloat64 =>
                let arr = a as Array[Float64];
                import static java.util.Arrays.copyOfRange(Array[Float64], Int32, Int32): ScopedArray[Float64, r2] & r1 and r2 as copy;
                copy(arr, b, e) as ScopedArray[a, r2]
            case ReifiedInt8 =>
                let arr = a as Array[Int8];
                import static java.util.Arrays.copyOfRange(Array[Int8], Int32, Int32): ScopedArray[Int8, r2] & r1 and r2 as copy;
                copy(arr, b, e) as ScopedArray[a, r2]
            case ReifiedInt16 =>
                let arr = a as Array[Int16];
                import static java.util.Arrays.copyOfRange(Array[Int16], Int32, Int32): ScopedArray[Int16, r2] & r1 and r2 as copy;
                copy(arr, b, e) as ScopedArray[a, r2]
            case ReifiedInt32 =>
                let arr = a as Array[Int32];
                import static java.util.Arrays.copyOfRange(Array[Int32], Int32, Int32): ScopedArray[Int32, r2] & r1 and r2 as copy;
                copy(arr, b, e) as ScopedArray[a, r2]
            case ReifiedInt64 =>
                let arr = a as Array[Int64];
                import static java.util.Arrays.copyOfRange(Array[Int64], Int32, Int32): ScopedArray[Int64, r2] & r1 and r2 as copy;
                copy(arr, b, e) as ScopedArray[a, r2]
            case ReifiedArray(_) =>
                let arr = a as Array[##java.lang.Object];
                import static java.util.Arrays.copyOfRange(Array[##java.lang.Object], Int32, Int32): ScopedArray[##java.lang.Object, r2] & r1 and r2 as copy;
                copy(arr, b, e) as ScopedArray[a, r2]
        }




}

namespace MutList {

    pub def toArrayRegion(v: MutList[a, r1], r2: Region[r2]): ScopedArray[a, r2] \ { Read(r1), Write(r2) } =
            let MutList(a, l) = v;
            Array.copyOfRangeRegion(0, deref l, deref a, r2)

}


    @test
    def toMutList05(): Bool = region r {
        let v = Array.toMutList([1, 2, 3] @ r);
        MutList.push!(4, v);
        Array.sameElements(MutList.toArrayRegion(v, r), [1, 2, 3, 4] @ r)
    }
```

so the bug is not exactly where you point to :)

**Comment by jaschdoc** [comment]
On I'll dig further into it tomorrow 😃

**Comment by jaschdoc** [comment]
I'm fairly certain it was caused by this:
```flix
    ///
    /// Returns the array `a` as a `DelayList`.
    ///
    pub def toDelayList(a: ScopedArray[a, r]): DelayList[a] \ Read(r) = region r1 {
        let cp = Array.copyOfRangeRegion(0, a.length, a, r1);
        def loop(i, k) = {
            if (i >= cp.length) {
                k(ENil)
            } else {
                let x = cp[i];
                loop(i + 1, ks -> ECons(x, ks))
            }
        };
        loop(0, identity)
    }
```

Changed it to something much simpler which solves the issue:
```flix

    ///
    /// Returns the array `a` as a `DelayList`.
    ///
    pub def toDelayList(a: ScopedArray[a, r]): DelayList[a] \ Read(r) =
        def loop(i, acc) = {
            if (i < 0)
                acc
            else
                loop(i - 1, ECons(a[i], acc))
        };
        loop(a.length - 1, ENil)
```

**Comment by magnus-madsen** [comment]
Think this is fixed too.
