### ISSUE TITLE
Regions: Finalizer crash

### ISSUE THREAD

**Issue by jaschdoc** [flix/flix#3741]
**Program**
(run tests)
```flix

///
/// Represents a StringBuilder1.
///
opaque type StringBuilder1[_: Region] = ##java.lang.StringBuilder

instance Newable[StringBuilder1] {
    pub def new(r: Region[r]): StringBuilder1[r] \ Write(r) = StringBuilder1.new(r)
}

namespace StringBuilder1 {

    ///
    /// Returns a new mutable StringBuilder1.
    ///
    pub def new(_: Region[r]): StringBuilder1[r] \ Write(r) =
        import new java.lang.StringBuilder(): ##java.lang.StringBuilder & r as newStringBuilder1;
        StringBuilder1(newStringBuilder1())
}


namespace TestStringBuilder1 {
/////////////////////////////////////////////////////////////////////////////
// new                                                                     //
/////////////////////////////////////////////////////////////////////////////
@test
def new01(): StringBuilder1[Impure] & Impure =
    new StringBuilder(static) // Must be Impure, otherwise the StringBuilder would escape its region

}
```

**Error**
```
#
# An unexpected error has been detected by the Flix compiler:
#
#   Unexpected type: '26410208[false]
#
# This is a bug in the Flix compiler. Please report it here:
#
# https://github.com/flix/flix/issues
#
# -- Flix Compiler --
#
# Flix Version : v0.28.0
#   incremental: All
#
# -- Java Virtual Machine --
#
# JVM Version  : 17.0.1 (2021-10-19)
# JVM Vendor   : Oracle Corporation
# JAVA_HOME    : /home/jaschn/.sdkman/candidates/java/17.0.1-open
# System       : Linux (5.17.6-200.fc35.x86_64)
#
# -- Stack Trace --
ca.uwaterloo.flix.util.InternalCompilerException: Unexpected type: '26410208[false]
	at ca.uwaterloo.flix.language.phase.Finalize$.visit$2(Finalize.scala:406)
	at ca.uwaterloo.flix.language.phase.Finalize$.$anonfun$visitType$1(Finalize.scala:401)
	at scala.collection.immutable.List.map(List.scala:250)
	at ca.uwaterloo.flix.language.phase.Finalize$.visit$2(Finalize.scala:401)
	at ca.uwaterloo.flix.language.phase.Finalize$.visitType(Finalize.scala:497)
	at ca.uwaterloo.flix.language.phase.Finalize$.visitDef(Finalize.scala:49)
	at ca.uwaterloo.flix.language.phase.Finalize$.$anonfun$run$2(Finalize.scala:36)
	at scala.collection.StrictOptimizedMapOps.map(StrictOptimizedMapOps.scala:28)
	at scala.collection.StrictOptimizedMapOps.map$(StrictOptimizedMapOps.scala:27)
	at scala.collection.immutable.HashMap.map(HashMap.scala:39)
	at ca.uwaterloo.flix.language.phase.Finalize$.$anonfun$run$1(Finalize.scala:35)
	at ca.uwaterloo.flix.api.Flix.phase(Flix.scala:566)
	at ca.uwaterloo.flix.language.phase.Finalize$.run(Finalize.scala:31)
	at ca.uwaterloo.flix.api.Flix.$anonfun$codeGen$10(Flix.scala:527)
	at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
	at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
	at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:74)
	at ca.uwaterloo.flix.api.Flix.$anonfun$codeGen$9(Flix.scala:526)
	at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
	at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
	at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:74)
	at ca.uwaterloo.flix.api.Flix.$anonfun$codeGen$8(Flix.scala:525)
	at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
	at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
	at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:74)
	at ca.uwaterloo.flix.api.Flix.$anonfun$codeGen$7(Flix.scala:524)
	at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
	at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
	at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:74)
	at ca.uwaterloo.flix.api.Flix.$anonfun$codeGen$6(Flix.scala:523)
	at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
	at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
	at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:74)
	at ca.uwaterloo.flix.api.Flix.$anonfun$codeGen$5(Flix.scala:522)
	at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
	at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
	at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:74)
	at ca.uwaterloo.flix.api.Flix.$anonfun$codeGen$4(Flix.scala:521)
	at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
	at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
	at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:74)
	at ca.uwaterloo.flix.api.Flix.$anonfun$codeGen$3(Flix.scala:520)
	at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
	at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
	at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:74)
	at ca.uwaterloo.flix.api.Flix.$anonfun$codeGen$2(Flix.scala:519)
	at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
	at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
	at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:74)
	at ca.uwaterloo.flix.api.Flix.$anonfun$codeGen$1(Flix.scala:518)
	at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
	at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
	at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:74)
	at ca.uwaterloo.flix.api.Flix.codeGen(Flix.scala:517)
	at ca.uwaterloo.flix.api.Flix.$anonfun$compile$1(Flix.scala:551)
	at ca.uwaterloo.flix.util.Validation$.flatMapN(Validation.scala:252)
	at ca.uwaterloo.flix.api.Flix.compile(Flix.scala:551)
	at ca.uwaterloo.flix.util.FlixSuite.compileAndRun(FlixSuite.scala:65)
	at ca.uwaterloo.flix.util.FlixSuite.$anonfun$mkTest$1(FlixSuite.scala:48)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at org.scalatest.FunSuite.withFixture(FunSuite.scala:1560)
	at org.scalatest.FunSuiteLike.invokeWithFixture$1(FunSuiteLike.scala:184)
	at org.scalatest.FunSuiteLike.$anonfun$runTest$1(FunSuiteLike.scala:196)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:286)
	at org.scalatest.FunSuiteLike.runTest(FunSuiteLike.scala:196)
	at org.scalatest.FunSuiteLike.runTest$(FunSuiteLike.scala:178)
	at org.scalatest.FunSuite.runTest(FunSuite.scala:1560)
	at org.scalatest.FunSuiteLike.$anonfun$runTests$1(FunSuiteLike.scala:229)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:393)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:381)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:376)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:458)
	at org.scalatest.FunSuiteLike.runTests(FunSuiteLike.scala:229)
	at org.scalatest.FunSuiteLike.runTests$(FunSuiteLike.scala:228)
	at org.scalatest.FunSuite.runTests(FunSuite.scala:1560)
	at org.scalatest.Suite.run(Suite.scala:1124)
	at org.scalatest.Suite.run$(Suite.scala:1106)
	at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1560)
	at org.scalatest.FunSuiteLike.$anonfun$run$1(FunSuiteLike.scala:233)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:518)
	at org.scalatest.FunSuiteLike.run(FunSuiteLike.scala:233)
	at org.scalatest.FunSuiteLike.run$(FunSuiteLike.scala:232)
	at org.scalatest.FunSuite.run(FunSuite.scala:1560)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1349)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1343)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1343)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:1033)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:1011)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1509)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1011)
	at org.scalatest.tools.Runner$.run(Runner.scala:850)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2or3(ScalaTestRunner.java:38)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:25)




Unexpected type: '26410208[false]
```

However, when wrapping the test in a main function like below, the error is that there is no instance of `Newable` for `StringBuilder1`:
```flix
def main(): Unit & Impure =
    let _ = new StringBuilder1(static);
    println("Hello World!")
```
**Error** (note that the number on the symbol may be different, the errors were made in separete VSCode windows / instances)
```
❌ -- Type Error --------------------------------------------------

>> No instance of the 'Newable' class for the type ''23774815'.

2 |     let _ = new StringBuilder1(static);
                    ^^^^^^^^^^^^^^
                    missing instance
```

Finally, note that not using the `Newable` instance is ok.
```flix
def main(): Unit & Impure =
    let _ = StringBuilder1.new(static); // ok
    println("Hello World!")
```

Compiler built from e15ee3c121f882ae79d48da15bc4b578136d9d67

**Comment by jaschdoc** [comment]
Confirmed!
