### ISSUE TITLE
Regions: Monomorph crash on `String.reverse`

### ISSUE THREAD

**Issue by jaschdoc** [flix/flix#3750]
**Program**
Note that the test does **not** call the `Str.reverse` but just the normal `String`. Either way, when it call `String.reverse` or `Str.reverse` it crashes.
```flix
namespace Str {
    pub def init(f: Int32 -> Char & ef, len: Int32): String & ef = region r {
        if (len <= 0)
            ""
        else {
            let sb = new StringBuilder1(r);
            def loop(i) = {
                if (i >= len)
                    ()
                else {
                    let c = f(i);
                    StringBuilder1.append!(c, sb);
                    loop(i+1)
                }
            };
            loop(0);
            StringBuilder1.toString(sb)
        }
    }

    pub def reverse(s: String) : String =
        let start = String.length(s) - 1;
        init(i -> String.charAt(start - i, s), start+1)

}

opaque type StringBuilder1[_: Region] = ##java.lang.StringBuilder

instance Newable[StringBuilder1] {
    pub def new(r: Region[r]): StringBuilder1[r] \ Write(r) = StringBuilder1.new(r)
}

namespace StringBuilder1 {
    ///
    /// Returns a new mutable StringBuilder.
    ///
    pub def new(_: Region[r]): StringBuilder1[r] \ Write(r) =
        import new java.lang.StringBuilder(): ##java.lang.StringBuilder & r as newStringBuilder;
        StringBuilder1(newStringBuilder())

    ///
    /// Append `x` to the StringBuilder `sb`.
    ///
    pub def append!(x: a, sb: StringBuilder1[r]): Unit \ Write(r) with ToString[a] =
        let s = ToString.toString(x);
        s `appendString!` sb;
        ()

    ///
    /// Append the String `s` to the StringBuilder `sb`.
    ///
    pub def appendString!(s: String, sb: StringBuilder1[r]): Unit \ Write(r) =
        import java.lang.StringBuilder.append(String): ##java.lang.StringBuilder & r;
        let StringBuilder1(msb) = sb;
        msb `append` s;
        ()

    ///
    /// Convert the StringBuilder `sb` to a string.
    ///
    pub def toString(sb: StringBuilder1[r]): String \ Read(r) =
        import java.lang.StringBuilder.toString(): String & r;
        let StringBuilder1(msb) = sb;
        toString(msb)
}

namespace TestStr {

@test
def reverse01(): Bool =
    String.reverse("") == ""

}
```

**Error**
```
#
# An unexpected error has been detected by the Flix compiler:
#
#   Unable to unify: '(Int32 -> Char & (b502741 and b8389!) or (b503022 and ((not (b503847 and b502741 and b8389!)) or (not b8389!)))) -> (Int32 -> String & b502741 and b8389!)' and '(Int32 -> Char) -> (Int32 -> String)'.
#
# This is a bug in the Flix compiler. Please report it here:
#
# https://github.com/flix/flix/issues
#
# -- Flix Compiler --
#
# Flix Version : v0.28.0
#   incremental: All
#
# -- Java Virtual Machine --
#
# JVM Version  : 17.0.1 (2021-10-19)
# JVM Vendor   : Oracle Corporation
# JAVA_HOME    : /home/jaschn/.sdkman/candidates/java/17.0.1-open
# System       : Linux (5.17.6-200.fc35.x86_64)
#
# -- Stack Trace --
ca.uwaterloo.flix.util.InternalCompilerException: Unable to unify: '(Int32 -> Char & (b502741 and b8389!) or (b503022 and ((not (b503847 and b502741 and b8389!)) or (not b8389!)))) -> (Int32 -> String & b502741 and b8389!)' and '(Int32 -> Char) -> (Int32 -> String)'.
	at ca.uwaterloo.flix.language.phase.Monomorph$.infallibleUnify(Monomorph.scala:929)
	at ca.uwaterloo.flix.language.phase.Monomorph$.specializeDef(Monomorph.scala:748)
	at ca.uwaterloo.flix.language.phase.Monomorph$.specializeDefSym(Monomorph.scala:695)
	at ca.uwaterloo.flix.language.phase.Monomorph$.visitExp$1(Monomorph.scala:267)
	at ca.uwaterloo.flix.language.phase.Monomorph$.visitExp$1(Monomorph.scala:332)
	at ca.uwaterloo.flix.language.phase.Monomorph$.visitExp$1(Monomorph.scala:352)
	at ca.uwaterloo.flix.language.phase.Monomorph$.specialize(Monomorph.scala:678)
	at ca.uwaterloo.flix.language.phase.Monomorph$.$anonfun$run$4(Monomorph.scala:200)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
	at scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:889)
	at ca.uwaterloo.flix.language.phase.Monomorph$.$anonfun$run$1(Monomorph.scala:191)
	at ca.uwaterloo.flix.api.Flix.phase(Flix.scala:566)
	at ca.uwaterloo.flix.language.phase.Monomorph$.run(Monomorph.scala:167)
	at ca.uwaterloo.flix.api.Flix.$anonfun$codeGen$2(Flix.scala:519)
	at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
	at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
	at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:74)
	at ca.uwaterloo.flix.api.Flix.$anonfun$codeGen$1(Flix.scala:518)
	at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
	at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
	at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:74)
	at ca.uwaterloo.flix.api.Flix.codeGen(Flix.scala:517)
	at ca.uwaterloo.flix.api.Flix.$anonfun$compile$1(Flix.scala:551)
	at ca.uwaterloo.flix.util.Validation$.flatMapN(Validation.scala:252)
	at ca.uwaterloo.flix.api.Flix.compile(Flix.scala:551)
	at ca.uwaterloo.flix.tools.Packager$.build(Packager.scala:199)
	at ca.uwaterloo.flix.tools.Packager$.test(Packager.scala:360)
	at ca.uwaterloo.flix.Main$.main(Main.scala:149)
	at ca.uwaterloo.flix.Main.main(Main.scala)
```

**Comment by magnus-madsen** [comment]
@jaschdoc Can you confirm that #3755 helps?

**Comment by jaschdoc** [comment]
Affirmative. It does **not** crash anymore
