### ISSUE TITLE
Compiler crashes on `Array.flatten` refactor

### ISSUE THREAD

**Issue by jaschdoc** [flix/flix#3811]
The following program crashes the compiler during unification.

```flix
def main(): Unit & Impure =
    println("Hello World!")

namespace Array1 {
    pub def length(a: ScopedArray[a, r]): Int32 = a.length

    pub def foldLeft(f: (b, a) -> b & ef, s: b, arr: ScopedArray[a, r]): b \ { ef, Read(r) } =
        let len = length(arr);
        def loop(i, acc) = {
            if (i >= len)
                acc
            else
                loop(i + 1, f(acc, arr[i]))
        };
        loop(0, s)


    def sumLengths(arrs: ScopedArray[ScopedArray[a, r1], r2]): Int32 \ Read(r2) =
        foldLeft((acc, a) -> acc + length(a), 0, arrs)

    def arrayWrites(pos: Int32, sub: ScopedArray[a, r1], out: ScopedArray[a, r2]): Int32 \ { Read(r1), Write(r2) } =
        updateSequence!(pos, sub, out);
        pos + length(sub)

    pub def updateSequence!(i: Int32, sub: ScopedArray[a, r1], a: ScopedArray[a, r2]): Unit \ { Read(r1), Write(r2) } =
        let end = i + length(sub);
        let f = { (_,ix) ->
            if (ix >= i and ix < end)
                a[ix] = sub[ix-i]
            else
                ()
        };
        foreachWithIndex(f, a)

    pub def foreachWithIndex(f: (a, Int32) -> Unit & ef, a: ScopedArray[a, r]): Unit \ { ef, Read(r) } =
        let len = length(a);
        def loop(i) = {
            if (i >= len)
                ()
            else {
                f(a[i], i);
                loop(i + 1)
            }
        };
        if (len < 1)
            ()
        else
            loop(0)

    pub def new(x: a, l: Int32, r: Region[r]): ScopedArray[a, r] \ Write(r) =
        [x; l] @ r

    def headArrays(arrs: ScopedArray[ScopedArray[a, r1], r2]): Option[a] \ Read(r1, r2) =
        let len = length(arrs);
        def loop(i) = {
            if (i >= len)
                None
            else
                match head(arrs[i]) {
                    case Some(x) => Some(x)
                    case None    => loop(i + 1)
                }
        };
        loop(0)

    pub def head(a: ScopedArray[a, r]): Option[a] \ Read(r) =
        if (length(a) > 0) Some(a[0]) else None

        pub def flatten(arrs: ScopedArray[ScopedArray[a, r1], r2]): ScopedArray[a, r2] \ { Read(r1, r2), Write(r2) } =
        let len = sumLengths(arrs);
        match headArrays(arrs) {
            case None    => [] @ Scoped.regionOf(arrs)
            case Some(x) => {
                let out = new(x, len, Scoped.regionOf(arrs));
                foldLeft((pos, a) -> arrayWrites(pos, a, out), 0, arrs);
                out
            }
        }

}
```
**Error**
```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at ca.uwaterloo.flix.language.phase.unification.BoolUnification$AND$.unapply(BoolUnification.scala:372)
	at ca.uwaterloo.flix.language.phase.unification.BoolUnification$.mkAnd(BoolUnification.scala:238)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:72)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:69)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:69)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:69)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:69)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:69)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:69)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
```

Compiler built from commit e2df900d6896132b111f0edcc3598b502e26c1ac

**Comment by magnus-madsen** [comment]
I think this is fixed in master.
