### ISSUE TITLE
Compiler crashes on `Array.intercalate`

### ISSUE THREAD

**Issue by jaschdoc** [flix/flix#3836]
The following program crashes with the following error.
```flix
def main(): Unit & Impure =
    let a = Array1.intercalate([11,12,13], []: ScopedArray[ScopedArray[Int32, _], _]);
    if (Array.sameElements(a, []: ScopedArray[Int32, _]))
        println("It works!")
    else
        println("Nope :(")

namespace Array1 {

    pub def intercalate(sep: ScopedArray[a, r1], arrs: ScopedArray[ScopedArray[a, r2], r3]): ScopedArray[a, r3] \ { Read(r1, r2, r3), Write(r3) } =
        let r3 = Scoped.regionOf(arrs);
        let count = Array.length(arrs);
        let sepLength = Array.length(sep);
        let sepCount = if (count < 2) 0 else count - 1;
        let len = sumLengths(arrs) + (sepCount * sepLength);
        match headArrays(arrs) {
            case None    => [] @ r3
            case Some(x) =>
                let out = Array.new(x, len, r3);
                let overwrite = { (st, a) ->
                    let (pos,i) = st;
                    if (i == 0) {
                        let pos1 = arrayWrites(0, a, out);
                        (pos1, 1)
                    } else {
                        let pos1 = arrayWrites(pos, sep, out);
                        let pos2 = arrayWrites(pos1, a, out);
                        (pos2, i+1)
                    }};
                Array.foldLeft(overwrite, (0, 0), arrs);
                out
        }

    def arrayWrites(pos: Int32, sub: ScopedArray[a, r1], out: ScopedArray[a, r2]): Int32 \ { Read(r1), Write(r2) } =
        Array.updateSequence!(pos, sub, out);
        pos + Array.length(sub)

    def sumLengths(arrs: ScopedArray[ScopedArray[a, r1], r2]): Int32 \ Read(r2) =
        Array.foldLeft((acc, a) -> acc + Array.length(a), 0, arrs)

    def headArrays(arrs: ScopedArray[ScopedArray[a, r1], r2]): Option[a] \ Read(r1, r2) =
        let len = Array.length(arrs);
        def loop(i) = {
            if (i >= len)
                None
            else
                match Array.head(arrs[i]) {
                    case Some(x) => Some(x)
                    case None    => loop(i + 1)
                }
        };
        loop(0)

}
```
**Error**
```
# An unexpected error has been detected by the Flix compiler:
#
#   Unexpected non-Bool kind: '???'.
#
# This is a bug in the Flix compiler. Please report it here:
#
# https://github.com/flix/flix/issues
#
# -- Flix Compiler --
#
# Flix Version : v0.28.0
#   incremental: All
#
# -- Java Virtual Machine --
#
# JVM Version  : 17.0.1 (2021-10-19)
# JVM Vendor   : Oracle Corporation
# JAVA_HOME    : /home/jaschn/.sdkman/candidates/java/17.0.1-open
# System       : Linux (5.17.9-200.fc35.x86_64)
#
# -- Stack Trace --
ca.uwaterloo.flix.util.InternalCompilerException: Unexpected non-Bool kind: '???'.
	at ca.uwaterloo.flix.language.phase.unification.BoolTable$.minimizeType(BoolTable.scala:87)
	at ca.uwaterloo.flix.language.phase.unification.BoolUnification$.successiveVariableElimination(BoolUnification.scala:140)
	at ca.uwaterloo.flix.language.phase.unification.BoolUnification$.successiveVariableElimination(BoolUnification.scala:138)
	at ca.uwaterloo.flix.language.phase.unification.BoolUnification$.booleanUnification(BoolUnification.scala:86)
	at ca.uwaterloo.flix.language.phase.unification.BoolUnification$.unify(BoolUnification.scala:65)
	at ca.uwaterloo.flix.language.phase.unification.Unification$.$anonfun$unifyBoolM$1(Unification.scala:372)
	at ca.uwaterloo.flix.language.phase.unification.InferMonad.runNext$2(InferMonad.scala:71)
	at ca.uwaterloo.flix.language.phase.unification.InferMonad.$anonfun$flatMap$2(InferMonad.scala:79)
	at ca.uwaterloo.flix.language.phase.unification.InferMonad.$anonfun$flatMap$1(InferMonad.scala:74)
	at ca.uwaterloo.flix.util.Result.flatMap(Result.scala:51)
	at ca.uwaterloo.flix.util.Result.flatMap$(Result.scala:50)
	at ca.uwaterloo.flix.util.Result$Ok.flatMap(Result.scala:77)
	at ca.uwaterloo.flix.language.phase.unification.InferMonad.runNext$2(InferMonad.scala:71)
	at ca.uwaterloo.flix.language.phase.unification.InferMonad.$anonfun$flatMap$2(InferMonad.scala:79)
	at ca.uwaterloo.flix.language.phase.unification.InferMonad.$anonfun$flatMap$1(InferMonad.scala:74)
	at ca.uwaterloo.flix.util.Result.flatMap(Result.scala:51)
	at ca.uwaterloo.flix.util.Result.flatMap$(Result.scala:50)
	at ca.uwaterloo.flix.util.Result$Ok.flatMap(Result.scala:77)
	at ca.uwaterloo.flix.language.phase.unification.InferMonad.runNext$2(InferMonad.scala:71)
	at ca.uwaterloo.flix.language.phase.unification.InferMonad.$anonfun$flatMap$2(InferMonad.scala:79)
	at ca.uwaterloo.flix.language.phase.unification.InferMonad.$anonfun$flatMap$1(InferMonad.scala:74)
	at ca.uwaterloo.flix.util.Result.flatMap(Result.scala:51)
	at ca.uwaterloo.flix.util.Result.flatMap$(Result.scala:50)
	at ca.uwaterloo.flix.util.Result$Ok.flatMap(Result.scala:77)
	at ca.uwaterloo.flix.language.phase.unification.InferMonad.runNext$2(InferMonad.scala:71)
	at ca.uwaterloo.flix.language.phase.unification.InferMonad.$anonfun$flatMap$2(InferMonad.scala:79)
	at ca.uwaterloo.flix.language.phase.unification.InferMonad.$anonfun$flatMap$1(InferMonad.scala:74)
	at ca.uwaterloo.flix.util.Result.flatMap(Result.scala:51)
	at ca.uwaterloo.flix.util.Result.flatMap$(Result.scala:50)
	at ca.uwaterloo.flix.util.Result$Ok.flatMap(Result.scala:77)
	at ca.uwaterloo.flix.language.phase.unification.InferMonad.runNext$2(InferMonad.scala:71)
	at ca.uwaterloo.flix.language.phase.unification.InferMonad.$anonfun$flatMap$2(InferMonad.scala:79)
	at ca.uwaterloo.flix.language.phase.unification.InferMonad.$anonfun$withFilter$1(InferMonad.scala:99)
	at ca.uwaterloo.flix.language.phase.unification.InferMonad.runNext$2(InferMonad.scala:71)
	at ca.uwaterloo.flix.language.phase.unification.InferMonad.$anonfun$flatMap$2(InferMonad.scala:79)
	at ca.uwaterloo.flix.language.phase.unification.InferMonad.$anonfun$withFilter$1(InferMonad.scala:99)
	at ca.uwaterloo.flix.language.phase.unification.InferMonad.runNext$2(InferMonad.scala:71)
	at ca.uwaterloo.flix.language.phase.unification.InferMonad.$anonfun$flatMap$2(InferMonad.scala:79)
	at ca.uwaterloo.flix.language.phase.unification.InferMonad.$anonfun$flatMap$1(InferMonad.scala:74)
	at ca.uwaterloo.flix.util.Result.flatMap(Result.scala:51)
	at ca.uwaterloo.flix.util.Result.flatMap$(Result.scala:50)
	at ca.uwaterloo.flix.util.Result$Ok.flatMap(Result.scala:77)
	at ca.uwaterloo.flix.language.phase.unification.InferMonad.runNext$2(InferMonad.scala:71)
	at ca.uwaterloo.flix.language.phase.unification.InferMonad.$anonfun$flatMap$2(InferMonad.scala:79)
	at ca.uwaterloo.flix.language.phase.unification.InferMonad.$anonfun$withFilter$1(InferMonad.scala:99)
	at ca.uwaterloo.flix.language.phase.unification.InferMonad.runNext$1(InferMonad.scala:57)
	at ca.uwaterloo.flix.language.phase.unification.InferMonad.$anonfun$map$2(InferMonad.scala:62)
	at ca.uwaterloo.flix.language.phase.Typer$.typeCheckDecl(Typer.scala:230)
	at ca.uwaterloo.flix.language.phase.Typer$.visitDefn(Typer.scala:143)
	at ca.uwaterloo.flix.language.phase.Typer$.$anonfun$visitDefs$2(Typer.scala:189)
	at scala.collection.parallel.mutable.ParArray$Map.leaf(ParArray.scala:664)
	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:52)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:97)
	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:55)
	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:49)
	at scala.collection.parallel.mutable.ParArray$Map.tryLeaf(ParArray.scala:655)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:169)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:156)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:303)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:149)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:148)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:303)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```
Compiler built from 2a8a0a239e9958b320adf5790244d3e71edebec8

**Comment by jaschdoc** [comment]
Perhaps somewhat more informative:
```flix
def main(): Unit & Impure =
    let a = Array1.intercalate([11,12,13], []: ScopedArray[ScopedArray[Int32, _], _]);
    let _ = Array.sameElements(a, []: ScopedArray[Int32, _]);
    println("")

namespace Array1 {

    pub def intercalate(sep: ScopedArray[a, r1], arrs: ScopedArray[ScopedArray[a, r2], r3]): ScopedArray[a, r3] \ { Read(r1, r2, r3), Write(r3) } =
        let r3 = Scoped.regionOf(arrs);
        let count = Array.length(arrs);
        let sepLength = Array.length(sep);
        let sepCount = if (count < 2) 0 else count - 1;
        let len = sumLengths(arrs) + (sepCount * sepLength);
        match headArrays(arrs) {
            case None    => [] @ r3
            case Some(x) =>
                let out = Array.new(x, len, r3);
                let overwrite = { (st, a) ->
                    let (pos,i) = st;
                    if (i == 0) {
                        let pos1 = arrayWrites(0, a, out);
                        (pos1, 1)
                    } else {
                        let pos1 = arrayWrites(pos, sep, out);
                        let pos2 = arrayWrites(pos1, a, out);
                        (pos2, i+1)
                    }};
                Array.foldLeft(overwrite, (0, 0), arrs);
                out
        }

    def arrayWrites(pos: Int32, sub: ScopedArray[a, r1], out: ScopedArray[a, r2]): Int32 \ { Read(r1), Write(r2) } =
        Array.updateSequence!(pos, sub, out);
        pos + Array.length(sub)

    def sumLengths(arrs: ScopedArray[ScopedArray[a, r1], r2]): Int32 \ Read(r2) =
        Array.foldLeft((acc, a) -> acc + Array.length(a), 0, arrs)

    def headArrays(arrs: ScopedArray[ScopedArray[a, r1], r2]): Option[a] \ Read(r1, r2) =
        let len = Array.length(arrs);
        def loop(i) = {
            if (i >= len)
                None
            else
                match Array.head(arrs[i]) {
                    case Some(x) => Some(x)
                    case None    => loop(i + 1)
                }
        };
        loop(0)

}
```
**Error**
```
# An unexpected error has been detected by the Flix compiler:
#
#   Unable to unify: 'ScopedArray[t44172, (b705607 and b705608) or (b33496 and ((not b705375) or (not (b705608 and ((not b705607) or b33498)))))] -> (ScopedArray[ScopedArray[t44172, (b705607 and b705608) or b705375], (b705607 and b705608) or (b705608 and ((not b705607) or b33498))] -> ScopedArray[t44172, (b705607 and b705608) or (b705608 and ((not (b705607 and b705608)) or (b705607 and b705608) or (b705608 and ((not (b705607 and b705608)) or (b705607 and b705608) or (b705608 and ((not b705607) or b33498))))))] & ((b705607 and b705608) or (b705608 and ((not b705607) or b33498))) and ((b705607 and b705608) or b705375) and ((b705607 and b705608) or (b705608 and ((not b705607) or b33498))) and b705607 and b705608)' and 'ScopedArray[Int32, false] -> (ScopedArray[ScopedArray[Int32, Unit], false] -> ScopedArray[Int32, false] & Impure)'.
#
# This is a bug in the Flix compiler. Please report it here:
#
# https://github.com/flix/flix/issues
#
# -- Flix Compiler --
#
# Flix Version : v0.28.0
#   incremental: All
#
# -- Java Virtual Machine --
#
# JVM Version  : 17.0.1 (2021-10-19)
# JVM Vendor   : Oracle Corporation
# JAVA_HOME    : /home/jaschn/.sdkman/candidates/java/17.0.1-open
# System       : Linux (5.17.9-200.fc35.x86_64)
#
# -- Stack Trace --
ca.uwaterloo.flix.util.InternalCompilerException: Unable to unify: 'ScopedArray[t44172, (b705607 and b705608) or (b33496 and ((not b705375) or (not (b705608 and ((not b705607) or b33498)))))] -> (ScopedArray[ScopedArray[t44172, (b705607 and b705608) or b705375], (b705607 and b705608) or (b705608 and ((not b705607) or b33498))] -> ScopedArray[t44172, (b705607 and b705608) or (b705608 and ((not (b705607 and b705608)) or (b705607 and b705608) or (b705608 and ((not (b705607 and b705608)) or (b705607 and b705608) or (b705608 and ((not b705607) or b33498))))))] & ((b705607 and b705608) or (b705608 and ((not b705607) or b33498))) and ((b705607 and b705608) or b705375) and ((b705607 and b705608) or (b705608 and ((not b705607) or b33498))) and b705607 and b705608)' and 'ScopedArray[Int32, false] -> (ScopedArray[ScopedArray[Int32, Unit], false] -> ScopedArray[Int32, false] & Impure)'.
	at ca.uwaterloo.flix.language.phase.Monomorph$.infallibleUnify(Monomorph.scala:933)
	at ca.uwaterloo.flix.language.phase.Monomorph$.specializeDef(Monomorph.scala:748)
	at ca.uwaterloo.flix.language.phase.Monomorph$.specializeDefSym(Monomorph.scala:695)
	at ca.uwaterloo.flix.language.phase.Monomorph$.visitExp$1(Monomorph.scala:267)
	at ca.uwaterloo.flix.language.phase.Monomorph$.visitExp$1(Monomorph.scala:332)
	at ca.uwaterloo.flix.language.phase.Monomorph$.visitExp$1(Monomorph.scala:352)
	at ca.uwaterloo.flix.language.phase.Monomorph$.specialize(Monomorph.scala:678)
	at ca.uwaterloo.flix.language.phase.Monomorph$.$anonfun$run$4(Monomorph.scala:200)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
	at scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:889)
	at ca.uwaterloo.flix.language.phase.Monomorph$.$anonfun$run$1(Monomorph.scala:191)
	at ca.uwaterloo.flix.api.Flix.phase(Flix.scala:566)
	at ca.uwaterloo.flix.language.phase.Monomorph$.run(Monomorph.scala:167)
	at ca.uwaterloo.flix.api.Flix.$anonfun$codeGen$2(Flix.scala:519)
	at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
	at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
	at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:74)
	at ca.uwaterloo.flix.api.Flix.$anonfun$codeGen$1(Flix.scala:518)
	at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
	at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
	at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:74)
	at ca.uwaterloo.flix.api.Flix.codeGen(Flix.scala:517)
	at ca.uwaterloo.flix.api.Flix.$anonfun$compile$1(Flix.scala:551)
	at ca.uwaterloo.flix.util.Validation$.flatMapN(Validation.scala:252)
	at ca.uwaterloo.flix.api.Flix.compile(Flix.scala:551)
	at ca.uwaterloo.flix.Main$.$anonfun$main$6(Main.scala:213)
	at ca.uwaterloo.flix.util.Timer.<init>(Timer.scala:28)
	at ca.uwaterloo.flix.Main$.main(Main.scala:213)
	at ca.uwaterloo.flix.Main.main(Main.scala)
```
Same compiler

**Comment by jaschdoc** [comment]
Also happens with regions:
```flix
def main(): Unit & Impure =
    region r {
        let a = Array1.intercalate([11,12,13], []: ScopedArray[ScopedArray[Int32, _], _]);
        let _ = Array.sameElements(a, []: ScopedArray[Int32, _]);
        ()
    };
    println("")
```

**Comment by mlutze** [comment]
This all comes down to the underscores in the type ascriptions.

Since we have incomplete kind inference, we guess that these have `Wild` kind. That's a problem for unification later since we check whether both variables have `Bool` kind before entering Boolean unification.

I conjecture that we can address this by updating the kind when we unify. For example, `unify(t1: K, t2: Wild)` calls `unify(t1: K, t2: K)`. Because a wild kind only comes from an underscore, it can only be related to one syntactic type, so I don't believe there is any risk of a real kind error involving wild kinds.

**Comment by magnus-madsen** [comment]
But can the kind not be inferred from where the underscore occurs?

**Comment by mlutze** [comment]
It's possible, but for efficiency we do not perform kind inference on expressions, only on the signature. Maybe we can do something special for wildcards.

**Comment by magnus-madsen** [comment]
Outdated.
