### ISSUE TITLE
Compiler crashes on `Array.flatten` during unification

### ISSUE THREAD

**Issue by jaschdoc** [flix/flix#3837]
The following program crashes with the following error.
```flix
def main(): Unit & Impure =
    println("")

namespace Array1 {

    pub def flatten(arrs: ScopedArray[ScopedArray[a, r1], r2]): ScopedArray[a, r2] \ { Read(r1, r2), Write(r2) } =
    let r2 = Scoped.regionOf(arrs);
    let len = sumLengths(arrs);
    match headArrays(arrs) {
        case None    => [] @ r2
        case Some(x) => {
            let out = Array.new(x, len, r2);
            Array.foldLeft((pos, a) -> arrayWrites(pos, a, out), 0, arrs);
            out
        }
    }

    def arrayWrites(pos: Int32, sub: ScopedArray[a, r1], out: ScopedArray[a, r2]): Int32 \ { Read(r1), Write(r2) } =
        Array.updateSequence!(pos, sub, out);
        pos + Array.length(sub)

    def sumLengths(arrs: ScopedArray[ScopedArray[a, r1], r2]): Int32 \ Read(r2) =
        Array.foldLeft((acc, a) -> acc + Array.length(a), 0, arrs)

    def headArrays(arrs: ScopedArray[ScopedArray[a, r1], r2]): Option[a] \ Read(r1, r2) =
        let len = Array.length(arrs);
        def loop(i) = {
            if (i >= len)
                None
            else
                match Array.head(arrs[i]) {
                    case Some(x) => Some(x)
                    case None    => loop(i + 1)
                }
        };
        loop(0)
}
```
**Error**
```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at ca.uwaterloo.flix.language.phase.unification.BoolUnification$NOT$.unapply(BoolUnification.scala:364)
	at ca.uwaterloo.flix.language.phase.unification.BoolUnification$.mkAnd(BoolUnification.scala:222)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:72)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:69)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:69)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:69)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:69)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:69)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:69)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
	at ca.uwaterloo.flix.language.phase.unification.Substitution.visit$1(Substitution.scala:68)
```
Compiler built from 2a8a0a239e9958b320adf5790244d3e71edebec8

**Comment by jaschdoc** [comment]
Duplicate oops, see #3811
