### ISSUE TITLE
Self contained jar file does not contain ca.uwaterloo.flix.runtime.interpreter.Channel

### ISSUE THREAD

**Issue by battisti** [flix/flix#3855]
Running the following program via `java -jar ./flix.jar run` shows "Meow!" as expected.

```scala
def meow(c: Channel[String], n: Int32): Unit & Impure =
    match n {
        case 0 => ()
        case x => c <- "Meow!"; meow(c, x - 1)
    }

def main(): Unit & Impure =
    let c = chan String 0;
    spawn meow(c, 1);
    select {
        case m <- c => m        
    } |> println
```

Running it by creating a self contained jar file via:

```bash
> java -jar ./flix.jar build
> java -jar ./flix.jar build-jar
> java -jar example.jar
```

Results in a `java.lang.ClassNotFoundException`:

```bash
> java -jar example.jar
Exception in thread "main" java.lang.NoClassDefFoundError: ca/uwaterloo/flix/runtime/interpreter/Channel
        at Def%main%.invoke(Unknown Source)
        at Cont%Obj.unwind(Cont%Obj)
        at Ns.m_main%(Unknown Source)
        at Main.main(Main)
Caused by: java.lang.ClassNotFoundException: ca.uwaterloo.flix.runtime.interpreter.Channel
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 4 more
```

**Comment by battisti** [comment]
If relevant my computer is an `Apple M1 Max` and the JVM is:

```bash
openjdk version "17.0.3" 2022-04-19
OpenJDK Runtime Environment GraalVM CE 22.1.0 (build 17.0.3+7-jvmci-22.1-b06)
OpenJDK 64-Bit Server VM GraalVM CE 22.1.0 (build 17.0.3+7-jvmci-22.1-b06, mixed mode, sharing)
```

**Comment by magnus-madsen** [comment]
This should work:

```
java -jar c:\\tmp\\flix2\\flix.jar build
java -jar c:\\tmp\\flix2\\flix.jar build-jar
java -classpath "flix2.jar;flix.jar" Main
```

Assuming `Main.flix` is in `src` and contains the above program. 

(Note here my project is called `flix2`. Your project name may vary. Note also that the `flix2.jar` must come before the `flix.jar` in the class path).

**Comment by battisti** [comment]
Yes thanks that works! For posterity in case something runs into problem using Linux or macOS (assuming the project name is example) the shell command looks like that (i.e. ':' instead of ';'):

`example>  java -classpath "example.jar:flix.jar" Main`

**Comment by magnus-madsen** [comment]
This problem will eventually go away, once we transition to Concurrency 2.0

**Comment by magnus-madsen** [comment]
We are aware and will update accordingly.
