### ISSUE TITLE
Compiler crashes during solve

### ISSUE THREAD

**Issue by paulbutcher** [flix/flix#3931]
The following program crashes the compiler:

```
def main(): Unit & Impure =
    let rules = #{
        Edge(1, 2).
        Edge(2, 3).
        Path(x, y) :- Edge(x, y).
        Path(x, z) :- Path(x, y), Edge(y, z).
    };
    let paths = solve rules project Paths;
    println("Hello world")
```

with:

```
# An unexpected error has been detected by the Flix compiler:
#
#   Unexpected type: ''117281.'
#
# This is a bug in the Flix compiler. Please report it here:
#
# https://github.com/flix/flix/issues
#
# -- Flix Compiler --
#
# Flix Version : v0.28.0
#   incremental: All
#
# -- Java Virtual Machine --
#
# JVM Version  : 18.0.1.1 (2022-04-22)
# JVM Vendor   : Oracle Corporation
# JAVA_HOME    : /Users/paulbutcher/Library/Java/JavaVirtualMachines/openjdk-18.0.1.1/Contents/Home
# System       : Mac OS X (12.4)
#
# -- Stack Trace --
ca.uwaterloo.flix.util.InternalCompilerException: Unexpected type: ''117281.'
	at ca.uwaterloo.flix.language.phase.Stratifier$.ca$uwaterloo$flix$language$phase$Stratifier$$termTypes(Stratifier.scala:786)
	at ca.uwaterloo.flix.language.phase.Stratifier$.visitType$1(Stratifier.scala:731)
	at ca.uwaterloo.flix.language.phase.Stratifier$.predicateSymbolsOf(Stratifier.scala:744)
	at ca.uwaterloo.flix.language.phase.Stratifier$.stratify(Stratifier.scala:714)
	at ca.uwaterloo.flix.language.phase.Stratifier$.visitExp(Stratifier.scala:383)
	at ca.uwaterloo.flix.language.phase.Stratifier$.visitExp(Stratifier.scala:157)
	at ca.uwaterloo.flix.language.phase.Stratifier$.visitDef(Stratifier.scala:88)
	at ca.uwaterloo.flix.language.phase.Stratifier$.$anonfun$run$8(Stratifier.scala:61)
	at scala.collection.parallel.mutable.ParArray$Map.leaf(ParArray.scala:664)
	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:52)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:97)
	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:55)
	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:49)
	at scala.collection.parallel.mutable.ParArray$Map.tryLeaf(ParArray.scala:655)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:169)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:156)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:303)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:149)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:148)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:303)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)


Unexpected type: ''117281.'
```

**Comment by magnus-madsen** [comment]
Indeed a bug. But the program also has a mistake, the project should be Path in singular.

**Comment by paulbutcher** [comment]
Indeed. Still something the compiler should handle gracefully though?

**Comment by paulbutcher** [comment]
(sorry - I should have indicated in the bug report that I knew it was an incorrect program)

**Comment by magnus-madsen** [comment]
Yes. The compiler should never crash.

**Comment by magnus-madsen** [comment]
Fixed.
