### ISSUE TITLE
Running the repl in "empty" folder gives `NoSuchFileException`

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#4113]
```
PS C:\Users\m\Desktop\JAR> java -jar flix.jar
     __   _   _
    / _| | | (_)            Welcome to Flix v0.29.0
   | |_  | |  _  __  __
   |  _| | | | | \ \/ /     Enter an expression to have it evaluated.
   | |   | | | |  >  <      Type ':help' for more information.
   |_|   |_| |_| /_/\_\     Type ':quit' or press 'ctrl + d' to exit.

Exception in thread "main" java.nio.file.NoSuchFileException: C:\Users\m\Desktop\JAR\src
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:53)
        at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(WindowsFileAttributeViews.java:38)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(WindowsFileSystemProvider.java:199)
        at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
        at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:220)
        at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:277)
        at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:323)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2804)
```

**Comment by paulbutcher** [comment]
Ah - yes, of course.

And yes, I think we need a better way of determining what makes a project a project (right now it insists on a very specific structure—I don't think, for example, that deleting the `README.md` should stop your project from being a project!).

I suggest that we punt this until we come up with a proper design for how dependency management should work (because the two things are intimately related)?

**Comment by magnus-madsen** [comment]
OK, but can we have a temporary solution? I don't want flix to crash when you just type `java -jar flix.jar`-- that should work out of the box :)

**Comment by paulbutcher** [comment]
Yes, fair enough - I'll see if I can come up with a stopgap solution

**Comment by magnus-madsen** [comment]
I'd like to release a new stable version next week (because Nicola has almost wrapped up the InlayHintProvider). It would be nice if this could be fixed before then :)

**Comment by paulbutcher** [comment]
Apologies: this wasn't what I assumed it was, it was a simple screw up on my part (I lost the call to `isProjectDir` when switching to `SourceProvider` from my original solution using `Either` (blush).

**Comment by magnus-madsen** [comment]
Thanks and no worries :)
