### ISSUE TITLE
Kinder/Boolean bug in foreach

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#4432]
```
def example(): Unit = {
    foreach(e <- fun) e
}

def fun(r: Region[r], i: Int32): Iterator[Int32, r] \ r = ??? as \ r
```
<details>
<summary> Output </summary>

```
java : Exception in thread "main" java.lang.StackOverflowError
	at ca.uwaterloo.flix.language.ast.Type.typeVars(Type.scala:52)
	at ca.uwaterloo.flix.language.ast.Type.typeVars$(Type.scala:49)
	at ca.uwaterloo.flix.language.ast.Type$Apply.typeVars(Type.scala:498)
	at ca.uwaterloo.flix.language.ast.Type.typeVars(Type.scala:52)
	at ca.uwaterloo.flix.language.ast.Type.typeVars$(Type.scala:49)
	at ca.uwaterloo.flix.language.ast.Type$Apply.typeVars(Type.scala:498)
	at ca.uwaterloo.flix.language.ast.Type.typeVars(Type.scala:52)
	at ca.uwaterloo.flix.language.ast.Type.typeVars$(Type.scala:49)
	at ca.uwaterloo.flix.language.ast.Type$Apply.typeVars(Type.scala:498)
	at ca.uwaterloo.flix.language.ast.Type.typeVars(Type.scala:52)
	at ca.uwaterloo.flix.language.ast.Type.typeVars$(Type.scala:49)
	at ca.uwaterloo.flix.language.ast.Type$Apply.typeVars(Type.scala:498)
	at ca.uwaterloo.flix.language.ast.Type.typeVars(Type.scala:52)
	at ca.uwaterloo.flix.language.ast.Type.typeVars$(Type.scala:49)
	at ca.uwaterloo.flix.language.ast.Type$Apply.typeVars(Type.scala:498)
	at ca.uwaterloo.flix.language.ast.Type.typeVars(Type.scala:52)
	at ca.uwaterloo.flix.language.ast.Type.typeVars$(Type.scala:49)
	at ca.uwaterloo.flix.language.ast.Type$Apply.typeVars(Type.scala:498)
	at ca.uwaterloo.flix.language.ast.Type.typeVars(Type.scala:52)
	at ca.uwaterloo.flix.language.ast.Type.typeVars$(Type.scala:49)
	at ca.uwaterloo.flix.language.ast.Type$Apply.typeVars(Type.scala:498)
	at ca.uwaterloo.flix.language.ast.Type.typeVars(Type.scala:52)
	at ca.uwaterloo.flix.language.ast.Type.typeVars$(Type.scala:49)
	at ca.uwaterloo.flix.language.ast.Type$Apply.typeVars(Type.scala:498)
	at ca.uwaterloo.flix.language.ast.Type.typeVars(Type.scala:52)
	at ca.uwaterloo.flix.language.ast.Type.typeVars$(Type.scala:49)
	at ca.uwaterloo.flix.language.ast.Type$Apply.typeVars(Type.scala:498)
	at ca.uwaterloo.flix.language.ast.Type.typeVars(Type.scala:52)
	at ca.uwaterloo.flix.language.ast.Type.typeVars$(Type.scala:49)
	at ca.uwaterloo.flix.language.ast.Type$Apply.typeVars(Type.scala:498)
	at ca.uwaterloo.flix.language.phase.unification.BoolUnification$.satisfiable(BoolUnification.scala:160)
	at ca.uwaterloo.flix.language.phase.unification.BoolUnification$.successiveVariableElimination(BoolUnification.scala:130)
	at ca.uwaterloo.flix.language.phase.unification.BoolUnification$.satisfiable(BoolUnification.scala:160)
	at ca.uwaterloo.flix.language.phase.unification.BoolUnification$.successiveVariableElimination(BoolUnification.scala:130)
	at ca.uwaterloo.flix.language.phase.unification.BoolUnification$.satisfiable(BoolUnification.scala:160)
	at ca.uwaterloo.flix.language.phase.unification.BoolUnification$.successiveVariableElimination(BoolUnification.scala:130)
	at ca.uwaterloo.flix.language.phase.unification.BoolUnification$.satisfiable(BoolUnification.scala:160)
	at ca.uwaterloo.flix.language.phase.unification.BoolUnification$.successiveVariableElimination(BoolUnification.scala:130)
	at ca.uwaterloo.flix.language.phase.unification.BoolUnification$.satisfiable(BoolUnification.scala:160)
	at ca.uwaterloo.flix.language.phase.unification.BoolUnification$.successiveVariableElimination(BoolUnification.scala:130)
	at ca.uwaterloo.flix.language.phase.unification.BoolUnification$.satisfiable(BoolUnification.scala:160)
	....
```
</details>

**Comment by magnus-madsen** [comment]
I get a type error now.
