### ISSUE TITLE
Introduce Constant Pool

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#446]
In fixing #445, we lift every single constant to a top-level function.

The problem with this is that if you have many constants (e.g. 65.000+) this will not work.

The solution is to avoid duplication of constants that are the same.

For example, right now we might lift:

```
P(42, 42)
```

to 

```
P(lit$1(), lit2$())
def lit$1(): Int = 42
def lit$2(): Int = 42
```

but there is no reason we could not use the same top-level function for the value 42.

The idea would be to introduce some intermediary map to hold constants and ensure that there is no duplication in this map.

**Comment by magnus-madsen** [comment]
```
Exception in thread "main" java.lang.RuntimeException: Class file too large!
	at org.objectweb.asm.ClassWriter.toByteArray(Unknown Source)
	at ca.uwaterloo.flix.language.phase.CodeGen$.compile(CodeGen.scala:193)
	at ca.uwaterloo.flix.language.phase.CodeGen$$anonfun$8.apply(CodeGen.scala:123)
	at ca.uwaterloo.flix.language.phase.CodeGen$$anonfun$8.apply(CodeGen.scala:122)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at ca.uwaterloo.flix.language.phase.CodeGen$.run(CodeGen.scala:122)
	at ca.uwaterloo.flix.language.phase.CodeGen$.run(CodeGen.scala:36)
```

So this is something we need to think about now.
