### ISSUE TITLE
Compiler crash with mixed lattice/non-lattice semantics

### ISSUE THREAD

**Issue by paulbutcher** [flix/flix#4719]
The following compiles without error, but crashes (I think because of the mixed lattice/non-lattice semantics):

```
pub def main(): List[(String, Int32)] = 
    let rules = #{
        Foo("a", 1).
        Foo("b", 2).

        Bar(n; v) :- Foo(n, v).
    };
    query rules select (x, y) from Bar(x; y)
```

```
********************************************************************************
**
**  BUG: Mismatched types.
**
********************************************************************************

Exception in thread "main" dev.flix.runtime.HoleError: Hole '?panic' at Prelude.flix:285:5
	at Def%bug%exclamation%179493.invoke(Unknown Source)
	at Cont%Obj.unwind(Cont%Obj)
	at Array.Clo%compare%193989.invoke(Unknown Source)
	at Cont%Obj.unwind(Cont%Obj)
	at Fixpoint.Tuple.Def%compare%179003.invoke(Unknown Source)
	at Cont%Obj.unwind(Cont%Obj)
	at RedBlackTree.Def%memberOf%179657.invoke(Unknown Source)
	at Cont%Bool.unwind(Cont%Bool)
	at Fixpoint.Clo%evalBoolExp%194146.invoke(Unknown Source)
	at Cont%Bool.unwind(Cont%Bool)
	at List.Def%forall%178725.invoke(Unknown Source)
	at Cont%Bool.unwind(Cont%Bool)
	at Fixpoint.Def%evalOp%178694.invoke(Unknown Source)
	at Cont%Obj.unwind(Cont%Obj)
	at RedBlackTree.Def%foreach%175807.invoke(Unknown Source)
	at Cont%Obj.unwind(Cont%Obj)
	at List.Def%foreach%178711.invoke(Unknown Source)
	at Cont%Obj.unwind(Cont%Obj)
	at Fixpoint.Def%evalStmt%178688.invoke(Unknown Source)
	at Cont%Obj.unwind(Cont%Obj)
	at List.Def%foreach%178711.invoke(Unknown Source)
	at Cont%Obj.unwind(Cont%Obj)
	at Fixpoint.Def%interpretWithDatabase%176089.invoke(Unknown Source)
	at Cont%Obj.unwind(Cont%Obj)
	at Fixpoint.Clo%solve%193987.invoke(Unknown Source)
	at Cont%Obj.unwind(Cont%Obj)
	at Def%main%.invoke(Unknown Source)
	at Cont%Obj.unwind(Cont%Obj)
	at Ns.m_main%(Unknown Source)
	at Main.main(Main)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at ca.uwaterloo.flix.language.phase.jvm.Bootstrap$.mainFunction$1(Bootstrap.scala:79)
	at ca.uwaterloo.flix.language.phase.jvm.Bootstrap$.$anonfun$bootstrap$9(Bootstrap.scala:88)
	at ca.uwaterloo.flix.language.phase.jvm.Bootstrap$.$anonfun$bootstrap$9$adapted(Bootstrap.scala:88)
	at ca.uwaterloo.flix.tools.Packager$.$anonfun$run$2(Packager.scala:321)
	at scala.Option.map(Option.scala:242)
	at ca.uwaterloo.flix.tools.Packager$.$anonfun$run$1(Packager.scala:319)
	at scala.Option.flatMap(Option.scala:283)
	at ca.uwaterloo.flix.tools.Packager$.run(Packager.scala:318)
	at ca.uwaterloo.flix.Main$.main(Main.scala:149)
	at ca.uwaterloo.flix.Main.main(Main.scala)
```

**Comment by magnus-madsen** [comment]
@JonathanStarup Could you investigate? You don't have to fix.

**Comment by magnus-madsen** [comment]
Something with the fact that Bar is 1-ary. (Probably broken Lowering or something like that).

**Comment by paulbutcher** [comment]
@magnus-madsen is correct. The following compiles and runs correctly:

```
pub def main(): List[(String, Int32)] = 
    let rules = #{
        Foo("a", 1).
        Foo("b", 2).

        Bar("dummy", n; v) :- Foo(n, v).
    };
    query rules select (x, y) from Bar(_, x; y)
```

**Comment by JonathanStarup** [comment]
Sidenote, we should really do something about the sourcelocation of `bug!` and `unreachable!`. Currently you always get the confusing jvm stack and the prelude sourcelocation. It is much more useful to use `?something` directly since you get the actual sourcelocation instead of prelude

**Comment by JonathanStarup** [comment]
Here's some engine debugging, it seems that the arity of `Bar` becomes 3 at some point
```
********************************************************************************
** Datalog Input
********************************************************************************

    Foo(BoxedObject(a, Obj -> Obj, Obj -> Obj), BoxedInt32(1)).
    Foo(BoxedObject(b, Obj -> Obj, Obj -> Obj), BoxedInt32(2)).
    %Result(VarSym(x)) :- fix Bar(VarSym(x); _).
    Bar(VarSym(n); VarSym(v)) :- Foo(VarSym(n), VarSym(v)).


********************************************************************************
** Relation Algebra Machine AST
********************************************************************************

    // Foo(BoxedObject(a, Obj -> Obj, Obj -> Obj), BoxedInt32(1)).;
    project (BoxedObject(a, Obj -> Obj, Obj -> Obj), BoxedInt32(1)) into Foo;
    // Foo(BoxedObject(b, Obj -> Obj, Obj -> Obj), BoxedInt32(2)).;
    project (BoxedObject(b, Obj -> Obj, Obj -> Obj), BoxedInt32(2)) into Foo;
    // Bar(VarSym(n); VarSym(v)) :- Foo(VarSym(n), VarSym(v)).;
    merge Foo into Bar;
    merge Bar into ΔBar;
    until(ΔBar == ∅) do
        purge ΔBar';
        // Bar(VarSym(n); VarSym(v)) :- Foo(VarSym(n), VarSym(v)).;
        merge ΔBar' into Bar;
        ΔBar := ΔBar'
    end;
    // %Result(VarSym(x)) :- fix Bar(VarSym(x); _).;
    search 0$ ∈ Bar do
        project (0$[0]) into %Result
    end;
    merge %Result into Δ%Result;
    until(Δ%Result == ∅) do
        purge Δ%Result';
        // %Result(VarSym(x)) :- fix Bar(VarSym(x); _).;
        search 0$ ∈ Bar do
            if((0$[0]) ∉ %Result) then
                project (0$[0]) into Δ%Result'
            end
        end;
        merge Δ%Result' into %Result;
        Δ%Result := Δ%Result'
    end


********************************************************************************
** Minimal Model
********************************************************************************

    %Result(BoxedObject(a, Obj -> Obj, Obj -> Obj)).
    %Result(BoxedObject(b, Obj -> Obj, Obj -> Obj)).
    Bar(BoxedObject(a, Obj -> Obj, Obj -> Obj), BoxedInt32(1); null).
    Bar(BoxedObject(b, Obj -> Obj, Obj -> Obj), BoxedInt32(2); null).
    Foo(BoxedObject(a, Obj -> Obj, Obj -> Obj), BoxedInt32(1)).
    Foo(BoxedObject(b, Obj -> Obj, Obj -> Obj), BoxedInt32(2)).


a :: b :: Nil

Process finished with exit code 0

```

**Comment by emk** [comment]
Hello! I was experimenting with Flix, because I found the integrated Datalog to be particularly fascinating. Thank you for this interesting bit of research, and for packaging it so cleanly for the public.

I was trying to build a simple type inferencer for a tiny subset of BigQuery SQL, where each expression was tagged with an `ExprID`. My Datalog rules look like this:

```
    pub def facts(e: Expr): #{
        Lit(ExprID, Type),
        Array(ExprID),
        ArrayElem(ExprID, ExprID) | r
    } = match e {
        case Expr.Lit(id, lit) =>
            // Associate literal expression IDs with their types.
            inject (id, Lit.typeOf(lit)) :: Nil into Lit
        case Expr.Array(id, elem_exprs) =>
            // Declare arrays.
            let array = inject id :: Nil into Array;
            // Associate arrays with their elements.
            let elems = inject List.map(elem_expr -> (id, Expr.id(elem_expr)), elem_exprs) into ArrayElem;
            // Get recursive type facts for the elements.
            let elem_type_facts = List.map(elem_expr -> Expr.facts(elem_expr), elem_exprs);
            // Combine our facts.
            List.foldLeft((f1, f2) -> f1 <+> f2, array <+> elems, elem_type_facts)
    }

    pub def inferTypes(e: Expr): Map[ExprID, Type] =
        // Get all our raw facts.
        let facts = Expr.facts(e);
        //debug(facts);

        // Define our inference rules.
        let rules = #{
            TypeOf(lit_id; t) :- Lit(lit_id, t).
            TypeOf(array_id; Type.Array(Type.Unknown)) :- Array(array_id).
            TypeOf(array_id; Type.Array(t)) :- ElemTypeOf(array_id; t).
            TypeOf(array_id; Type.Inconsistent) :-
                ElemTypeOf(array_id; t),
                if (t == Type.Inconsistent).

            ElemTypeOf(array_id; t) :- ArrayElem(array_id, elem_id), TypeOf(elem_id; t).
        };

        query rules, facts select (id, t) from TypeOf(id; t) |> Vector.toMap
```

This fails with:

```
FAIL  testTypeOfComplexArray
         /home/emk/src/flix/test/TestTypes.flix:20
    ********************************************************************************
    **
    **  BUG: Reached unreachable expression.
    **
    ********************************************************************************
    
    dev.flix.runtime.HoleError: Hole '?panic' at Prelude.flix:163:5
        at Boxable.Def$unbox$135102.applyFrame(Unknown Source)
        at Boxable.Def$unbox$135102.invoke(Unknown Source)
        at Boxable.Clo$lift2b$165344.applyFrame(Unknown Source)
        at Boxable.Clo$lift2b$165344.invoke(Unknown Source)
        at Fixpoint.Def$evalOp$138152.applyFrame(Unknown Source)
        at Fixpoint.Def$evalOp$138152.invoke(Unknown Source)
        at RedBlackTree.Def$queryWith$141528.applyFrame(Unknown Source)
        at RedBlackTree.Def$queryWith$141528.invoke(Unknown Source)
        at RedBlackTree.Def$forEach$136105.applyFrame(Unknown Source)
        at RedBlackTree.Def$forEach$136105.invoke(Unknown Source)
        at RedBlackTree.Def$forEach$136105.applyFrame(Unknown Source)
        at RedBlackTree.Def$forEach$136105.invoke(Unknown Source)
        at Vector.Clo$forEach$165594.applyFrame(Unknown Source)
        at Vector.Clo$forEach$165594.invoke(Unknown Source)
        at Vector.Def$forEach$136981.applyFrame(Unknown Source)
        at Vector.Def$forEach$136981.invoke(Unknown Source)
        at Fixpoint.Clo$solveWithStratification$165835.applyFrame(Unknown Source)
        at Fixpoint.Clo$solveWithStratification$165835.invoke(Unknown Source)
        at Fixpoint.Def$solveWithStratification$135195.applyFrame(Unknown Source)
        at Fixpoint.Def$solveWithStratification$135195.invoke(Unknown Source)
        at Expr.Def$inferTypes.applyFrame(Unknown Source)
        at Expr.Def$inferTypes.invoke(Unknown Source)
        at Def$testTypeOfComplexArray.applyFrame(Unknown Source)
        at Def$testTypeOfComplexArray.invoke(Unknown Source)
        at Ns.m_testTypeOfComplexArray(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.$anonfun$link$2(JvmBackend.scala:224)
        at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.$anonfun$getCompiledDefs$2(JvmBackend.scala:199)
        at ca.uwaterloo.flix.tools.Tester$TestRunner.runTest(Tester.scala:197)
        at ca.uwaterloo.flix.tools.Tester$TestRunner.$anonfun$run$7(Tester.scala:168)
        at ca.uwaterloo.flix.tools.Tester$TestRunner.$anonfun$run$7$adapted(Tester.scala:167)
        at scala.collection.immutable.Vector.foreach(Vector.scala:2122)
        at ca.uwaterloo.flix.tools.Tester$TestRunner.run(Tester.scala:167)
```

I can confirm that adding a `"dummy"` argument to `TypeOf` and `ElemTypeOf` (as described above) works around this issue. I can provide a full program if that helps, but I suspect this is just a more complicated version of your existing test case. Please let me know if there's anything I can do to help debug this!

Also, is there a way to rewrite code without using "mixed lattice/non-lattice semantics"?

**Comment by magnus-madsen** [comment]
I have been debugging a bit. Current progress is that in:

```
pub def main(): Vector[(String, Int32)] =
    let rules = #{
        Foo("a", 1).
        Foo("b", 2).
        //Foo("b", 3).

        Bar(n; v) :- Foo(n, v). // here
    };
    query rules select (x, y) from Bar(x; y)
```

it seems that `v` is LOADED from the lattice environment, but that is obviously not where it actually is. This happens because that is its DESTINATION.

**Comment by magnus-madsen** [comment]
Disabling the (Datalog) simplifier solve this problem, but then some other tests fail :/

**Comment by magnus-madsen** [comment]
A potential fix is available in https://github.com/flix/flix/pull/6870

**Comment by magnus-madsen** [comment]
> Hello! I was experimenting with Flix, because I found the integrated Datalog to be particularly fascinating. Thank you for this interesting bit of research, and for packaging it so cleanly for the public.

Again, thanks for the kind words!

> I was trying to build a simple type inferencer for a tiny subset of BigQuery SQL, where each expression was tagged with an ExprID. My Datalog rules look like this:

Cool

> Also, is there a way to rewrite code without using "mixed lattice/non-lattice semantics"?

What do you mean?
