### ISSUE TITLE
NoSuchElementException: key not found: TupleClassName(List(WrappedPrimitive(Int32), WrappedPrimitive(Int32)))

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#476]
The fragment:

```
def f(p: (Int, Int)): Int = 42
```

triggers:

```
Exception in thread "main" java.util.NoSuchElementException: key not found: TupleClassName(List(WrappedPrimitive(Int32), WrappedPrimitive(Int32)))
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.MapLike$class.apply(MapLike.scala:141)
	at scala.collection.AbstractMap.apply(Map.scala:59)
	at ca.uwaterloo.flix.language.phase.LoadBytecode$.ca$uwaterloo$flix$language$phase$LoadBytecode$$toJavaClass(LoadBytecode.scala:187)
	at ca.uwaterloo.flix.language.phase.LoadBytecode$$anonfun$run$2$$anonfun$apply$2$$anonfun$10.apply(LoadBytecode.scala:151)
	at ca.uwaterloo.flix.language.phase.LoadBytecode$$anonfun$run$2$$anonfun$apply$2$$anonfun$10.apply(LoadBytecode.scala:151)
```

**Comment by magnus-madsen** [comment]
My guess is that you also need to traverse the types in the formal parameters.

**Comment by magnus-madsen** [comment]
Fixed.
