### ISSUE TITLE
Parsing of Unary Lambda with Typed Argument

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#518]
```
def f(): Int = (x: Int -> x + 1)(42)
```

```
Exception in thread "main" java.util.NoSuchElementException: key not found: x
	at scala.collection.immutable.Map$EmptyMap$.apply(Map.scala:97)
	at scala.collection.immutable.Map$EmptyMap$.apply(Map.scala:95)
	at ca.uwaterloo.flix.language.phase.Namer$Types$.visit$3(Namer.scala:690)
	at ca.uwaterloo.flix.language.phase.Namer$Types$.visit$3(Namer.scala:700)
	at ca.uwaterloo.flix.language.phase.Namer$Types$.namer(Namer.scala:704)
	at ca.uwaterloo.flix.language.phase.Namer$Expressions$.$anonfun$namer$56(Namer.scala:451)
	at ca.uwaterloo.flix.util.Validation.map(Validation.scala:29)
	at ca.uwaterloo.flix.util.Validation.map$(Validation.scala:28)
```

**Comment by magnus-madsen** [comment]
Still an issue as-of today.

**Comment by magnus-madsen** [comment]
Its ambiguous anyway. Today we give a nice error, so that is okay.
