### ISSUE TITLE
Crash of Flix compiler: `No default or matching definition found for 'PartialOrder.lessEqual'.`

### ISSUE THREAD

**Issue by thomas-colcombet** [flix/flix#5181]
The following code generates for me an internal error of the compiler.
It works by (1) defining a type BLattice[a] to be used in datalog constraints, then (2) use it at the very end just to produce an error.

The compiler fails, with internal error:
```
No default or matching definition found for 'PartialOrder.lessEqual'.
```

The detail of the crash report is to be found below.

```
/// BLattice[a]: the type a plus bot and top
enum BLattice[a] {
	case Val(a),
	case Bot,
	case Top
}

instance Boxable[BLattice[a]] with Boxable[a]

type alias L_String = BLattice[String]

def toBLattice(x : a): BLattice[a] = Val(x)

instance ToString[BLattice[a]] with ToString[a] {
	pub def toString( c:BLattice[a] ): String  with ToString[a]= match c {
		case Bot		=> "Bot"
		case Top		=> "Top"
		case Val(v)	=> ToString.toString(v)
		}
}

instance Eq[BLattice[a]] with Eq[a] {
	pub def eq(x : BLattice[a], y:BLattice[a]):Bool  with Eq[a] =
		match (x,y) {
			case (Bot,Bot)       => true
			case (Top,Top)       => true
			case (Val(a),Val(b)) => Eq.eq(a,b)
			case _               => false
	}
}

instance Order[BLattice[a]] with Order[a] {
	pub def compare(x : BLattice[a], y:BLattice[a]):Comparison  with Order[a] =
		match (x,y) {
			case (Bot,Bot) => Comparison.EqualTo
			case (Top,Top) => Comparison.EqualTo
			case (Bot,_)   => Comparison.LessThan
			case (Top,_)   => Comparison.GreaterThan
			case (_,Top)   => Comparison.LessThan
			case (_,Bot)   => Comparison.GreaterThan
			case (Val(a),Val(b)) => Order.compare(a,b)
	}
}

instance LowerBound[BLattice[a]] {
	pub def minValue(): BLattice[a] = BLattice.Bot
}

instance PartialOrder[BLattice[a]] with Eq[a] {
	pub def lessEqual(x : BLattice[a], y:BLattice[a]):Bool with Eq[a] =
		match (x,y) {
		case (Bot,_) => true
		case (_,Top) => true
		case (Val(a),Val(b)) => Eq.eq(a,b)
		case _ => false
		}
}

instance JoinLattice[BLattice[a]] with Eq[a] {
	pub def leastUpperBound(x : BLattice[a], y:BLattice[a]):BLattice[a] with Eq[a] =
		match (x,y) {
		case (Bot,_) => y
		case (_,Bot) => x
		case (Val(a),Val(b)) => if (Eq.eq(a,b)) x else Top
		case _ => Top
		}
}

instance MeetLattice[BLattice[a]] with Eq[a] {
	pub def greatestLowerBound(x : BLattice[a], y:BLattice[a]):BLattice[a] with Eq[a] =
		match (x,y) {
		case (Top,_) => y
		case (_,Top) => x
		case (Val(a),Val(b)) => if (Eq.eq(a,b)) x else Bot
		case _ => Bot
	}
}

/// Real part f the code

type alias System = #{
		Type(Int32, String; L_String),
		FlowLink(Int32,Int32)
	}

def propTypes(): System = #{
	Type(l1,v; t) :- FlowLink(l1,l2), Type(l2,v; t).
}

def main(): Unit \ IO =
	let _pt = solve propTypes();
	println(0)
```

Crash report:
```
#
# An unexpected error has been detected by the Flix compiler:
#
#   No default or matching definition found for 'PartialOrder.lessEqual'.
#
# This is a bug in the Flix compiler. Please report it here:
#
# https://github.com/flix/flix/issues
#
# -- Flix Compiler --
#
# Flix Version : v0.34.0
#   incremental: All
#
# -- Java Virtual Machine --
#
# JVM Version  : 11.0.17 (2022-10-18)
# JVM Vendor   : Homebrew
# JAVA_HOME    : /usr/local/Cellar/openjdk@11/11.0.17/libexec/openjdk.jdk/Contents/Home
# System       : Mac OS X (11.7)
#
# -- Stack Trace --
ca.uwaterloo.flix.util.InternalCompilerException: No default or matching definition found for 'PartialOrder.lessEqual'.
        at ca.uwaterloo.flix.language.phase.Monomorph$.specializeSigSym(Monomorph.scala:645)
        at ca.uwaterloo.flix.language.phase.Monomorph$.visitExp$1(Monomorph.scala:271)
        at ca.uwaterloo.flix.language.phase.Monomorph$.visitExp$1(Monomorph.scala:284)
        at ca.uwaterloo.flix.language.phase.Monomorph$.visitExp$1(Monomorph.scala:280)
        at ca.uwaterloo.flix.language.phase.Monomorph$.visitExp$1(Monomorph.scala:280)
        at ca.uwaterloo.flix.language.phase.Monomorph$.$anonfun$specialize$12(Monomorph.scala:401)
        at scala.collection.immutable.List.map(List.scala:250)
        at ca.uwaterloo.flix.language.phase.Monomorph$.visitExp$1(Monomorph.scala:401)
        at ca.uwaterloo.flix.language.phase.Monomorph$.visitExp$1(Monomorph.scala:397)
        at ca.uwaterloo.flix.language.phase.Monomorph$.specialize(Monomorph.scala:599)
        at ca.uwaterloo.flix.language.phase.Monomorph$.$anonfun$run$1(Monomorph.scala:221)
        at ca.uwaterloo.flix.api.Flix.phase(Flix.scala:595)
        at ca.uwaterloo.flix.language.phase.Monomorph$.run(Monomorph.scala:163)
        at ca.uwaterloo.flix.api.Flix.$anonfun$codeGen$3(Flix.scala:548)
        at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
        at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
        at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:79)
        at ca.uwaterloo.flix.api.Flix.$anonfun$codeGen$2(Flix.scala:547)
        at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
        at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
        at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:79)
        at ca.uwaterloo.flix.api.Flix.$anonfun$codeGen$1(Flix.scala:546)
        at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
        at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
        at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:79)
        at ca.uwaterloo.flix.api.Flix.codeGen(Flix.scala:545)
        at ca.uwaterloo.flix.api.Flix.$anonfun$compile$1(Flix.scala:580)
        at ca.uwaterloo.flix.util.Validation$.flatMapN(Validation.scala:268)
        at ca.uwaterloo.flix.api.Flix.compile(Flix.scala:580)
        at ca.uwaterloo.flix.tools.Packager$.build(Packager.scala:185)
        at ca.uwaterloo.flix.Main$.main(Main.scala:137)
        at ca.uwaterloo.flix.Main.main(Main.scala)
```

**Comment by magnus-madsen** [comment]
Thanks for the bug report. There is an issue with type inference.

Meanwhile this is a work around:

```
def propTypes(): System = #{
	Type(l1,v; t: L_String) :- FlowLink(l1,l2), Type(l2,v; t). // Note the type annotation on the lattice part.
}
```

sorry for the inconvenience.

Let us know if you have more issues or questions.

**Comment by CasperDN** [comment]
The following is executable (well `main` is, `propType` does not have a `ToString`). Note that I've added `Blattice.` everywhere and removed the `with X[A]` for the functions when appropriate. Finally the instance of `Boxable` has been removed. 

```
/// BLattice[a]: the type a plus bot and top
enum BLattice[a] {
	case Val(a),
	case Bot,
	case Top
}

type alias L_String = BLattice[String]

def toBLattice(x : a): BLattice[a] = BLattice.Val(x)

instance ToString[BLattice[a]] with ToString[a] {
	pub def toString( c:BLattice[a] ): String = match c {
		case BLattice.Bot		=> "Bot"
		case BLattice.Top		=> "Top"
		case BLattice.Val(v)	=> ToString.toString(v)
		}
}

instance Eq[BLattice[a]] with Eq[a] {
	pub def eq(x : BLattice[a], y:BLattice[a]):Bool =
		match (x,y) {
			case (BLattice.Bot,BLattice.Bot)       => true
			case (BLattice.Top,BLattice.Top)       => true
			case (BLattice.Val(a),BLattice.Val(b)) => Eq.eq(a,b)
			case _               => false
	}
}

instance Order[BLattice[a]] with Order[a] {
	pub def compare(x : BLattice[a], y:BLattice[a]):Comparison =
		match (x,y) {
			case (BLattice.Bot,BLattice.Bot) => Comparison.EqualTo
			case (BLattice.Top,BLattice.Top) => Comparison.EqualTo
			case (BLattice.Bot,_)   => Comparison.LessThan
			case (BLattice.Top,_)   => Comparison.GreaterThan
			case (_,BLattice.Top)   => Comparison.LessThan
			case (_,BLattice.Bot)   => Comparison.GreaterThan
			case (BLattice.Val(a),BLattice.Val(b)) => Order.compare(a,b)
	}
}

instance LowerBound[BLattice[a]] {
	pub def minValue(): BLattice[a] = BLattice.Bot
}

instance PartialOrder[BLattice[a]] with Eq[a] {
	pub def lessEqual(x : BLattice[a], y:BLattice[a]):Bool =
		match (x,y) {
		case (BLattice.Bot,_) => true
		case (_,BLattice.Top) => true
		case (BLattice.Val(a),BLattice.Val(b)) => Eq.eq(a,b)
		case _ => false
		}
}

instance JoinLattice[BLattice[a]] with Eq[a] {
	pub def leastUpperBound(x : BLattice[a], y:BLattice[a]):BLattice[a] =
		match (x,y) {
		case (BLattice.Bot,_) => y
		case (_,BLattice.Bot) => x
		case (BLattice.Val(a),BLattice.Val(b)) => if (Eq.eq(a,b)) x else BLattice.Top
		case _ => BLattice.Top
		}
}

instance MeetLattice[BLattice[a]] with Eq[a] {
	pub def greatestLowerBound(x : BLattice[a], y:BLattice[a]):BLattice[a] =
		match (x,y) {
		case (BLattice.Top,_) => y
		case (_,BLattice.Top) => x
		case (BLattice.Val(a),BLattice.Val(b)) => if (Eq.eq(a,b)) x else BLattice.Bot
		case _ => BLattice.Bot
	}
}

/// Real part f the code

type alias System = #{
		Type(Int32, String; L_String),
		FlowLink(Int32,Int32)
	}

def propTypes(): System = #{
	Type(l1,v; t) :- FlowLink(l1,l2), Type(l2,v; t).
}

def main(): Unit \ IO =
	let _pt = solve propTypes();
	println(0)
```

**Comment by magnus-madsen** [comment]
Fixed. Thanks to @CasperDN

**Comment by magnus-madsen** [comment]
This was a long-standing and tricky issue.
