### ISSUE TITLE
Several VSCode features broken on master

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#5183]
- Semantic highlight
- Code lenses
- Hovering

Strangely, VSCode hovering reports "information may not be current" for a correct program.

Bug seems to have been introduced between Dec 18 and Dec 19.

**Comment by magnus-madsen** [comment]
```
ca.uwaterloo.flix.util.InternalCompilerException: Unexpected non-arrow type: 'Region[b33907]'.
	at ca.uwaterloo.flix.language.ast.Type.arrowPurityType(Type.scala:177)
	at ca.uwaterloo.flix.language.ast.Type.arrowPurityType$(Type.scala:175)
	at ca.uwaterloo.flix.language.ast.Type$Apply.arrowPurityType(Type.scala:417)
	at ca.uwaterloo.flix.language.phase.extra.CodeHinter$.isPureFunction(CodeHinter.scala:477)
	at ca.uwaterloo.flix.language.phase.extra.CodeHinter$.checkPurity(CodeHinter.scala:350)
	at ca.uwaterloo.flix.language.phase.extra.CodeHinter$.visitExp(CodeHinter.scala:108)
	at ca.uwaterloo.flix.language.phase.extra.CodeHinter$.visitDef(CodeHinter.scala:74)
	at ca.uwaterloo.flix.language.phase.extra.CodeHinter$.$anonfun$run$2(CodeHinter.scala:33)
```
