### ISSUE TITLE
ArrayIndexOutOfBoundsException in IndexedRelation

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#537]
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
        at ca.uwaterloo.flix.runtime.datastore.IndexedRelation.matchRow(IndexedRelation.scala:202)
        at ca.uwaterloo.flix.runtime.datastore.IndexedRelation.$anonfun$lookup$2(IndexedRelation.scala:181)
        at ca.uwaterloo.flix.runtime.datastore.IndexedRelation.$anonfun$lookup$2$adapted(IndexedRelation.scala:180)
        at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:502)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
        at ca.uwaterloo.flix.runtime.Solver.evalCross(Solver.scala:404)
        at ca.uwaterloo.flix.runtime.Solver.ca$uwaterloo$flix$runtime$Solver$$evalBody(Solver.scala:357)
        at ca.uwaterloo.flix.runtime.Solver$Batch.call(Solver.scala:658)
        at ca.uwaterloo.flix.runtime.Solver$Batch.call(Solver.scala:652)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by magnus-madsen** [comment]
This happens with `SUOpt.flix`

**Comment by magnus-madsen** [comment]
Believed fixed.
