### ISSUE TITLE
InternalCompilerException: Unexpected pattern in lowering phase

### ISSUE THREAD

**Issue by sfendrich** [flix/flix#5371]
# Actual behavior

The following program causes the compiler to crash with `InternalCompilerException: Unexpected pattern` during lowering:

```
def shortestPaths(graph: Set[(t,Int32,t)], origin: t): List[(List[t], Down[Int32])] with Boxable[t] =
    let db = inject graph into Edge;
    let pr = #{
        Path(origin::Nil; Down(0)).
        Path(y::x::path; add(dox, Down(dxy))) :- 
            Path(x::path; dox), 
            Edge(x, dxy, y).
    };
    query db, pr select (route, d) from Path(route; d)

def add(x: Down[Int32], y: Down[Int32]): Down[Int32] =
    let Down(n1) = x;
    let Down(n2) = y;
    Down(n1 + n2)

def main(): Unit \ IO =
   let graph = Set#{
        ("A", 200, "B")};
    List.forEach(println, shortestPaths(graph, "A"))
```

# Expected behavior

Either (a) reject the program with a proper error message 
or (b) compile to a working program.

# Crash Report

```
# An unexpected error has been detected by the Flix compiler:
#
#   Unexpected pattern: 'Cons((x, path))'.
#
# This is a bug in the Flix compiler. Please report it here:
#
# https://github.com/flix/flix/issues
#
# -- Flix Compiler --
#
# Flix Version : v0.34.0
#   incremental: All
#
# -- Java Virtual Machine --
#
# JVM Version  : 11.0.17 (2022-10-18)
# JVM Vendor   : Ubuntu
# JAVA_HOME    : /usr/lib/jvm/java-11-openjdk-amd64
# System       : Linux (5.15.0-58-generic)
#
# -- Stack Trace --
ca.uwaterloo.flix.util.InternalCompilerException: Unexpected pattern: 'Cons((x, path))'.
    at ca.uwaterloo.flix.language.phase.Lowering$.visitBodyTerm(Lowering.scala:1058)
    at ca.uwaterloo.flix.language.phase.Lowering$.$anonfun$visitBodyPred$2(Lowering.scala:988)
    at scala.collection.immutable.List.map(List.scala:246)
    at ca.uwaterloo.flix.language.phase.Lowering$.visitBodyPred(Lowering.scala:988)
    at ca.uwaterloo.flix.language.phase.Lowering$.$anonfun$visitConstraint$1(Lowering.scala:962)
    at scala.collection.immutable.List.map(List.scala:246)
    at ca.uwaterloo.flix.language.phase.Lowering$.visitConstraint(Lowering.scala:962)
    at ca.uwaterloo.flix.language.phase.Lowering$.$anonfun$mkDatalog$4(Lowering.scala:947)
    at scala.collection.immutable.List.map(List.scala:246)
    at ca.uwaterloo.flix.language.phase.Lowering$.mkDatalog(Lowering.scala:947)
    at ca.uwaterloo.flix.language.phase.Lowering$.visitExp(Lowering.scala:699)
    at ca.uwaterloo.flix.language.phase.Lowering$.visitExp(Lowering.scala:368)
    at ca.uwaterloo.flix.language.phase.Lowering$.visitExp(Lowering.scala:369)
    at ca.uwaterloo.flix.language.phase.Lowering$.visitImpl(Lowering.scala:292)
    at ca.uwaterloo.flix.language.phase.Lowering$.visitDef(Lowering.scala:181)
    at ca.uwaterloo.flix.language.phase.Lowering$.$anonfun$run$2(Lowering.scala:154)
    at scala.collection.parallel.mutable.ParArray$Map.leaf(ParArray.scala:664)
    at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:52)
    at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
    at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:97)
    at scala.collection.parallel.Task.tryLeaf(Tasks.scala:55)
    at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:49)
    at scala.collection.parallel.mutable.ParArray$Map.tryLeaf(ParArray.scala:655)
    at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:169)
    at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:156)
    at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:303)
    at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:149)
    at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:148)
    at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:303)
    at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by magnus-madsen** [comment]
@sfendrich Thanks for the bug report. A few things:

- Can you try with the latest nightly: https://flix.dev/nightly/ ? Just download the jar, call it `flix.jar`, and place it into the root folder of the VSCode project.
- I believe the newest nightly should rejected the above program with an error message. This is because Flix does not (yet) support pattern matches in rules. If that is important, we could potentially look into it.
- I am not sure if the above program is safe, i.e. I would worry that if the graph has cycles you could build an infinite list.


That said, I tried a hacked version of your program:


```
def shortestPaths(graph: Set[(t,Int32,t)], origin: t): List[(List[t], Down[Int32])] with Boxable[t] =
    let db = inject graph into Edge;
    let pr = #{
        Path(origin::Nil; Down(0)).
        Path(concat(y, path); add(dox, Down(dxy))) :- 
            Path(path; dox), 
            Edge(x, dxy, y),
            if List.head(path) == Some(x).
    };
    query db, pr select (route, d) from Path(route; d)

def concat(y: t, l: List[t]): List[t] = match l {
    case Nil     => y :: Nil
    case x :: xs => y :: x :: xs
}

def add(x: Down[Int32], y: Down[Int32]): Down[Int32] =
    let Down(n1) = x;
    let Down(n2) = y;
    Down(n1 + n2)

def main(): Unit \ IO =
   let graph = Set#{
        ("A", 200, "B")};
    List.forEach(println, shortestPaths(graph, "A"))
```

Not sure if it computes what you want.

**Comment by sfendrich** [comment]
Thanks for the quick response and for improving the code!

* I can confirm that current nightly rejects the program with a proper error message.
* I also found a way to circumvent the pattern match in the rules and can share my solution if it is of interest

**Comment by magnus-madsen** [comment]
> Thanks for the quick response and for improving the code!
> 
> * I can confirm that current nightly rejects the program with a proper error message.
> * I also found a way to circumvent the pattern match in the rules and can share my solution if it is of interest

If the solution is different, I would like to see it :)

**Comment by sfendrich** [comment]
Your solution is much simpler, thank you!
