### ISSUE TITLE
`InternalCompilerException: Unexpected type` when changing List to Vector in RamStmt

### ISSUE THREAD

**Issue by dignissimus** [flix/flix#5733]
# Reproduction steps
Apply the following diff to master (https://github.com/flix/flix/commit/f3705d18fe350864b8f6e5c9e61df9aa9b1d306f)
```diff
diff --git a/main/src/library/Fixpoint/Ram/RamStmt.flix b/main/src/library/Fixpoint/Ram/RamStmt.flix
index ec656d1ca..4a1ac2bd2 100644
--- a/main/src/library/Fixpoint/Ram/RamStmt.flix
+++ b/main/src/library/Fixpoint/Ram/RamStmt.flix
@@ -24,8 +24,8 @@ namespace Fixpoint/Ram {
         case Merge(RamSym[v], RamSym[v])
         case Assign(RamSym[v], RamSym[v])
         case Purge(RamSym[v])
-        case Seq(List[RamStmt[v]])
-        case Until(List[BoolExp[v]], RamStmt[v])
+        case Seq(Vector[RamStmt[v]])
+        case Until(Vector[BoolExp[v]], RamStmt[v])
         case Comment(String)
     }
 
@@ -37,9 +37,9 @@ namespace Fixpoint/Ram {
                 case RamStmt.Merge(src, dst) => "merge ${src} into ${dst}"
                 case RamStmt.Assign(lhs, rhs) => "${lhs} := ${rhs}"
                 case RamStmt.Purge(ramSym) => "purge ${ramSym}"
-                case RamStmt.Seq(xs) => List.join(";${nl}", xs)
+                case RamStmt.Seq(xs) => Vector.join(";${nl}", xs)
                 case RamStmt.Until(test, body) =>
-                    let tst = test |> List.join(" Λ ");
+                    let tst = test |> Vector.join(" Λ ");
                     "until(${tst}) do${nl}${String.indent(4, "${body}")}end"
                 case RamStmt.Comment(comment) => "// ${comment}"
             }

```

# Result
```java
here:
#
# https://github.com/flix/flix/issues
#
# -- Flix Compiler --
#
# Flix Version : 0.34.0
#   incremental: All
#
# -- Java Virtual Machine --
#
# JVM Version  : 19.0.2 (2023-01-17)
# JVM Vendor   : N/A
# JAVA_HOME    : /usr/lib/jvm/java-19-openjdk
# System       : Linux (6.2.7-arch1-1)
#
# -- Stack Trace --
ca.uwaterloo.flix.util.InternalCompilerException: Unexpected type: 'Vector[RamStmt[t30720]]'.
	at ca.uwaterloo.flix.language.phase.PatternExhaustiveness$.countTypeArgs(PatternExhaustiveness.scala:613)
	at ca.uwaterloo.flix.language.phase.PatternExhaustiveness$.$anonfun$missingFromSig$1(PatternExhaustiveness.scala:534)
	at scala.collection.StrictOptimizedIterableOps.map(StrictOptimizedIterableOps.scala:99)
	at scala.collection.StrictOptimizedIterableOps.map$(StrictOptimizedIterableOps.scala:86)
	at scala.collection.immutable.HashMap.map(HashMap.scala:39)
	at ca.uwaterloo.flix.language.phase.PatternExhaustiveness$.getAllCtors$1(PatternExhaustiveness.scala:534)
	at ca.uwaterloo.flix.language.phase.PatternExhaustiveness$.$anonfun$missingFromSig$2(PatternExhaustiveness.scala:545)
	at scala.collection.immutable.List.foldRight(List.scala:352)
	at ca.uwaterloo.flix.language.phase.PatternExhaustiveness$.missingFromSig(PatternExhaustiveness.scala:545)
	at ca.uwaterloo.flix.language.phase.PatternExhaustiveness$.findNonMatchingPat(PatternExhaustiveness.scala:321)
	at ca.uwaterloo.flix.language.phase.PatternExhaustiveness$.checkRules(PatternExhaustiveness.scala:297)
	at ca.uwaterloo.flix.language.phase.PatternExhaustiveness$.visitExp(PatternExhaustiveness.scala:163)
	at ca.uwaterloo.flix.language.phase.PatternExhaustiveness$.$anonfun$visitExp$3(PatternExhaustiveness.scala:150)
	at scala.collection.immutable.List.flatMap(List.scala:293)
	at ca.uwaterloo.flix.language.phase.PatternExhaustiveness$.visitExp(PatternExhaustiveness.scala:150)
	at ca.uwaterloo.flix.language.phase.PatternExhaustiveness$.visitImpl(PatternExhaustiveness.scala:126)
	at ca.uwaterloo.flix.language.phase.PatternExhaustiveness$.$anonfun$run$3(PatternExhaustiveness.scala:109)
	at scala.collection.immutable.List.flatMap(List.scala:293)
	at scala.collection.immutable.List.flatMap(List.scala:79)
	at ca.uwaterloo.flix.language.phase.PatternExhaustiveness$.$anonfun$run$1(PatternExhaustiveness.scala:109)
	at ca.uwaterloo.flix.api.Flix.phase(Flix.scala:589)
	at ca.uwaterloo.flix.language.phase.PatternExhaustiveness$.run(PatternExhaustiveness.scala:107)
	at ca.uwaterloo.flix.api.Flix.$anonfun$check$13(Flix.scala:491)
	at ca.uwaterloo.flix.util.Validation$Implicit$AsMonad.flatMap(Validation.scala:93)
	at ca.uwaterloo.flix.api.Flix.$anonfun$check$12(Flix.scala:490)
	at ca.uwaterloo.flix.util.Validation$Implicit$AsMonad.flatMap(Validation.scala:99)
	at ca.uwaterloo.flix.api.Flix.$anonfun$check$11(Flix.scala:489)
	at ca.uwaterloo.flix.util.Validation$Implicit$AsMonad.flatMap(Validation.scala:93)
	at ca.uwaterloo.flix.api.Flix.$anonfun$check$10(Flix.scala:488)
```

**Comment by magnus-madsen** [comment]
I think I have a fix in #5734
