### ISSUE TITLE
Crash from local `use`

### ISSUE THREAD

**Issue by AStenbaek** [flix/flix#6119]
Local use of `use` throws a JVM exception.

The following program crashes:
```scala
def freeVars(e: Exp): Set[Var] = {
    use Exp;
    match e {
        case ConstExp(_) => Set.empty()
        case _ => Set.empty()
    }
}

def main(): Unit \ IO = 
    println("Hello World!")
```
producing the error message:
```
head of empty listjava.util.NoSuchElementException: head of empty list
        at scala.collection.immutable.Nil$.head(List.scala:629)
        at scala.collection.immutable.Nil$.head(List.scala:628)
        at ca.uwaterloo.flix.language.phase.Resolver$.tryLookupQualifiedName(Resolver.scala:2710)
        at ca.uwaterloo.flix.language.phase.Resolver$.ca$uwaterloo$flix$language$phase$Resolver$$lookupQualifiedName(Resolver.scala:2756)
        at ca.uwaterloo.flix.language.phase.Resolver$Expressions$.visitExp$1(Resolver.scala:992)
        at ca.uwaterloo.flix.language.phase.Resolver$Expressions$.resolve(Resolver.scala:1678)
        at ca.uwaterloo.flix.language.phase.Resolver$.$anonfun$resolveDef$1(Resolver.scala:506)
        at ca.uwaterloo.flix.util.Validation$.flatMapN(Validation.scala:462)
        at ca.uwaterloo.flix.language.phase.Resolver$.resolveDef(Resolver.scala:503)
        at ca.uwaterloo.flix.language.phase.Resolver$.visitDecl(Resolver.scala:353)
        at ca.uwaterloo.flix.language.phase.Resolver$.$anonfun$visitUnit$3(Resolver.scala:323)
        at ca.uwaterloo.flix.util.Validation$.$anonfun$fastTraverse$1(Validation.scala:223)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at ca.uwaterloo.flix.util.Validation$.fastTraverse(Validation.scala:222)
        at ca.uwaterloo.flix.util.Validation$.traverse(Validation.scala:176)
        at ca.uwaterloo.flix.language.phase.Resolver$.$anonfun$visitUnit$2(Resolver.scala:323)
        at ca.uwaterloo.flix.util.Validation$.flatMapN(Validation.scala:462)
        at ca.uwaterloo.flix.language.phase.Resolver$.visitUnit(Resolver.scala:320)
        at ca.uwaterloo.flix.language.phase.Resolver$.$anonfun$run$9(Resolver.scala:99)
        at ca.uwaterloo.flix.util.Validation$.$anonfun$fastTraverse$1(Validation.scala:223)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
        at ca.uwaterloo.flix.util.Validation$.fastTraverse(Validation.scala:222)
        at ca.uwaterloo.flix.util.Validation$.traverse(Validation.scala:176)
        at ca.uwaterloo.flix.language.phase.Resolver$.$anonfun$run$8(Resolver.scala:99)
        at ca.uwaterloo.flix.util.Validation$.$anonfun$curry$2(Validation.scala:300)
        at ca.uwaterloo.flix.util.Validation$.ap(Validation.scala:275)
        at ca.uwaterloo.flix.util.Validation$.flatMapN(Validation.scala:476)
        at ca.uwaterloo.flix.language.phase.Resolver$.$anonfun$run$1(Resolver.scala:96)
        at ca.uwaterloo.flix.api.Flix.phase(Flix.scala:643)
        at ca.uwaterloo.flix.language.phase.Resolver$.run(Resolver.scala:78)
        at ca.uwaterloo.flix.api.Flix.$anonfun$check$4(Flix.scala:531)
        at ca.uwaterloo.flix.util.Validation$Implicit$AsMonad.flatMap(Validation.scala:93)
        at ca.uwaterloo.flix.api.Flix.$anonfun$check$3(Flix.scala:530)
        at ca.uwaterloo.flix.util.Validation$Implicit$AsMonad.flatMap(Validation.scala:93)
        at ca.uwaterloo.flix.api.Flix.$anonfun$check$2(Flix.scala:529)
        at ca.uwaterloo.flix.util.Validation$Implicit$AsMonad.flatMap(Validation.scala:93)
        at ca.uwaterloo.flix.api.Flix.$anonfun$check$1(Flix.scala:528)
        at ca.uwaterloo.flix.util.Validation$Implicit$AsMonad.flatMap(Validation.scala:93)
        at ca.uwaterloo.flix.api.Flix.check(Flix.scala:527)
        at ca.uwaterloo.flix.runtime.shell.Shell.compile(Shell.scala:345)
        at ca.uwaterloo.flix.runtime.shell.Shell.execReload(Shell.scala:183)
        at ca.uwaterloo.flix.runtime.shell.Shell.execReloadAndEval(Shell.scala:317)
        at ca.uwaterloo.flix.runtime.shell.Shell.execute(Shell.scala:162)
        at ca.uwaterloo.flix.runtime.shell.Shell.loop(Shell.scala:113)
        at ca.uwaterloo.flix.Main$.main(Main.scala:247)
        at ca.uwaterloo.flix.Main.main(Main.scala)
flix> :eval main()
head of empty listjava.util.NoSuchElementException: head of empty list
        at scala.collection.immutable.Nil$.head(List.scala:629)
        at scala.collection.immutable.Nil$.head(List.scala:628)
        at ca.uwaterloo.flix.language.phase.Resolver$.tryLookupQualifiedName(Resolver.scala:2710)
        at ca.uwaterloo.flix.language.phase.Resolver$.ca$uwaterloo$flix$language$phase$Resolver$$lookupQualifiedName(Resolver.scala:2756)
        at ca.uwaterloo.flix.language.phase.Resolver$Expressions$.visitExp$1(Resolver.scala:992)
        at ca.uwaterloo.flix.language.phase.Resolver$Expressions$.resolve(Resolver.scala:1678)
        at ca.uwaterloo.flix.language.phase.Resolver$.$anonfun$resolveDef$1(Resolver.scala:506)
        at ca.uwaterloo.flix.util.Validation$.flatMapN(Validation.scala:462)
        at ca.uwaterloo.flix.language.phase.Resolver$.resolveDef(Resolver.scala:503)
        at ca.uwaterloo.flix.language.phase.Resolver$.visitDecl(Resolver.scala:353)
        at ca.uwaterloo.flix.language.phase.Resolver$.$anonfun$visitUnit$3(Resolver.scala:323)
        at ca.uwaterloo.flix.util.Validation$.$anonfun$fastTraverse$1(Validation.scala:223)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at ca.uwaterloo.flix.util.Validation$.fastTraverse(Validation.scala:222)
        at ca.uwaterloo.flix.util.Validation$.traverse(Validation.scala:176)
        at ca.uwaterloo.flix.language.phase.Resolver$.$anonfun$visitUnit$2(Resolver.scala:323)
        at ca.uwaterloo.flix.util.Validation$.flatMapN(Validation.scala:462)
        at ca.uwaterloo.flix.language.phase.Resolver$.visitUnit(Resolver.scala:320)
        at ca.uwaterloo.flix.language.phase.Resolver$.$anonfun$run$9(Resolver.scala:99)
        at ca.uwaterloo.flix.util.Validation$.$anonfun$fastTraverse$1(Validation.scala:223)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
        at ca.uwaterloo.flix.util.Validation$.fastTraverse(Validation.scala:222)
        at ca.uwaterloo.flix.util.Validation$.traverse(Validation.scala:176)
        at ca.uwaterloo.flix.language.phase.Resolver$.$anonfun$run$8(Resolver.scala:99)
        at ca.uwaterloo.flix.util.Validation$.$anonfun$curry$2(Validation.scala:300)
        at ca.uwaterloo.flix.util.Validation$.ap(Validation.scala:275)
        at ca.uwaterloo.flix.util.Validation$.flatMapN(Validation.scala:476)
        at ca.uwaterloo.flix.language.phase.Resolver$.$anonfun$run$1(Resolver.scala:96)
        at ca.uwaterloo.flix.api.Flix.phase(Flix.scala:643)
        at ca.uwaterloo.flix.language.phase.Resolver$.run(Resolver.scala:78)
        at ca.uwaterloo.flix.api.Flix.$anonfun$check$4(Flix.scala:531)
        at ca.uwaterloo.flix.util.Validation$Implicit$AsMonad.flatMap(Validation.scala:93)
        at ca.uwaterloo.flix.api.Flix.$anonfun$check$3(Flix.scala:530)
        at ca.uwaterloo.flix.util.Validation$Implicit$AsMonad.flatMap(Validation.scala:93)
        at ca.uwaterloo.flix.api.Flix.$anonfun$check$2(Flix.scala:529)
        at ca.uwaterloo.flix.util.Validation$Implicit$AsMonad.flatMap(Validation.scala:93)
        at ca.uwaterloo.flix.api.Flix.$anonfun$check$1(Flix.scala:528)
        at ca.uwaterloo.flix.util.Validation$Implicit$AsMonad.flatMap(Validation.scala:93)
        at ca.uwaterloo.flix.api.Flix.check(Flix.scala:527)
        at ca.uwaterloo.flix.runtime.shell.Shell.compile(Shell.scala:345)
        at ca.uwaterloo.flix.runtime.shell.Shell.execReload(Shell.scala:183)
        at ca.uwaterloo.flix.runtime.shell.Shell.execReloadAndEval(Shell.scala:317)
        at ca.uwaterloo.flix.runtime.shell.Shell.execute(Shell.scala:162)
        at ca.uwaterloo.flix.runtime.shell.Shell.loop(Shell.scala:113)
        at ca.uwaterloo.flix.Main$.main(Main.scala:247)
        at ca.uwaterloo.flix.Main.main(Main.scala)
```

**Comment by mlutze** [comment]
Appears fixed.
