### ISSUE TITLE
java.lang.StackOverflowError on large functions

### ISSUE THREAD

**Issue by christianhujer** [flix/flix#6229]
When creating a large function, the compiler throws `StackOverflowError`.

Generate example code:
```bash
#!/bin/bash
echo 'def main(): Unit \ Impure ='
for ((i = 1; i < 1000; i++)) ; do
    echo '    println("Hello, world!");'
done
echo '    println("Hello, world!")
```
Run this and save its output to `src/Main.flix`, then compile with `java -jar flix.jar build`.

Expected behavior: This code compiles (just like it would in most other languages).
Actual behavior: Compiling this code throws `StackOverflowError`

Workaround: Increase the stack size, for example: `java -Xss8M -jar ~/soft/flix-0.38.0.jar build`

I've observed that the maximum complexity that Flix can compile in a single function with the standard JVM stack size seems to be ~150 elements.

Real-world impact: Probably very low for human-written code, probably medium for auto-generated code.

Note: This was discovered during a systematic scientific comparison of programming languages.

Stack trace:
```
Exception in thread "main" java.lang.StackOverflowError
        at ca.uwaterloo.flix.language.phase.Weeder$.visitExp(Weeder.scala:577)
        at ca.uwaterloo.flix.language.phase.Weeder$.visitExp(Weeder.scala:787)
        at ca.uwaterloo.flix.language.phase.Weeder$.visitExp(Weeder.scala:857)
        at ca.uwaterloo.flix.language.phase.Weeder$.visitExp(Weeder.scala:857) (many times)
        at ca.uwaterloo.flix.language.phase.Weeder$.visitDef(Weeder.scala:247)
        at ca.uwaterloo.flix.language.phase.Weeder$.visitTopDef(Weeder.scala:225)
        at ca.uwaterloo.flix.language.phase.Weeder$.visitDecl(Weeder.scala:134)
        at ca.uwaterloo.flix.language.phase.Weeder$.$anonfun$visitCompilationUnit$2(Weeder.scala:83)
        at ca.uwaterloo.flix.util.Validation$.$anonfun$fastTraverse$1(Validation.scala:223)
        at scala.collection.immutable.Vector.foreach(Vector.scala:2122)
        at ca.uwaterloo.flix.util.Validation$.fastTraverse(Validation.scala:222)
        at ca.uwaterloo.flix.util.Validation$.traverse(Validation.scala:176)
        at ca.uwaterloo.flix.language.phase.Weeder$.visitCompilationUnit(Weeder.scala:83)
        at ca.uwaterloo.flix.language.phase.Weeder$.$anonfun$run$2(Weeder.scala:68)
        at scala.collection.parallel.mutable.ParArray$Map.leaf(ParArray.scala:664)
        at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:52)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:97)
        at scala.collection.parallel.Task.tryLeaf(Tasks.scala:55)
        at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:49)
        at scala.collection.parallel.mutable.ParArray$Map.tryLeaf(ParArray.scala:655)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:169)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:156)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:303)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:149)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:148)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:303)
        at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool.helpJoin(ForkJoinPool.java:2074)
        at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:423)
        at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:651)
        at scala.collection.parallel.ForkJoinTasks$WrappedTask.sync(Tasks.scala:242)
        at scala.collection.parallel.ForkJoinTasks$WrappedTask.sync$(Tasks.scala:242)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.sync(Tasks.scala:303)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:173)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:156)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:303)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:149)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:148)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:303)
        at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1311)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1841)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1806)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by JonathanStarup** [comment]
reconfirmed to still happen - although not it is in Desugar, not Weeder.

@magnus-madsen should we add a huge def like this as a test?

**Comment by magnus-madsen** [comment]
I don't even know how we can fix it...

**Comment by CasperDN** [comment]
I believe we can remove parsing. Even with 6000 repeats this only fails in the last phase when the method is too big for `MethodWriter`. It can also now handle at least 500 repeats on my machine (maybe the Flix byte code has gotten simpler?).

**Comment by CasperDN** [comment]
Are we sure this should be completely closed? My comment was mostly about the label used. The program works for `800` repetitions, but for `850` the generated java method is still too large to be legal.

**Comment by magnus-madsen** [comment]
> Are we sure this should be completely closed? My comment was mostly about the label used. The program works for `800` repetitions, but for `850` the generated java method is still too large to be legal.

Hard for us to do anything about that... Other than to introduce some approximate limits earlier in the compiler?

The same holds for any number of things: max local variables, max fields, max constant pool, etc. etc.
