### ISSUE TITLE
Maven dependencies problems

### ISSUE THREAD

**Issue by mobilemindtec** [flix/flix#6272]
Hello!

I'm trying build anything using Flix to see how work. I liked very much of language. I'm trying add some maven dependencies on my tom file, but something is not right.

1 - Apparently I can't use a dependency whose version has anything other than numbers.

```
[mvn-dependencies]
"org.junit.jupiter:junit-jupiter-api" = "5.9.2"
"io.netty:netty-all" = "5.0.0.Alpha2"
```

```
 This toml file has a version number which includes things that are not numbers: 5.0.0.Alpha2.
 For input string: "Alpha2"
 The toml file was found at /mnt/data/sources/flix/app/flix.toml.
```

2 - There seems to be something wrong with resolving maven dependencies

```
[mvn-dependencies]
"org.junit.jupiter:junit-jupiter-api" = "5.9.2"
"com.linecorp.armeria:armeria" = "1.24.2"
"ch.qos.logback:logback-classic" = "1.4.7"
"org.slf4j:log4j-over-slf4j" = "1.7.36"
```
```
Dependency resolution completed.                                                                                                                     
java.lang.IllegalArgumentException: '/mnt/data/sources/flix/app/lib/cache/https/repo1.maven.org/maven2/io/netty/netty-transport-native-epoll/4.1.94.Final/netty-transport-native-epoll-4.1.94.Final.jar' must be a file.                                                                                  
        at ca.uwaterloo.flix.api.Flix.addJar(Flix.scala:429)                                                                                         
        at ca.uwaterloo.flix.api.Bootstrap.$anonfun$reconfigureFlix$6(Bootstrap.scala:438)                                                           
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:576)                                                                          
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:574)                                                                         
        at scala.collection.AbstractIterable.foreach(Iterable.scala:933)                                                                             
        at scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:903)                                                                       
        at ca.uwaterloo.flix.api.Bootstrap.reconfigureFlix(Bootstrap.scala:437)                                                                      
        at ca.uwaterloo.flix.api.Bootstrap.build(Bootstrap.scala:491)                                                                                
        at ca.uwaterloo.flix.api.Bootstrap.run(Bootstrap.scala:597)                                                                                  
        at ca.uwaterloo.flix.Main$.$anonfun$main$17(Main.scala:206)                                                                                  
        at ca.uwaterloo.flix.util.Validation$.flatMapN(Validation.scala:462)
        at ca.uwaterloo.flix.Main$.main(Main.scala:201)
        at ca.uwaterloo.flix.Main.main(Main.scala)

```

The dependency `netty-transport-native-epoll-4.1.94.Final.jar` was downloaded on  `.m2` folder, but not was copy to `cache` folder. If I manually copy the file, I get the following error:

```
java.lang.IllegalArgumentException: '/mnt/data/sources/flix/app/lib/cache/https/repo1.maven.org/maven2/com/aayushatharva/brotli4j/native-linux-x86/64/1.12.0/64-1.12.0.jar' must be a file.
        at ca.uwaterloo.flix.api.Flix.addJar(Flix.scala:429)
        at ca.uwaterloo.flix.api.Bootstrap.$anonfun$reconfigureFlix$6(Bootstrap.scala:438)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:576)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:574)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:933)
        at scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:903)
        at ca.uwaterloo.flix.api.Bootstrap.reconfigureFlix(Bootstrap.scala:437)
        at ca.uwaterloo.flix.api.Bootstrap.build(Bootstrap.scala:491)
        at ca.uwaterloo.flix.api.Bootstrap.run(Bootstrap.scala:597)
        at ca.uwaterloo.flix.Main$.$anonfun$main$17(Main.scala:206)
        at ca.uwaterloo.flix.util.Validation$.flatMapN(Validation.scala:462)
        at ca.uwaterloo.flix.Main$.main(Main.scala:201)
        at ca.uwaterloo.flix.Main.main(Main.scala)

```

This lib `64-1.12.0.jar` isn't a valid dependency. I couldn't find it in the maven repositories.

If you can help me I would appreciate it. Keep up the amazing work!

**Comment by magnus-madsen** [comment]
>  Apparently I can't use a dependency whose version has anything other than numbers.

This has been fixed in the latest master (but not released yet). You could try a nightly: https://flix.dev/nightly/

**Comment by magnus-madsen** [comment]
As for the second problem, what OS, JVM version, etc are you using?

**Comment by mobilemindtec** [comment]
Java

```
ava version "20.0.1" 2023-04-18
Java(TM) SE Runtime Environment (build 20.0.1+9-29)
Java HotSpot(TM) 64-Bit Server VM (build 20.0.1+9-29, mixed mode, sharing)

```

O.S

```
Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2023.2
Codename:       kali-rolling
```

CPU

```
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         43 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  8
  On-line CPU(s) list:   0-7
Vendor ID:               AuthenticAMD
  BIOS Vendor ID:        Advanced Micro Devices, Inc.
  Model name:            AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx
    BIOS Model name:     AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx   Unknown CPU @ 2.3GHz
    BIOS CPU family:     107
    CPU family:          23
    Model:               24
    Thread(s) per core:  2
    Core(s) per socket:  4
    Socket(s):           1
    Stepping:            1
    Frequency boost:     enabled
    CPU(s) scaling MHz:  88%
    CPU max MHz:         2300.0000
    CPU min MHz:         1400.0000
    BogoMIPS:            4591.23
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_
                         opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 f
                         ma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse
                          3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate ssbd ibpb vmmcall 
                         fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 clzero irperf xsaveerptr arat npt lbr
                         v svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overfl
                         ow_recov succor smca sev sev_es
Virtualization features: 
  Virtualization:        AMD-V
Caches (sum of all):     
  L1d:                   128 KiB (4 instances)
  L1i:                   256 KiB (4 instances)
  L2:                    2 MiB (4 instances)
  L3:                    4 MiB (1 instance)
NUMA:                    
  NUMA node(s):          1
  NUMA node0 CPU(s):     0-7
Vulnerabilities:         
  Itlb multihit:         Not affected
  L1tf:                  Not affected
  Mds:                   Not affected
  Meltdown:              Not affected
  Mmio stale data:       Not affected
  Retbleed:              Mitigation; untrained return thunk; SMT vulnerable
  Spec store bypass:     Mitigation; Speculative Store Bypass disabled via prctl
  Spectre v1:            Mitigation; usercopy/swapgs barriers and __user pointer sanitization
  Spectre v2:            Mitigation; Retpolines, IBPB conditional, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
  Srbds:                 Not affected
  Tsx async abort:       Not affected

```

**Comment by magnus-madsen** [comment]
What happens if you try with the nightly jar?

**Comment by mobilemindtec** [comment]
Flix 0.38.0 the same error

```
java.lang.IllegalArgumentException: '/mnt/data/sources/flix/app/lib/cache/https/repo1.maven.org/maven2/io/netty/netty-transport-native-epoll/4.1.94.Final/netty-transport-native-epoll-4.1.94.Final.jar' must be a file.
        at ca.uwaterloo.flix.api.Flix.addJar(Flix.scala:425)
        at ca.uwaterloo.flix.api.Bootstrap.$anonfun$reconfigureFlix$6(Bootstrap.scala:438)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:576)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:574)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:933)
        at scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:903)
        at ca.uwaterloo.flix.api.Bootstrap.reconfigureFlix(Bootstrap.scala:437)
        at ca.uwaterloo.flix.api.Bootstrap.build(Bootstrap.scala:491)
        at ca.uwaterloo.flix.api.Bootstrap.run(Bootstrap.scala:597)
        at ca.uwaterloo.flix.Main$.$anonfun$main$17(Main.scala:206)
        at ca.uwaterloo.flix.util.Validation$.flatMapN(Validation.scala:462)
        at ca.uwaterloo.flix.Main$.main(Main.scala:201)
        at ca.uwaterloo.flix.Main.main(Main.scala)
```

After copy files:

```
java.lang.IllegalArgumentException: '/mnt/data/sources/flix/app/lib/cache/https/repo1.maven.org/maven2/com/aayushatharva/brotli4j/native-linux-x86/64/1.12.0/64-1.12.0.jar' must be a file.
        at ca.uwaterloo.flix.api.Flix.addJar(Flix.scala:425)
        at ca.uwaterloo.flix.api.Bootstrap.$anonfun$reconfigureFlix$6(Bootstrap.scala:438)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:576)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:574)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:933)
        at scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:903)
        at ca.uwaterloo.flix.api.Bootstrap.reconfigureFlix(Bootstrap.scala:437)
        at ca.uwaterloo.flix.api.Bootstrap.build(Bootstrap.scala:491)
        at ca.uwaterloo.flix.api.Bootstrap.run(Bootstrap.scala:597)
        at ca.uwaterloo.flix.Main$.$anonfun$main$17(Main.scala:206)
        at ca.uwaterloo.flix.util.Validation$.flatMapN(Validation.scala:462)
        at ca.uwaterloo.flix.Main$.main(Main.scala:201)
        at ca.uwaterloo.flix.Main.main(Main.scala)
```

**Comment by magnus-madsen** [comment]
Ok. Im on vacation but can look a bit later. You can confirm the files exists and have a non zero size?

**Comment by magnus-madsen** [comment]
This is the broken part:

https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/tools/pkg/MavenPackageManager.scala#L60-L68

**Comment by magnus-madsen** [comment]
Working on a fix in https://github.com/flix/flix/pull/6276

**Comment by magnus-madsen** [comment]
@mobilemindtec Can you try the JAR in https://github.com/flix/flix/pull/6276 Thanks!

**Comment by mobilemindtec** [comment]
now it worked. then I'll play some more! Thanks

**Comment by magnus-madsen** [comment]
Reopening until the fix is merged. Thanks!
