### ISSUE TITLE
Stackoverflow in Synthesize

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#678]
```
rel Z(o: Option[List[Int]])
```

produces

```
	at scala.collection.immutable.List.map(List.scala:287)
	at ca.uwaterloo.flix.language.phase.Synthesize$.mkHashExp$1(Synthesize.scala:696)
	at ca.uwaterloo.flix.language.phase.Synthesize$.$anonfun$run$21(Synthesize.scala:605)
	at scala.collection.MapLike.getOrElse(MapLike.scala:128)
	at scala.collection.MapLike.getOrElse$(MapLike.scala:126)
	at scala.collection.AbstractMap.getOrElse(Map.scala:59)
	at ca.uwaterloo.flix.language.phase.Synthesize$.getOrMkHash$1(Synthesize.scala:582)
	at ca.uwaterloo.flix.language.phase.Synthesize$.mkApplyHash$1(Synthesize.scala:570)
	at ca.uwaterloo.flix.language.phase.Synthesize$.$anonfun$run$25(Synthesize.scala:763)
	at scala.collection.immutable.List.map(List.scala:287)
```

**Comment by magnus-madsen** [comment]
Fixed in master.
