### ISSUE TITLE
unification with boolean operator bug

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#7061]
```
def example[b: Eff, c: Eff, a: Eff -> Eff -> Eff](x: Unit -> Unit \ a[b, c], y: Unit -> Unit \ b + c) : Unit = ???
```

```
Exception in thread "ForkJoinPool-87-worker-6" ca.uwaterloo.flix.util.InternalCompilerException: Unexpected type: ''1969856[e1969848, e1969851]'.
	at ca.uwaterloo.flix.language.phase.unification.BoolAlg.fromType(BoolAlg.scala:157)
	at ca.uwaterloo.flix.language.phase.unification.BoolAlg.fromType$(BoolAlg.scala:142)
	at ca.uwaterloo.flix.language.phase.unification.BoolFormulaAlg.fromType(BoolFormulaAlg.scala:28)
	at ca.uwaterloo.flix.language.phase.unification.EffUnification$.lookupOrSolve(EffUnification.scala:162)
	at ca.uwaterloo.flix.language.phase.unification.EffUnification$.unify(EffUnification.scala:142)
	at ca.uwaterloo.flix.language.phase.unification.Unification$.unifyTypes(Unification.scala:92)
	at ca.uwaterloo.flix.language.phase.unification.Unification$.unifyStarOrArrowTypes(Unification.scala:125)
	at ca.uwaterloo.flix.language.phase.unification.Unification$.unifyTypes(Unification.scala:104)
	at ca.uwaterloo.flix.language.phase.unification.Unification$.unifyStarOrArrowTypes(Unification.scala:124)
	at ca.uwaterloo.flix.language.phase.unification.Unification$.unifyTypes(Unification.scala:104)
	at ca.uwaterloo.flix.language.phase.unification.Unification$.unifyStarOrArrowTypes(Unification.scala:124)
	at ca.uwaterloo.flix.language.phase.unification.Unification$.unifyTypes(Unification.scala:104)
	at ca.uwaterloo.flix.language.phase.unification.Unification$.unifyStarOrArrowTypes(Unification.scala:125)
	at ca.uwaterloo.flix.language.phase.unification.Unification$.unifyTypes(Unification.scala:104)
	at ca.uwaterloo.flix.language.phase.unification.Unification$.unifyStarOrArrowTypes(Unification.scala:124)
	at ca.uwaterloo.flix.language.phase.unification.Unification$.unifyTypes(Unification.scala:104)
	at ca.uwaterloo.flix.language.phase.unification.Unification$.unifyStarOrArrowTypes(Unification.scala:124)
	at ca.uwaterloo.flix.language.phase.unification.Unification$.unifyTypes(Unification.scala:104)
	at ca.uwaterloo.flix.language.ast.Scheme$.checkLessThanEqual(Scheme.scala:135)
	at ca.uwaterloo.flix.language.phase.TypeInference$.typeCheckDecl(TypeInference.scala:125)
	at ca.uwaterloo.flix.language.phase.TypeInference$.visitDefn(TypeInference.scala:47)
	at ca.uwaterloo.flix.language.phase.Typer$.visitDef(Typer.scala:160)
	at ca.uwaterloo.flix.language.phase.Typer$.$anonfun$visitDefs$2(Typer.scala:151)
	at ca.uwaterloo.flix.util.ParOps$.$anonfun$parTraverseValues$1(ParOps.scala:81)
	at ca.uwaterloo.flix.util.ParOps$.$anonfun$parMap$2(ParOps.scala:49)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

**Comment by JonathanStarup** [comment]
It is correctly kinded, but maybe `Eff -> Eff -> Eff` should be illegal

**Comment by magnus-madsen** [comment]
> It is correctly kinded, but maybe `Eff -> Eff -> Eff` should be illegal

Right. Or rather, a parameter must not have kind Eff.

**Comment by mlutze** [comment]
> > It is correctly kinded, but maybe `Eff -> Eff -> Eff` should be illegal
> 
> Right. Or rather, a parameter must not have kind Eff.

Or rather, a type parameter must not have kind `X -> ... -> Eff`

**Comment by magnus-madsen** [comment]
Exactly. Should be an easy fix?

**Comment by mlutze** [comment]
Yes, some `IllegalTypeParameterKind` in the `Kinder`

**Comment by CasperDN** [comment]
The following is executable (well main is):
```
def example
    [b: Eff, c: Eff, a: Eff -> Eff -> Eff]
    (x: Unit -> Unit \ a[b, c], y: Unit -> Unit \ b + c)
    : Unit \ b + c = y() |> ???

def main(): Unit = ()
```

As for the original it does not crash the compiler, but the errors are not nice
<details>

<summary>Type errors</summary>

```
❌ -- Type Error --------------------------------------------------

>> Unable to unify the effect formulas: 'Pure' and 'e0'.

 7 |> def example
 8 |>     [b: Eff, c: Eff, a: Eff -> Eff -> Eff]
 9 |>     (x: Unit -> Unit \ a[b, c], y: Unit -> Unit \ b + c)
10 |>     : Unit = x() |> ???

mismatched effect formulas.

Type One: Pure
Type Two: e0

❌ -- Type Error -------------------------------------------------- 

>> Expected type: 'Unit -> Unit \ e0' but found type: 'Unit -> Unit \ a[b, c]'.

10 |     : Unit = x() |> ???
                  ^^^
                  expression has unexpected type.

❌ -- Type Error -------------------------------------------------- 

>> Unable to unify the effect formulas: 'e0' and 'e0'.

10 |     : Unit = x() |> ???
                  ^^^
                  mismatched effect formulas.

Type One: e0
Type Two: e0

❌ -- Type Error -------------------------------------------------- 

>> Unable to unify the effect formulas: 'e0' and 'e0'.

10 |     : Unit = x() |> ???
                  ^^^^^^^^^^
                  mismatched effect formulas.

Type One: e0
Type Two: e0

❌ -- Type Error -------------------------------------------------- 

>> Unable to unify the effect formulas: 'e0' and 'e2 ⊕ e0 ⊕ (e0 & e2)'.

10 |     : Unit = x() |> ???
                  ^^^^^^^^^^
                  mismatched effect formulas.

Type One: e0
Type Two: e2 ⊕ e0 ⊕ (e0 & e2)
```

</details>

**Comment by magnus-madsen** [comment]
That is fine. We have a separate project to fix the errors.
