### ISSUE TITLE
Polymorphic recursion breaks monomorphization

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#7181]
```
pub def main(): Bool = f(32, 12)

pub def f(x: t, n: Int32): Bool = {
    if (n == 0) true else f(x :: Nil, n - 1)
}
```
```
Exception in thread "ForkJoinPool-3-worker-7" java.lang.OutOfMemoryError: Java heap space
	at ca.uwaterloo.flix.language.ast.Type.map(Type.scala:167)
	at ca.uwaterloo.flix.language.ast.Type.map$(Type.scala:164)
	at ca.uwaterloo.flix.language.ast.Type$Apply.map(Type.scala:451)
	at ca.uwaterloo.flix.language.ast.Type.map(Type.scala:167)
	at ca.uwaterloo.flix.language.ast.Type.map$(Type.scala:164)
	at ca.uwaterloo.flix.language.ast.Type$Apply.map(Type.scala:451)
	at ca.uwaterloo.flix.language.ast.Type.map(Type.scala:167)
	at ca.uwaterloo.flix.language.ast.Type.map$(Type.scala:164)
	at ca.uwaterloo.flix.language.ast.Type$Apply.map(Type.scala:451)
	at ca.uwaterloo.flix.language.ast.Type.map(Type.scala:167)
	at ca.uwaterloo.flix.language.ast.Type.map$(Type.scala:164)
	at ca.uwaterloo.flix.language.ast.Type$Apply.map(Type.scala:451)
	at ca.uwaterloo.flix.language.ast.Type.map(Type.scala:167)
	at ca.uwaterloo.flix.language.ast.Type.map$(Type.scala:164)
	at ca.uwaterloo.flix.language.ast.Type$Apply.map(Type.scala:451)
```

**Comment by magnus-madsen** [comment]
Sad. Is this in monomorph? Maybe we need a different map function.

**Comment by JonathanStarup** [comment]
It is conceptually impossible

**Comment by magnus-madsen** [comment]
> It is conceptually impossible

Oh

**Comment by magnus-madsen** [comment]
So I guess you want an error message instead. But its tricky to produce, I think?

**Comment by JonathanStarup** [comment]
Yes, hard to spot, especially with the mutual example. And impossible with lambdas I'm pretty sure

My guess is that the best we can do is a cycle detection thing in MonoDefs

**Comment by JonathanStarup** [comment]
One way to solve it is to monomorphize to erased types, this would break the cycle. This would however also break typematch
