### ISSUE TITLE
Java interoperability error

### ISSUE THREAD

**Issue by mobilemindtec** [flix/flix#7220]
Hi, I'm updating a project I did a while ago that interoperates flix with armeria. I'm getting a strange error when accessing a class that contains the request headers. It seems that the method where the error occurs is inside an inherited interface. Any idea?

The code:

```flix

import import com.linecorp.armeria.common.HttpRequest;

def convertRequest(req: HttpRequest): Armeria.HttpRequest \ IO =
    import com.linecorp.armeria.common.HttpRequest.headers(): RequestHeaders \ IO as requestHeaders;
    import com.linecorp.armeria.common.RequestHeaders.names() : ##java.util.Set \ IO as headersNames;
    import com.linecorp.armeria.common.RequestHeaders.get(##java.lang.CharSequence) : String \ IO as headersGet;    

    let reqHeaders = req |> requestHeaders;
    let setOfNames = reqHeaders |> headersNames; // boom!!! error
    let names: Set[String] = setOfNames |> Adaptor.fromSet;

  // ........

```

The error:

```shell
20:23:28.249 [armeria-common-worker-epoll-3-2] WARN com.linecorp.armeria.server.DefaultUnhandledExceptionsReporter -- Observed 1 exception(s) that didn't reach a LoggingService in the last 10000ms(10000000000ns). Please consider adding a LoggingService as the outermost decorator to get detailed error logs. One of the thrown exceptions:
java.lang.IllegalAccessError: failed to access class com.linecorp.armeria.common.HttpHeaderGetters from class ArmeriaApi.Def$convertRequest (com.linecorp.armeria.common.HttpHeaderGetters is in unnamed module of loader ca.uwaterloo.flix.util.ExternalJarLoader @723e88f9; ArmeriaApi.Def$convertRequest is in unnamed module of loader ca.uwaterloo.flix.language.phase.jvm.FlixClassLoader @64a1923a)
        at ArmeriaApi.Def$convertRequest.applyFrame(Unknown Source)
        at ArmeriaApi.Def$convertRequest.invoke(Unknown Source)
        at ArmeriaApi.Clo$newServiceSpec$412851.applyFrame(Unknown Source)
        at ArmeriaApi.Clo$newServiceSpec$412851.invoke(Unknown Source)
        at Anon$304914.serve(Unknown Source)
        at com.linecorp.armeria.server.HttpServerHandler.serve0(HttpServerHandler.java:455)
        at com.linecorp.armeria.server.HttpServerHandler.handleRequest(HttpServerHandler.java:392)
        at com.linecorp.armeria.server.HttpServerHandler.channelRead(HttpServerHandler.java:281)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at com.linecorp.armeria.server.Http1RequestDecoder.channelRead(Http1RequestDecoder.java:278)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at com.linecorp.armeria.server.HttpServerUpgradeHandler.channelRead(HttpServerUpgradeHandler.java:228)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:266)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:536)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)
20:23:33.261 [armeria-common-worker-epoll-3-1] DEBUG com.linecorp.armeria.internal.common.AbstractKeepAliveHandler -- [id: 0x7b135aef, L:/127.0.0.1:8181 - R:/127.0.0.1:39528] Closing an idle server connection
```

I would like to leave this repository as an example of a more complex integration with Java code. Thanks!

https://github.com/mobilemindtec/flix-armeria/

**Comment by magnus-madsen** [comment]
Strange. I wonder what the problem is. What is the accessibility of that class? It is not private, right?

**Comment by magnus-madsen** [comment]
https://stackoverflow.com/questions/7076414/java-lang-illegalaccesserror-tried-to-access-method

**Comment by magnus-madsen** [comment]
Not sure exactly what should be done here.

When do you get the above error? In the repl or after building a jar and running it?

**Comment by mobilemindtec** [comment]
I'm running using repl. I tried executing now using `run` but the application exits shortly after starting, as if the thread was not "holding" the execution. The same java code works.

So I'm trying to join the main thread, but I can't.

```flix
  def thread_join(): Unit \ IO =
    import static java.lang.Thread.currentThread(): Thread \ IO;
    import java.lang.Thread.join(): Void \ IO as join;
    let t: Thread = currentThread();
    t |> join; // error "Impossible cast"
    ()
```

**Comment by mobilemindtec** [comment]
the interface `HttpHeaderGetters` is not public, but there is a hierarchy of interfaces in these structures.

https://github.com/line/armeria/blob/main/core/src/main/java/com/linecorp/armeria/common/HttpHeaderGetters.java

The equivalent java code:

```java
        sb.service("/", (ctx, req) -> {

            logger.info(">>>> " + req.headers().getClass().getName()); // print com.linecorp.armeria.common.DefaultRequestHeaders


            req.headers().names().forEach(s -> logger.info(s + "=" + req.headers().get(s)));

            return HttpResponse.of("Hello, world!");
        });
```

**Comment by magnus-madsen** [comment]
What if you do build-jar and run the built jar?

**Comment by magnus-madsen** [comment]
(Remember to run build before build-jar).

**Comment by magnus-madsen** [comment]
Unfortunately there is not yet a way to create a fat jar, but its a good idea. I added a ticket here: https://github.com/flix/flix/issues/7224

For your current problem, I think you need to set your class path correctly. Not sure exactly what to do, the output from your terminal is a bit messed up.

**Comment by mobilemindtec** [comment]
It worked! I was executing the command with wrong arguments.

`java  -cp "app.jar:lib/*"  Main`

the `lib` folder contains `find lib/cache -name "*.jar" -exec cp {} artefact/lib/ \;`


but the same error happened

**Comment by mobilemindtec** [comment]
Another interesting thing that would solve the problem in a simple way would be the possibility of generating some glue code with a java file.

**Comment by magnus-madsen** [comment]
Sorry, what works and what does not?

**Comment by magnus-madsen** [comment]
The error is also in the compiled jar. Thats very strange :/ because there we have no class loaders.

**Comment by mobilemindtec** [comment]
Is there a way to make glue code in Java?

**Comment by magnus-madsen** [comment]
> Is there a way to make glue code in Java?

Depends on what you mean? You can compile your Flix program to classes and call that.

**Comment by magnus-madsen** [comment]
I am still unsure about the fundamental problem. Something strange with class loaders must be going on in one of your libraries.

**Comment by mobilemindtec** [comment]
With glue code, I mean adding a java class to the project structure and calling that class from flix, without having to create a "glue library"

If you want to take a look, the code is here https://github.com/mobilemindtec/flix-armeria/. The project is very small, I'm using it to explore the language.

**Comment by magnus-madsen** [comment]
You can create a Java class, compile it to a .class file, put that into a JAR file, and then put that JAR file in the lib folder.

**Comment by magnus-madsen** [comment]
But I am not sure if it will help because something strange is going on.

**Comment by mobilemindtec** [comment]
Yes, I know how I could improvise a Java glue code. I think the glue code is a separate conversation, as this would be an additional feature that would work in the build and also in the IDE's inference. Since flix is ​​developed on top of the JDK, glue code feature is essential, in potential cases where a java code must be used for some reason. And this would have to be an easy thing, that is, just add a .java to a project folder and then the magic happens.

**Comment by magnus-madsen** [comment]
We have recently reworked how interop works. See https://doc.flix.dev/interoperability.html

Perhaps this solves your problem?
