### ISSUE TITLE
Casting Int32 to Int64

### ISSUE THREAD

**Issue by stetimi** [flix/flix#7318]
I got a compiler crash report on opening the REPL on a Mac M1, JDK 21.
I'm using flix from main branch, commit id: a20714f5dfe1ad544523d9d6af288216e34971a9
I minimized it, gist is here: https://gist.github.com/stetimi/49c9072caa535f987da4de46415775e4
Crash report is attached.
[crash_report_1.txt](https://github.com/flix/flix/files/14442312/crash_report_1.txt)

I'm using unchecked_cast to get from Int32 to Int64: I've since discovered Int32.toInt64
But the message does say it's a compiler bug so I thought I should report.

**Comment by magnus-madsen** [comment]
Thanks @stetimi 

This is actually not a compiler bug. You cannot cast Int32 to Int64.

But I do wonder why our "impossible cast" did not detect this.

**Comment by stetimi** [comment]
I tried minimizing a bit more, now I get a slightly different crash 
```
def main(): Unit \ IO =
    println(evil(5))

def evil(n: Int32): Int64 =
    unchecked_cast(n as Int64)
```

# -- Stack Trace --
java.lang.ArrayIndexOutOfBoundsException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:542)
	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:567)
	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:653)
	at java.base/java.util.concurrent.ForkJoinPool.invoke(ForkJoinPool.java:2822)
	at ca.uwaterloo.flix.util.ParOps$.parAgg(ParOps.scala:134)
	at ca.uwaterloo.flix.language.phase.jvm.GenFunAndClosureClasses$.gen(GenFunAndClosureClasses.scala:41)
	at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.$anonfun$run$2(JvmBackend.scala:81)
	at ca.uwaterloo.flix.api.Flix.subphase(Flix.scala:684)
	at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.$anonfun$run$1(JvmBackend.scala:39)
	at ca.uwaterloo.flix.api.Flix.phase(Flix.scala:665)
	at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.run(JvmBackend.scala:33)
	at ca.uwaterloo.flix.api.Flix.codeGen(Flix.scala:622)
	at ca.uwaterloo.flix.runtime.shell.Shell.$anonfun$compile$1(Shell.scala:369)
	at ca.uwaterloo.flix.util.Validation$.flatMapN(Validation.scala:524)
	at ca.uwaterloo.flix.runtime.shell.Shell.compile(Shell.scala:369)
	at ca.uwaterloo.flix.runtime.shell.Shell.execReload(Shell.scala:190)
	at ca.uwaterloo.flix.runtime.shell.Shell.loop(Shell.scala:101)
	at ca.uwaterloo.flix.Main$.main(Main.scala:261)
	at ca.uwaterloo.flix.Main.main(Main.scala)
Caused by: java.lang.ArrayIndexOutOfBoundsException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:542)
	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:567)
	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:653)
	at ca.uwaterloo.flix.util.ParOps$Task$1.compute(ParOps.scala:123)
	at java.base/java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:110)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
	at org.objectweb.asm.Frame.getConcreteOutputType(Frame.java:1150)
	at org.objectweb.asm.Frame.merge(Frame.java:1250)
	at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1612)
	at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1548)
	at ca.uwaterloo.flix.language.phase.jvm.GenFunAndClosureClasses$.compileFrameMethod(GenFunAndClosureClasses.scala:252)
	at ca.uwaterloo.flix.language.phase.jvm.GenFunAndClosureClasses$.genCode(GenFunAndClosureClasses.scala:153)
	at ca.uwaterloo.flix.language.phase.jvm.GenFunAndClosureClasses$.$anonfun$gen$2(GenFunAndClosureClasses.scala:53)
	at ca.uwaterloo.flix.util.ParOps$Task$1.$anonfun$compute$1(ParOps.scala:114)
	at ca.uwaterloo.flix.util.ParOps$Task$1.$anonfun$compute$1$adapted(ParOps.scala:113)
	at scala.collection.IterableOnceOps.foldLeft(IterableOnce.scala:644)
	at scala.collection.IterableOnceOps.foldLeft$(IterableOnce.scala:670)
	at scala.collection.AbstractIterable.foldLeft(Iterable.scala:933)
	at ca.uwaterloo.flix.util.ParOps$Task$1.compute(ParOps.scala:113)
	... 6 more

**Comment by stetimi** [comment]
I see the "impossible cast" code you mention, @magnus-madsen :
https://github.com/flix/flix/blob/0368700eae7bc7d06ac8e3febc55d451baea612c/main/src/ca/uwaterloo/flix/language/phase/Safety.scala#L454

Should it just disallow any cast between (different) primitive types?

Note, some casts do actually work:
```
flix> unchecked_cast(65 as Char) |> println
A                                                                               
()
```

**Comment by stetimi** [comment]
Yep - I reported it because said "please report" in the error message.

**Comment by magnus-madsen** [comment]
Not a bug-- though the error message is misleading. Unfortunately there is nothing we can do to fix that.
