### ISSUE TITLE
Compiler threw an exception on associated type

### ISSUE THREAD

**Issue by stetimi** [flix/flix#7447]
Dunno if this is valid, I was just trying to play with associated types.
```
trait Play[t] {
    type Output
    pub def play(t: t): Play.Output[t]
}

instance Play[String] {
    type Output = List
    pub def play(s: String): List[String] = List#{s}
}

def main(): Unit \ IO =
    let _x = Play.play("");
    println("hello")
```

I ran :build in the repl, and it said:
```
# This is a bug in the Flix compiler. Please report it here:
#
# https://github.com/flix/flix/issues
#
# -- Flix Compiler --
#
# Flix Version : 0.45.0
#   incremental: All
#
# -- Java Virtual Machine --
#
# JVM Version  : 21.0.2 (2024-01-16)
# JVM Vendor   : Homebrew
# JAVA_HOME    : /opt/homebrew/Cellar/openjdk/21.0.2/libexec/openjdk.jdk/Contents/Home
# System       : Mac OS X (14.3.1)
#
# -- Stack Trace --
ca.uwaterloo.flix.util.InternalCompilerException: No default or matching definition found for 'Play.play'.
        at ca.uwaterloo.flix.language.phase.Monomorpher$.specializeSigSym(Monomorpher.scala:674)
        at ca.uwaterloo.flix.language.phase.Monomorpher$.visitExp(Monomorpher.scala:438)
        at ca.uwaterloo.flix.language.phase.Monomorpher$.visitExp(Monomorpher.scala:450)
        at ca.uwaterloo.flix.language.phase.Monomorpher$.visitExp(Monomorpher.scala:462)
        at ca.uwaterloo.flix.language.phase.Monomorpher$.mkFreshDefn(Monomorpher.scala:394)
        at ca.uwaterloo.flix.language.phase.Monomorpher$.$anonfun$run$3(Monomorpher.scala:338)
        at ca.uwaterloo.flix.language.phase.Monomorpher$.$anonfun$run$3$adapted(Monomorpher.scala:333)
        at ca.uwaterloo.flix.util.ParOps$.$anonfun$parMap$2(ParOps.scala:64)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

**Comment by magnus-madsen** [comment]
Associated types are not yet fully implemented. Stay tuned.

**Comment by magnus-madsen** [comment]
Fixed in master.
