### ISSUE TITLE
IndexOutOfBounds in Lexer

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#7458]
My fuzzer found a bug in the lexer on:

```
// A Suit type deriving an Eq and ToString instance
enum Suit with Eq, ToString {
    case Clubs
    case Hearts
    case Spades
    case Diamonds
}

// A Rank type deriving an Eq and Order instance
enum Rank with Eq, Order {
    case Number(Int32)
    case Jack
    case Queen
    case King
    case Ace
}

// A Card type deriving an Eq instance
enum Card(Rank, Suit) with Eq

// An instance of ToString for Ranks
instance ToString[Rank] {
    pub def toString(x: Rank): String = match x {
        case Rank.Number(n) => "${n}"
        case Rank.Jack      => "Jack"
        case Rank.Queen     => "Queen"
        case Rank.King      => "King"
        case Rank.Ace       => "Ace"
    }
}

// An instance of ToString for Cards
instance ToString[Card] {
    pub def toString(x: Card): String = match x {
        case Card.Card(r, s) => "${r}
```

Gives

```
java.lang.ArrayIndexOutOfBoundsException: Index 840 out of bounds for length 840
	at ca.uwaterloo.flix.language.phase.Lexer$.advance(Lexer.scala:171)
	at ca.uwaterloo.flix.language.phase.Lexer$.acceptString(Lexer.scala:799)
	at ca.uwaterloo.flix.language.phase.Lexer$.scanToken(Lexer.scala:332)
	at ca.uwaterloo.flix.language.phase.Lexer$.lex(Lexer.scala:145)
	at ca.uwaterloo.flix.language.phase.Lexer$.tryLex(Lexer.scala:127)
	at ca.uwaterloo.flix.language.phase.Lexer$.$anonfun$run$2(Lexer.scala:112)
```

**Comment by magnus-madsen** [comment]
Fixed in master.
