### ISSUE TITLE
Crash during `TypeReconstruction`

### ISSUE THREAD

**Issue by jaschdoc** [flix/flix#7650]
Was testing out the completers and got an error from the program below (which is not a valid program but I was midway through typing it).

```scala
pub def main(): Unit \ IO =
    println("The sum from 0..42 is")


pub def f(x: Option[a]): Option[a] = match
```

```
#
# An unexpected error has been detected by the Flix compiler:
#
#   head of empty list
#
# This is a bug in the Flix compiler. Please report it here:
#
# https://github.com/flix/flix/issues
#
# -- Flix Compiler --
#
# Flix Version : 0.46.0
#   incremental: All
#
# -- Java Virtual Machine --
#
# JVM Version  : 21.0.1 (2023-10-17)
# JVM Vendor   : GraalVM Community
# JAVA_HOME    : /home/_/.sdkman/candidates/java/21.0.1-graalce
# System       : Linux
#
# -- Stack Trace --
java.util.NoSuchElementException: head of empty list
	at scala.collection.immutable.Nil$.head(List.scala:662)
	at scala.collection.immutable.Nil$.head(List.scala:661)
	at ca.uwaterloo.flix.language.phase.TypeReconstruction$.visitExp(TypeReconstruction.scala:195)
	at ca.uwaterloo.flix.language.phase.TypeReconstruction$.visitDef(TypeReconstruction.scala:35)
	at ca.uwaterloo.flix.language.phase.Typer$.$anonfun$visitDef$1(Typer.scala:179)
	at ca.uwaterloo.flix.util.Validation$.mapN(Validation.scala:429)
	at ca.uwaterloo.flix.language.phase.Typer$.visitDef(Typer.scala:178)
	at ca.uwaterloo.flix.language.phase.Typer$.$anonfun$visitDefs$2(Typer.scala:162)
	at ca.uwaterloo.flix.util.ParOps$.$anonfun$parTraverseValues$1(ParOps.scala:106)
	at ca.uwaterloo.flix.util.ParOps$.$anonfun$parMap$2(ParOps.scala:64)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

_Originally posted by @jaschdoc in https://github.com/flix/flix/issues/7605#issuecomment-2068056794_

**Comment by magnus-madsen** [comment]
@herluf-ba I think this was also fixed then?
