### ISSUE TITLE
typer crash on error effect

### ISSUE THREAD

**Issue by sockmaster27** [flix/flix#7895]
Happens on the newest version of the compiler (0.48.0) with input
```flix
def reachable(origin: n, edges: f[(n, n)]): Set[n] \ Aef[f] = Set#{}
```

<details>
<summary>Crash report</summary><pre>
#
# An unexpected error has been detected by the Flix compiler:
#
#   Unexpected type: 'Error'.
#
# This is a bug in the Flix compiler. Please report it here:
#
# https://github.com/flix/flix/issues
#
# -- Flix Compiler --
#
# Flix Version : 0.48.0
#   incremental: All
#
# -- Java Virtual Machine --
#
# JVM Version  : 21.0.1 (2023-10-17)
# JVM Vendor   : Oracle Corporation
# JAVA_HOME    : C:\Program Files\Java\jdk-21
# System       : Windows 11 (10.0)
#
# -- Stack Trace --
ca.uwaterloo.flix.util.InternalCompilerException: Unexpected type: 'Error'.
	at ca.uwaterloo.flix.language.phase.unification.BoolAlg.fromType(BoolAlg.scala:157)
	at ca.uwaterloo.flix.language.phase.unification.BoolAlg.fromType$(BoolAlg.scala:142)
	at ca.uwaterloo.flix.language.phase.unification.BoolFormulaAlg.fromType(BoolFormulaAlg.scala:28)
	at ca.uwaterloo.flix.language.phase.unification.EffUnification$.lookupOrSolve(EffUnification.scala:243)
	at ca.uwaterloo.flix.language.phase.unification.EffUnification$.unify(EffUnification.scala:171)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.$anonfun$resolveEquality$4(ConstraintSolver.scala:332)
	at ca.uwaterloo.flix.util.Result.flatMap(Result.scala:62)
	at ca.uwaterloo.flix.util.Result.flatMap$(Result.scala:61)
	at ca.uwaterloo.flix.util.Result$Ok.flatMap(Result.scala:94)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.$anonfun$resolveEquality$2(ConstraintSolver.scala:331)
	at ca.uwaterloo.flix.util.Result.flatMap(Result.scala:62)
	at ca.uwaterloo.flix.util.Result.flatMap$(Result.scala:61)
	at ca.uwaterloo.flix.util.Result$Ok.flatMap(Result.scala:94)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.resolveEquality(ConstraintSolver.scala:330)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.resolveOne(ConstraintSolver.scala:273)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.tryResolve$1(ConstraintSolver.scala:252)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.resolveOneOf(ConstraintSolver.scala:262)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.resolve(ConstraintSolver.scala:228)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.visitSpec(ConstraintSolver.scala:110)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.visitDef(ConstraintSolver.scala:56)
	at ca.uwaterloo.flix.language.phase.Typer$.visitDef(Typer.scala:173)
	at ca.uwaterloo.flix.language.phase.Typer$.$anonfun$visitDefs$1(Typer.scala:159)
	at ca.uwaterloo.flix.util.ParOps$.$anonfun$parTraverseValues$1(ParOps.scala:106)
	at ca.uwaterloo.flix.util.ParOps$.$anonfun$parMap$2(ParOps.scala:64)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
</pre></details>

**Comment by JonathanStarup** [comment]
Ive had this many times, I think `Error` is unhandled in the bool solver stuff

**Comment by JonathanStarup** [comment]
Better than crashing on master

```
-- Type Error -------------------------------------------------- test.flix

>> Unable to unify the types: 'Error' and 'e0'.

1 | def reachable(_origin: n, _edges: f[(n, n)]): Set[n] \ Aef[f] = Set#{}
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    mismatched types.

Type One: Error
Type Two: e0

-- Resolution Error -------------------------------------------------- test.flix

>> Undefined type 'Aef'.

1 | def reachable(_origin: n, _edges: f[(n, n)]): Set[n] \ Aef[f] = Set#{}
                                                           ^^^
                                                           type not found.
```
