### ISSUE TITLE
[Concurrency?] Code generation bug

### ISSUE THREAD

**Issue by acieroid** [flix/flix#790]
Running the following program:

```
def eval(): Unit = {
  let c5 = chan Unit 0;
  let c6 = chan Unit 0;
  let c7 = chan Unit 0;
  let c8 = chan Unit 0;
  spawn {

    select {
      case nocare <- c7 => c8 <- () ; ()
      case nocare <- c7 => c8 <- () ; ()
    } ; ()
  } ;
  spawn { <- c6 ; c7 <- () ; () } ;
  spawn {
    <- c5 ; () ;
    c6 <- () ; ()
  } ; () ;
  c5 <- () ; () ; () ;
  <- c8;
    ()
}

def main(): Unit = eval()
```

Generates the following error:
```
Exception in thread "main" java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    Def$eval$14086.invoke(LContext;)V @59: aload
  Reason:
    Type top (current frame, locals[7]) is not assignable to reference type
  Current Frame:
    bci: @59
    flags: { }
    locals: { 'Def$eval$14086', 'Context', top, 'java/lang/Object', top, 'java/lang/Object' }
    stack: { }
  Bytecode:
    0000000: 2ab4 000c 4e05 bd00 1959 032d c000 04c0
    0000010: 0019 5359 042d c000 04c0 0019 5303 b800
    0000020: 1d59 b400 239a 0055 59b4 0027 5903 649a
    0000030: 0023 57b4 002a c000 043a 0519 07c0 0004
    0000040: c000 1959 b800 30b6 0033 3a06 b800 30a7
    0000050: 002e 5904 649a 0023 57b4 002a c000 043a
    0000060: 0719 07c0 0004 c000 1959 b800 30b6 0033
    0000070: 3a08 b800 30a7 0008 01bf 5701 bf3a 04b8
    0000080: 0030 2a5f b500 11b1                    
  Stackmap Table:
    full_frame(@82,{Object[#2],Object[#53],Top,Object[#4]},{Object[#31],Integer})
    full_frame(@120,{Object[#2],Object[#53],Top,Object[#4]},{Object[#31],Integer})
    same_locals_1_stack_item_frame(@122,Object[#31])
    same_locals_1_stack_item_frame(@125,Object[#44])

	at Ns.<init>(Unknown Source)
	at Context.<init>(Unknown Source)
	at Ns.m_main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.$anonfun$link$1(JvmBackend.scala:246)
	at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.$anonfun$getCompiledDefs$2(JvmBackend.scala:219)
	at ca.uwaterloo.flix.runtime.CompilationResult.evalToString(CompilationResult.scala:90)
	at ca.uwaterloo.flix.Main$.$anonfun$main$6(Main.scala:143)
	at ca.uwaterloo.flix.util.Timer.<init>(Timer.scala:28)
	at ca.uwaterloo.flix.Main$.main(Main.scala:143)
	at ca.uwaterloo.flix.Main.main(Main.scala)
```

**Comment by acieroid** [comment]
A variant of the previous program (that compiles successfully, but not correctly I think) is the following:
```
def main(): Unit = {
  let c7 = chan Unit 0;
  let c8 = chan Unit 0;
  spawn {
    let c100 = chan Unit 0;
    let c101 = chan Unit 0;
    select {
      case nocare <- c7 => c8 <- () ; ()
      case nocare <- c7 => c8 <- () ; ()
    } ; ()
  } ;
  spawn { c7 <- () ; () } ;
  <- c8; ()
}
```

However, this program deadlocks (while it clearly should not). After some investigation, what seems to happen is that the send over c8 in the `select` is actually sending to one of the channels `c100` or `c101`. Local variables between the main thread and the spawned thread seems mixed up. This is no longer the case when `select` is not present, e.g., the following program is semantically equivalent, but compiles and runs as expected, sending over the expected channels : 
```
def main(): Unit = {
  let c7 = chan Unit 0;
  let c8 = chan Unit 0;
  spawn {
    let c100 = chan Unit 0;
    let c101 = chan Unit 0;
    <- c7 ; c8 <- () ; ()
  } ;
  spawn { c7 <- () ; () } ;
  <- c8; ()
}
```

**Comment by magnus-madsen** [comment]
> Local variables between the main thread and the spawned thread seems mixed up. 
😮 
If this is true that is a good find!

**Comment by magnus-madsen** [comment]
These programs now compile and run, but I don't know if they are executed correctly.

**Comment by magnus-madsen** [comment]
Assuming the bug has been fixed.
