### ISSUE TITLE
[Backend] Closures Class Generation throws exception

### ISSUE THREAD

**Issue by ifazk** [flix/flix#793]
I was playing around with closures and this input threw an error.

Flix version: 0.6.0

Input: test1.flix
```scala
def bar(x: Int): Int =
  if (x > 2) bar(1) else x

def foo(): Int =
  let barr = bar;
  barr(2)

def main(): Unit =
  Console.printLine("hi there")
```

Command:
```bash
java -jar ../flix.jar test1.flix
```

Output:
```bash
Exception in thread "main" java.lang.NullPointerException
	at org.objectweb.asm.Frame.a(Unknown Source)
	at org.objectweb.asm.MethodWriter.visitMaxs(Unknown Source)
	at ca.uwaterloo.flix.language.phase.jvm.GenClosureClasses$.compileInvokeMethod(GenClosureClasses.scala:218)
	at ca.uwaterloo.flix.language.phase.jvm.GenClosureClasses$.genByteCode(GenClosureClasses.scala:112)
	at ca.uwaterloo.flix.language.phase.jvm.GenClosureClasses$.$anonfun$gen$1(GenClosureClasses.scala:25)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:157)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:95)
	at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:155)
	at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
	at ca.uwaterloo.flix.language.phase.jvm.GenClosureClasses$.gen(GenClosureClasses.scala:21)
	at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.$anonfun$run$1(JvmBackend.scala:110)
	at ca.uwaterloo.flix.api.Flix.phase(Flix.scala:278)
	at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.run(JvmBackend.scala:37)
	at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.run(JvmBackend.scala:32)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.$anonfun$run$1(Phase.scala:42)
	at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:49)
	at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:48)
	at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:73)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
	at ca.uwaterloo.flix.api.Flix.codeGen(Flix.scala:258)
	at ca.uwaterloo.flix.api.Flix.$anonfun$compile$1(Flix.scala:266)
	at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:49)
	at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:48)
	at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:73)
	at ca.uwaterloo.flix.api.Flix.compile(Flix.scala:265)
	at ca.uwaterloo.flix.Main$.$anonfun$main$5(Main.scala:136)
	at ca.uwaterloo.flix.util.Timer.<init>(Timer.scala:28)
	at ca.uwaterloo.flix.Main$.main(Main.scala:136)
	at ca.uwaterloo.flix.Main.main(Main.scala)
```

**Comment by ifazk** [comment]
Also tried it out with the latest commit from master flix/flix@fe5637245fcccb41770879638fe923da4330613b. Had the same issue.

**Comment by magnus-madsen** [comment]
Thanks for reporting this!

@ma-fialho We should look into this when we get to closures.

**Comment by magnus-madsen** [comment]
This example seems to simple I wonder what could be wrong. The NullPointer from ASM is also "intriguing".

**Comment by ifazk** [comment]
This bug seems to only happen if we let bind `bar` when `bar` takes a single input and is recursive. If we change `bar` and `foo` to the following, the exception disappears.
```scala
def bar(x: Int): Int =
  x + x

def foo(): Int =
  let barr = bar;
  barr(4)
```

```scala
def bar(x: Int, y: Int): Int =
  if (x > 2) bar(1,y) else y

def foo(): Int =
  let barr = bar;
  barr(4,2)
```

```scala

def bar(x: Int, y: Int): Int =
  if (x > 2) bar(1,y) else y

def foo(): Int =
  let barr = bar(4);
  barr(5)
```

**Comment by magnus-madsen** [comment]
All the examples compile now, so I am closing this.
