### ISSUE TITLE
ConstraintSolver crash (on wrong Aef definition)

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#7966]
```
trait Indexablee[t] {
    type Aef[t]: Eff
    pub def get(index: Int32, m: t): String \ Indexablee.Aef[t]
}

instance Indexablee[List[t]] {
    type Aef
    pub def get(index: Int32, m: List[t]): String \ Aef[t] = ???
}
```
```
#
# An unexpected error has been detected by the Flix compiler:
#
#   Unexpected type: 'Error'.
#
# This is a bug in the Flix compiler. Please report it here:
#
# https://github.com/flix/flix/issues
#
# -- Flix Compiler --
#
# Flix Version : 0.48.0
#   incremental: All
#
# -- Java Virtual Machine --
#
# JVM Version  : 21.0.1 (2023-10-17)
# JVM Vendor   : Oracle Corporation
# JAVA_HOME    : C:\Program Files\Java\jdk-21.0.1
# System       : Windows 11 (10.0)
#
# -- Stack Trace --
ca.uwaterloo.flix.util.InternalCompilerException: Unexpected type: 'Error'.
	at ca.uwaterloo.flix.language.phase.unification.BoolAlg.fromType(BoolAlg.scala:157)
	at ca.uwaterloo.flix.language.phase.unification.BoolAlg.fromType$(BoolAlg.scala:142)
	at ca.uwaterloo.flix.language.phase.unification.BoolFormulaAlg.fromType(BoolFormulaAlg.scala:28)
	at ca.uwaterloo.flix.language.phase.unification.EffUnification$.lookupOrSolve(EffUnification.scala:243)
	at ca.uwaterloo.flix.language.phase.unification.EffUnification$.unify(EffUnification.scala:171)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.$anonfun$resolveEquality$4(ConstraintSolver.scala:365)
	at ca.uwaterloo.flix.util.Result.flatMap(Result.scala:62)
	at ca.uwaterloo.flix.util.Result.flatMap$(Result.scala:61)
	at ca.uwaterloo.flix.util.Result$Ok.flatMap(Result.scala:94)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.$anonfun$resolveEquality$2(ConstraintSolver.scala:364)
	at ca.uwaterloo.flix.util.Result.flatMap(Result.scala:62)
	at ca.uwaterloo.flix.util.Result.flatMap$(Result.scala:61)
	at ca.uwaterloo.flix.util.Result$Ok.flatMap(Result.scala:94)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.resolveEquality(ConstraintSolver.scala:363)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.resolveOne(ConstraintSolver.scala:273)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.tryResolve$1(ConstraintSolver.scala:252)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.resolveOneOf(ConstraintSolver.scala:262)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.resolve(ConstraintSolver.scala:228)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.visitSpec(ConstraintSolver.scala:110)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.visitDef(ConstraintSolver.scala:56)
	at ca.uwaterloo.flix.language.phase.Typer$.visitDef(Typer.scala:178)
	at ca.uwaterloo.flix.language.phase.Typer$.$anonfun$visitInstance$4(Typer.scala:275)
	at ca.uwaterloo.flix.util.Validation$.$anonfun$fastTraverse$1(Validation.scala:284)
	at scala.collection.immutable.List.foreach(List.scala:334)
	at ca.uwaterloo.flix.util.Validation$.fastTraverse(Validation.scala:283)
	at ca.uwaterloo.flix.util.Validation$.traverse(Validation.scala:237)
	at ca.uwaterloo.flix.language.phase.Typer$.visitInstance(Typer.scala:275)
	at ca.uwaterloo.flix.language.phase.Typer$.$anonfun$visitInstances$4(Typer.scala:250)
	at ca.uwaterloo.flix.util.ParOps$.$anonfun$parMap$2(ParOps.scala:64)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

**Comment by mlutze** [comment]
Fixed by new solver
