### ISSUE TITLE
Crash of Flix compiler: No default or matching definition found for 'ToString.toString'

### ISSUE THREAD

**Issue by kenaryn** [flix/flix#8040]
**PROGRAM**

```
enum Connection(String, String)

enum InvalidInput {
    case InvalidUserName,
    case InvalidPassWord
}

def validateUser(s: String): Validation[InvalidInput, String] = 
    if (8 <= String.length(s) and String.forAll(Char.isLetter, s))
        Validation.Success(s)
    else
        Validation.Failure(Nec.singleton(InvalidInput.InvalidUserName))

def validatePass(s: String): Validation[InvalidInput, String] =
    if (12 <= String.length(s) and String.length(s) <= 20)
        Validation.Success(s)
    else
        Validation.Failure(Nec.singleton(InvalidInput.InvalidPassWord))

def connect(u: String, p: String): Validation[InvalidInput, Connection] =
    forA(
        user <- validateUser(u);
        pass <- validatePass(p)
    ) yield Connection.Connection(user, pass)

def main(): Validation[InvalidInput, Connection] \ {} =
    connect("Kena", "iamfree")
 ```
 
 **ERROR REPORT**
 
 ```
 Dependency resolution completed.
ca.uwaterloo.flix.util.InternalCompilerException: No default or matching definition found for 'ToString.toString'.
        at ca.uwaterloo.flix.language.phase.Monomorpher$.specializeSigSym(Monomorpher.scala:712)
        at ca.uwaterloo.flix.language.phase.Monomorpher$.visitExp(Monomorpher.scala:476)
        at ca.uwaterloo.flix.language.phase.Monomorpher$.visitExp(Monomorpher.scala:488)
        at ca.uwaterloo.flix.language.phase.Monomorpher$.$anonfun$visitExp$2(Monomorpher.scala:493)
        at scala.collection.immutable.List.map(List.scala:251)
        at ca.uwaterloo.flix.language.phase.Monomorpher$.visitExp(Monomorpher.scala:493)
        at ca.uwaterloo.flix.language.phase.Monomorpher$.$anonfun$visitExp$2(Monomorpher.scala:493)
        at scala.collection.immutable.List.map(List.scala:247)
        at ca.uwaterloo.flix.language.phase.Monomorpher$.visitExp(Monomorpher.scala:493)
        at ca.uwaterloo.flix.language.phase.Monomorpher$.$anonfun$visitExp$3(Monomorpher.scala:536)
        at scala.collection.immutable.List.map(List.scala:247)
        at ca.uwaterloo.flix.language.phase.Monomorpher$.visitExp(Monomorpher.scala:531)
        at ca.uwaterloo.flix.language.phase.Monomorpher$.mkFreshDefn(Monomorpher.scala:432)
        at ca.uwaterloo.flix.language.phase.Monomorpher$.$anonfun$run$4(Monomorpher.scala:388)
        at ca.uwaterloo.flix.language.phase.Monomorpher$.$anonfun$run$4$adapted(Monomorpher.scala:387)
        at ca.uwaterloo.flix.util.ParOps$.$anonfun$parMap$2(ParOps.scala:64)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
#
# An unexpected error has been detected by the Flix compiler:
#
#   No default or matching definition found for 'ToString.toString'.
#
# This is a bug in the Flix compiler. Please report it here:
#
# https://github.com/flix/flix/issues
#
# -- Flix Compiler --
#
# Flix Version : 0.48.0
#   incremental: All
#
# -- Java Virtual Machine --
#
# JVM Version  : 21.0.4-ea (2024-07-16)
# JVM Vendor   : Debian
# JAVA_HOME    : /usr/lib/jvm/java-21-openjdk-amd64
# System       : Linux (5.15.153.1-microsoft-standard-WSL2)
#
# -- Stack Trace --
ca.uwaterloo.flix.util.InternalCompilerException: No default or matching definition found for 'ToString.toString'.
        at ca.uwaterloo.flix.language.phase.Monomorpher$.specializeSigSym(Monomorpher.scala:712)
        at ca.uwaterloo.flix.language.phase.Monomorpher$.visitExp(Monomorpher.scala:476)
        at ca.uwaterloo.flix.language.phase.Monomorpher$.visitExp(Monomorpher.scala:488)
        at ca.uwaterloo.flix.language.phase.Monomorpher$.$anonfun$visitExp$2(Monomorpher.scala:493)
        at scala.collection.immutable.List.map(List.scala:251)
        at ca.uwaterloo.flix.language.phase.Monomorpher$.visitExp(Monomorpher.scala:493)
        at ca.uwaterloo.flix.language.phase.Monomorpher$.$anonfun$visitExp$2(Monomorpher.scala:493)
        at scala.collection.immutable.List.map(List.scala:247)
        at ca.uwaterloo.flix.language.phase.Monomorpher$.visitExp(Monomorpher.scala:493)
        at ca.uwaterloo.flix.language.phase.Monomorpher$.$anonfun$visitExp$3(Monomorpher.scala:536)
        at scala.collection.immutable.List.map(List.scala:247)
        at ca.uwaterloo.flix.language.phase.Monomorpher$.visitExp(Monomorpher.scala:531)
        at ca.uwaterloo.flix.language.phase.Monomorpher$.mkFreshDefn(Monomorpher.scala:432)
        at ca.uwaterloo.flix.language.phase.Monomorpher$.$anonfun$run$4(Monomorpher.scala:388)
        at ca.uwaterloo.flix.language.phase.Monomorpher$.$anonfun$run$4$adapted(Monomorpher.scala:387)
        at ca.uwaterloo.flix.util.ParOps$.$anonfun$parMap$2(ParOps.scala:64)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)


ca.uwaterloo.flix.util.InternalCompilerException: No default or matching definition found for 'ToString.toString'.
        at ca.uwaterloo.flix.language.phase.Monomorpher$.specializeSigSym(Monomorpher.scala:712)
        at ca.uwaterloo.flix.language.phase.Monomorpher$.visitExp(Monomorpher.scala:476)
        at ca.uwaterloo.flix.language.phase.Monomorpher$.visitExp(Monomorpher.scala:488)
        at ca.uwaterloo.flix.language.phase.Monomorpher$.$anonfun$visitExp$2(Monomorpher.scala:493)
        at scala.collection.immutable.List.map(List.scala:251)
        at ca.uwaterloo.flix.language.phase.Monomorpher$.visitExp(Monomorpher.scala:493)
        at ca.uwaterloo.flix.language.phase.Monomorpher$.$anonfun$visitExp$2(Monomorpher.scala:493)
        at scala.collection.immutable.List.map(List.scala:247)
        at ca.uwaterloo.flix.language.phase.Monomorpher$.visitExp(Monomorpher.scala:493)
        at ca.uwaterloo.flix.language.phase.Monomorpher$.$anonfun$visitExp$3(Monomorpher.scala:536)
        at scala.collection.immutable.List.map(List.scala:247)
        at ca.uwaterloo.flix.language.phase.Monomorpher$.visitExp(Monomorpher.scala:531)
        at ca.uwaterloo.flix.language.phase.Monomorpher$.mkFreshDefn(Monomorpher.scala:432)
        at ca.uwaterloo.flix.language.phase.Monomorpher$.$anonfun$run$4(Monomorpher.scala:388)
        at ca.uwaterloo.flix.language.phase.Monomorpher$.$anonfun$run$4$adapted(Monomorpher.scala:387)
        at ca.uwaterloo.flix.util.ParOps$.$anonfun$parMap$2(ParOps.scala:64)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

**NOTA BENE**

The vscode flix extension reports: `Source for: 'Validation.flix' is unavailable`.
Running WIndows 10 WSL 2 with Debian unstable.

**Comment by mlutze** [comment]
I can reproduce on the latest release but not on master, so I think this is fixed.

**Comment by JonathanStarup** [comment]
Confirmed to work on master
