### ISSUE TITLE
Trying to compose two records crashes JVM

### ISSUE THREAD

**Issue by cab404** [flix/flix#808]
`flix> {a = 2} <+> {a = 2}`
Expected: some message that tells you that you can do that only on Scheme types.
Actual:
```
Exception in thread "main" java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    Def$$1.invoke(LContext;)V @39: invokestatic
  Reason:
    Type 'RecordExtend$Int32' (current frame, stack[1]) is not assignable to 'flix/runtime/fixpoint/ConstraintSystem'
  Current Frame:
    bci: @39
    flags: { }
    locals: { 'Def$$1', 'Context', top, 'java/lang/Object' }
    stack: { 'RecordExtend$Int32', 'RecordExtend$Int32' }
  Bytecode:
    0000000: 2ab4 000c 4ebb 0019 5912 1b05 bb00 1d59
    0000010: b700 1eb7 0021 bb00 1959 121b 05bb 001d
    0000020: 59b7 001e b700 21b8 0027 2a5f b500 11b1
    0000030:                                        

	at Ns.<init>(Unknown Source)
	at Context.<init>(Unknown Source)
	at Ns.m_$1(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.$anonfun$link$1(JvmBackend.scala:243)
	at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.$anonfun$getCompiledDefs$2(JvmBackend.scala:216)
	at ca.uwaterloo.flix.runtime.CompilationResult.evalToString(CompilationResult.scala:90)
	at ca.uwaterloo.flix.runtime.shell.Shell.execEval(Shell.scala:207)
	at ca.uwaterloo.flix.runtime.shell.Shell.execute(Shell.scala:173)
	at ca.uwaterloo.flix.runtime.shell.Shell.loop(Shell.scala:130)
	at ca.uwaterloo.flix.Main$.main(Main.scala:127)
	at ca.uwaterloo.flix.Main.main(Main.scala)
```

I built Flix from 5314570.

**Comment by magnus-madsen** [comment]
Yes. This is a current limitation. Once we add kinds we will be able to disallow such programs.

**Comment by magnus-madsen** [comment]
@mlutze Do you know if this is also fixed now? :)

**Comment by cab404** [comment]
Still crashes playground)

**Comment by mlutze** [comment]
Looks like the latest revision to kinds fixes this:

```
  test("TmpTest.1") {
    val input = "def f(): {| x} = {a = 2} <+> {a = 2}"
    val result = compile(input, DefaultOptions)
    expectError[TypeError.MismatchedKinds](result)
  }

  test("TmpTest.2") {
    val input = "def f(): #{| x} = {a = 2} <+> {a = 2}"
    val result = compile(input, DefaultOptions)
    expectError[TypeError.MismatchedKinds](result)
  }

  test("TmpTest.3") {
    val input = "def f(): {a: Int} = {a = 2} <+> {a = 2}"
    val result = compile(input, DefaultOptions)
    expectError[TypeError.MismatchedKinds](result)
  }

```

These tests all succeed. I'll add these and other tests to our suite.

**Comment by magnus-madsen** [comment]
Fixed in master.
