### ISSUE TITLE
Consecutive calls error

### ISSUE THREAD

**Issue by chanattan** [flix/flix#8161]
This is the original function below from `main/src/library/Console.flix`:

```scala
pub def println(x: a): Unit \ IO with ToString[a] =
        import java.io.Console.writer(): ##java.io.PrintWriter \ IO;
        import java.io.PrintWriter.println(String): Unit \ IO as printWriterPrintln;
        console() |> Option.forEach(c -> printWriterPrintln(writer(c), ToString.toString(x)))
```

with the old import system it works.
The below refactoring doesn't work:

```scala
pub def println(x: a): Unit \ IO with ToString[a] =
        console() |> Option.forEach(c -> c.writer().println(ToString.toString(x)))
```
with the right imports, it causes the following error:

```scala
Unable to compile. Failed with: 1 errors.
  
  -- Type Error -------------------------------------------------- Console.flix
  
  >> Unable to unify the types: 'j0' and 't0'.
  
  78 |         console() |> Option.forEach(c -> c.writer().println(ToString.toString(x)))
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                mismatched types.
  
  Type One: j0
  Type Two: t0 (FlixSuite.scala:69)
                                                                                ca.uwaterloo.flix.util.InternalCompilerException: Unexpected error expression near
	at ca.uwaterloo.flix.language.phase.Lowering$.visitExp(Lowering.scala:800)
	at ca.uwaterloo.flix.language.phase.Lowering$.visitExp(Lowering.scala:370)
	at ca.uwaterloo.flix.language.phase.Lowering$.$anonfun$visitExps$1(Lowering.scala:807)
	at scala.collection.immutable.List.map(List.scala:247)
	at ca.uwaterloo.flix.language.phase.Lowering$.visitExps(Lowering.scala:807)
	at ca.uwaterloo.flix.language.phase.Lowering$.visitExp(Lowering.scala:376)
	at ca.uwaterloo.flix.language.phase.Lowering$.$anonfun$visitExps$1(Lowering.scala:807)
	at scala.collection.immutable.List.map(List.scala:251)
	at ca.uwaterloo.flix.language.phase.Lowering$.visitExps(Lowering.scala:807)
	at ca.uwaterloo.flix.language.phase.Lowering$.visitExp(Lowering.scala:376)
	at ca.uwaterloo.flix.language.phase.Lowering$.visitDef(Lowering.scala:177)
	at ca.uwaterloo.flix.language.phase.Lowering$.$anonfun$run$2(Lowering.scala:151)
	at ca.uwaterloo.flix.util.ParOps$.$anonfun$parMapValues$1(ParOps.scala:90)
	at ca.uwaterloo.flix.util.ParOps$.$anonfun$parMap$2(ParOps.scala:64)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```
which loops in `Unexpected error expression near`.

The same problem goes for the `print` function in the same file.

Even when using parentheses, the error persists, i.e., as `(c.writer()).println(...)`.
The issues were raised in PR #8156.

!!! EDIT !!! The following refactor compiled but failed in the test `polymorphic-record-update.flix`, see below for the error.

The most possible refactored function is now the following:

```scala
pub def println(x: a): Unit \ IO with ToString[a] =
        import java.io.PrintWriter.println(String): Unit \ IO as printWriterPrintln;
        console() |> Option.forEach(c -> printWriterPrintln(c.writer(), ToString.toString(x)))
```

Error:

```scala
 - polymorphic-record-update.flix
ca.uwaterloo.flix.util.InternalCompilerException: Unexpected type: 'writer'.
	at ca.uwaterloo.flix.language.phase.Simplifier$.visitType(Simplifier.scala:341)
	at ca.uwaterloo.flix.language.phase.Simplifier$.$anonfun$visitType$1(Simplifier.scala:227)
	at scala.collection.immutable.List.map(List.scala:247)
	at ca.uwaterloo.flix.language.phase.Simplifier$.visitType(Simplifier.scala:227)
	at ca.uwaterloo.flix.language.phase.Simplifier$.visitExp(Simplifier.scala:129)
	at ca.uwaterloo.flix.language.phase.Simplifier$.$anonfun$visitExp$1(Simplifier.scala:78)
	at scala.collection.immutable.List.map(List.scala:247)
	at ca.uwaterloo.flix.language.phase.Simplifier$.visitExp(Simplifier.scala:78)
	at ca.uwaterloo.flix.language.phase.Simplifier$.visitExp(Simplifier.scala:77)
	at ca.uwaterloo.flix.language.phase.Simplifier$.visitExp(Simplifier.scala:72)
	at ca.uwaterloo.flix.language.phase.Simplifier$.$anonfun$visitExp$1(Simplifier.scala:78)
	at scala.collection.immutable.List.map(List.scala:247)
	at ca.uwaterloo.flix.language.phase.Simplifier$.visitExp(Simplifier.scala:78)
	at ca.uwaterloo.flix.language.phase.Simplifier$.$anonfun$visitExp$1(Simplifier.scala:78)
	at scala.collection.immutable.List.map(List.scala:251)
	at ca.uwaterloo.flix.language.phase.Simplifier$.visitExp(Simplifier.scala:78)
	at ca.uwaterloo.flix.language.phase.Simplifier$.visitExp(Simplifier.scala:148)
	at ca.uwaterloo.flix.language.phase.Simplifier$.visitDef(Simplifier.scala:44)
	at ca.uwaterloo.flix.language.phase.Simplifier$.$anonfun$run$2(Simplifier.scala:34)
	at ca.uwaterloo.flix.util.ParOps$.$anonfun$parMapValues$1(ParOps.scala:90)
	at ca.uwaterloo.flix.util.ParOps$.$anonfun$parMap$2(ParOps.scala:64)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

**Comment by chanattan** [comment]
#8168 should have solved it.
