### ISSUE TITLE
bug: array get error

### ISSUE THREAD

**Issue by chanattan** [flix/flix#8190]
The following function crashes:

```scala
def testInvokeMethod2_09(): Bool \ IO =
      let obj = "Hello World";
      let arr = obj.split(" ");
      Array.get(0, arr) == "Hello"
```

Error:

```scala
ca.uwaterloo.flix.util.InternalCompilerException: Mismatched types near test.flix:10:20: tpe1 = Array(String), tpe2 = String
	at ca.uwaterloo.flix.language.phase.Verifier$.failMismatchedTypes(Verifier.scala:674)
	at ca.uwaterloo.flix.language.phase.Verifier$.checkEq(Verifier.scala:565)
	at ca.uwaterloo.flix.language.phase.Verifier$.visitExpr(Verifier.scala:71)
	at ca.uwaterloo.flix.language.phase.Verifier$.$anonfun$visitExpr$1(Verifier.scala:75)
	at scala.collection.immutable.List.map(List.scala:247)
	at ca.uwaterloo.flix.language.phase.Verifier$.visitExpr(Verifier.scala:75)
	at ca.uwaterloo.flix.language.phase.Verifier$.visitExpr(Verifier.scala:471)
	at ca.uwaterloo.flix.language.phase.Verifier$.visitExpr(Verifier.scala:472)
	at ca.uwaterloo.flix.language.phase.Verifier$.visitDef(Verifier.scala:44)
	at ca.uwaterloo.flix.language.phase.Verifier$.$anonfun$run$2(Verifier.scala:35)
	at ca.uwaterloo.flix.language.phase.Verifier$.$anonfun$run$2$adapted(Verifier.scala:35)
	at ca.uwaterloo.flix.util.ParOps$.$anonfun$parMap$2(ParOps.scala:64)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

**Comment by chanattan** [comment]
Is there a way to just print somehow what contains `arr`?
I believe it doesn't split the right way.

**Comment by magnus-madsen** [comment]
@mlutze @JonathanStarup Do we know what is wrong here? I suspect its because arrays returned by Java methods lack regions?

**Comment by mlutze** [comment]
@chanattan I've opened a PR with a fix. There was an issue with the subtype checking function used in the verifier.
