### ISSUE TITLE
Using a nonexistent trait can crash the compiler

### ISSUE THREAD

**Issue by dghosef** [flix/flix#8401]
This crashes the compiler:
```
def foo(): Unit \ NonExistentTrait.Aef[typevariable] =
    ()
```
with 
```
ca.uwaterloo.flix.util.InternalCompilerException: Unexpected type: 'Error'.
	at ca.uwaterloo.flix.language.phase.unification.BoolAlg.fromType(BoolAlg.scala:157)
	at ca.uwaterloo.flix.language.phase.unification.BoolAlg.fromType$(BoolAlg.scala:142)
	at ca.uwaterloo.flix.language.phase.unification.BoolFormulaAlg.fromType(BoolFormulaAlg.scala:28)
	at ca.uwaterloo.flix.language.phase.unification.EffUnification$.lookupOrSolve(EffUnification.scala:243)
	at ca.uwaterloo.flix.language.phase.unification.EffUnification$.unify(EffUnification.scala:171)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.$anonfun$resolveEquality$4(ConstraintSolver.scala:365)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.$anonfun$resolveEquality$2(ConstraintSolver.scala:364)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.resolveEquality(ConstraintSolver.scala:363)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.resolveOne(ConstraintSolver.scala:272)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.tryResolve$1(ConstraintSolver.scala:247)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.resolveOneOf(ConstraintSolver.scala:257)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.resolve(ConstraintSolver.scala:223)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.visitSpec(ConstraintSolver.scala:105)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.visitDef(ConstraintSolver.scala:51)
	at ca.uwaterloo.flix.language.phase.Typer$.visitDef(Typer.scala:183)
	at ca.uwaterloo.flix.language.phase.Typer$.$anonfun$visitDefs$1(Typer.scala:167)
	at ca.uwaterloo.flix.util.ParOps$.$anonfun$parTraverseValues$1(ParOps.scala:106)
	at ca.uwaterloo.flix.util.ParOps$.$anonfun$parMap$2(ParOps.scala:64)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

**Comment by mlutze** [comment]
Appears fixed
