### ISSUE TITLE
Crash in `PredicateCompleter`

### ISSUE THREAD

**Issue by jaschdoc** [flix/flix#8449]
The important part of the program is just
```
Person("A", "B").
Person("").
```

```
#
# An unexpected error has been detected by the Flix compiler:
#
#   head of empty list
#
# This is a bug in the Flix compiler. Please report it here:
#
# https://github.com/flix/flix/issues
#
# -- Flix Compiler --
#
# Flix Version : 0.49.0
#   incremental: All
#
# -- Java Virtual Machine --
#
# JVM Version  : 21.0.1 (2023-10-17)
# JVM Vendor   : GraalVM Community
# JAVA_HOME    : /home/_/java/21.0.1-graalce
# System       : Linux
#
# -- Stack Trace --
java.util.NoSuchElementException: head of empty list
	at scala.collection.immutable.Nil$.head(List.scala:663)
	at scala.collection.immutable.Nil$.head(List.scala:662)
	at ca.uwaterloo.flix.api.lsp.provider.completion.PredicateCompleter$.arityOf(PredicateCompleter.scala:47)
	at ca.uwaterloo.flix.api.lsp.provider.completion.PredicateCompleter$.$anonfun$getCompletions$5(PredicateCompleter.scala:39)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:584)
	at scala.collection.mutable.Growable.addAll(Growable.scala:62)
	at scala.collection.mutable.Growable.addAll$(Growable.scala:57)
	at scala.collection.immutable.SetBuilderImpl.addAll(Set.scala:405)
	at scala.collection.immutable.Set$.from(Set.scala:362)
	at scala.collection.immutable.Set$.from(Set.scala:93)
	at scala.collection.IterableOps$WithFilter.map(Iterable.scala:900)
	at ca.uwaterloo.flix.api.lsp.provider.completion.PredicateCompleter$.$anonfun$getCompletions$2(PredicateCompleter.scala:37)
	at scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:594)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:608)
	at scala.collection.immutable.List.prependedAll(List.scala:152)
	at scala.collection.immutable.List$.from(List.scala:685)
	at scala.collection.immutable.List$.from(List.scala:682)
	at scala.collection.IterableFactory$Delegate.from(Factory.scala:288)
	at scala.collection.immutable.Iterable$.from(Iterable.scala:35)
	at scala.collection.immutable.Iterable$.from(Iterable.scala:32)
	at scala.collection.IterableOps$WithFilter.flatMap(Iterable.scala:903)
	at ca.uwaterloo.flix.api.lsp.provider.completion.PredicateCompleter$.getCompletions(PredicateCompleter.scala:36)
	at ca.uwaterloo.flix.api.lsp.provider.CompletionProvider$.getCompletions(CompletionProvider.scala:138)
	at ca.uwaterloo.flix.api.lsp.provider.CompletionProvider$.autoComplete(CompletionProvider.scala:90)
	at ca.uwaterloo.flix.api.lsp.LanguageServer.processRequest(LanguageServer.scala:265)
	at ca.uwaterloo.flix.api.lsp.LanguageServer.onMessage(LanguageServer.scala:126)
	at org.java_websocket.server.WebSocketServer.onWebsocketMessage(WebSocketServer.java:728)
	at org.java_websocket.drafts.Draft_6455.processFrameText(Draft_6455.java:986)
	at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:910)
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:402)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:234)
	at org.java_websocket.server.WebSocketServer$WebSocketWorker.doDecode(WebSocketServer.java:1130)
	at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:1102)


java.util.NoSuchElementException: head of empty list
	at scala.collection.immutable.Nil$.head(List.scala:663)
	at scala.collection.immutable.Nil$.head(List.scala:662)
	at ca.uwaterloo.flix.api.lsp.provider.completion.PredicateCompleter$.arityOf(PredicateCompleter.scala:47)
	at ca.uwaterloo.flix.api.lsp.provider.completion.PredicateCompleter$.$anonfun$getCompletions$5(PredicateCompleter.scala:39)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:584)
	at scala.collection.mutable.Growable.addAll(Growable.scala:62)
	at scala.collection.mutable.Growable.addAll$(Growable.scala:57)
	at scala.collection.immutable.SetBuilderImpl.addAll(Set.scala:405)
	at scala.collection.immutable.Set$.from(Set.scala:362)
	at scala.collection.immutable.Set$.from(Set.scala:93)
	at scala.collection.IterableOps$WithFilter.map(Iterable.scala:900)
	at ca.uwaterloo.flix.api.lsp.provider.completion.PredicateCompleter$.$anonfun$getCompletions$2(PredicateCompleter.scala:37)
	at scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:594)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:608)
	at scala.collection.immutable.List.prependedAll(List.scala:152)
	at scala.collection.immutable.List$.from(List.scala:685)
	at scala.collection.immutable.List$.from(List.scala:682)
	at scala.collection.IterableFactory$Delegate.from(Factory.scala:288)
	at scala.collection.immutable.Iterable$.from(Iterable.scala:35)
	at scala.collection.immutable.Iterable$.from(Iterable.scala:32)
	at scala.collection.IterableOps$WithFilter.flatMap(Iterable.scala:903)
	at ca.uwaterloo.flix.api.lsp.provider.completion.PredicateCompleter$.getCompletions(PredicateCompleter.scala:36)
	at ca.uwaterloo.flix.api.lsp.provider.CompletionProvider$.getCompletions(CompletionProvider.scala:138)
	at ca.uwaterloo.flix.api.lsp.provider.CompletionProvider$.autoComplete(CompletionProvider.scala:90)
	at ca.uwaterloo.flix.api.lsp.LanguageServer.processRequest(LanguageServer.scala:265)
	at ca.uwaterloo.flix.api.lsp.LanguageServer.onMessage(LanguageServer.scala:126)
	at org.java_websocket.server.WebSocketServer.onWebsocketMessage(WebSocketServer.java:728)
	at org.java_websocket.drafts.Draft_6455.processFrameText(Draft_6455.java:986)
	at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:910)
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:402)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:234)
	at org.java_websocket.server.WebSocketServer$WebSocketWorker.doDecode(WebSocketServer.java:1130)
	at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:1102)
java.util.NoSuchElementException: head of empty list
	at scala.collection.immutable.Nil$.head(List.scala:663)
	at scala.collection.immutable.Nil$.head(List.scala:662)
	at ca.uwaterloo.flix.api.lsp.provider.completion.PredicateCompleter$.arityOf(PredicateCompleter.scala:47)
	at ca.uwaterloo.flix.api.lsp.provider.completion.PredicateCompleter$.$anonfun$getCompletions$5(PredicateCompleter.scala:39)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:584)
	at scala.collection.mutable.Growable.addAll(Growable.scala:62)
	at scala.collection.mutable.Growable.addAll$(Growable.scala:57)
	at scala.collection.immutable.SetBuilderImpl.addAll(Set.scala:405)
	at scala.collection.immutable.Set$.from(Set.scala:362)
	at scala.collection.immutable.Set$.from(Set.scala:93)
	at scala.collection.IterableOps$WithFilter.map(Iterable.scala:900)
	at ca.uwaterloo.flix.api.lsp.provider.completion.PredicateCompleter$.$anonfun$getCompletions$2(PredicateCompleter.scala:37)
	at scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:594)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:608)
	at scala.collection.immutable.List.prependedAll(List.scala:152)
	at scala.collection.immutable.List$.from(List.scala:685)
	at scala.collection.immutable.List$.from(List.scala:682)
	at scala.collection.IterableFactory$Delegate.from(Factory.scala:288)
	at scala.collection.immutable.Iterable$.from(Iterable.scala:35)
	at scala.collection.immutable.Iterable$.from(Iterable.scala:32)
	at scala.collection.IterableOps$WithFilter.flatMap(Iterable.scala:903)
	at ca.uwaterloo.flix.api.lsp.provider.completion.PredicateCompleter$.getCompletions(PredicateCompleter.scala:36)
	at ca.uwaterloo.flix.api.lsp.provider.CompletionProvider$.getCompletions(CompletionProvider.scala:138)
	at ca.uwaterloo.flix.api.lsp.provider.CompletionProvider$.autoComplete(CompletionProvider.scala:90)
	at ca.uwaterloo.flix.api.lsp.LanguageServer.processRequest(LanguageServer.scala:265)
	at ca.uwaterloo.flix.api.lsp.LanguageServer.onMessage(LanguageServer.scala:126)
	at org.java_websocket.server.WebSocketServer.onWebsocketMessage(WebSocketServer.java:728)
	at org.java_websocket.drafts.Draft_6455.processFrameText(Draft_6455.java:986)
	at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:910)
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:402)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:234)
	at org.java_websocket.server.WebSocketServer$WebSocketWorker.doDecode(WebSocketServer.java:1130)
	at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:1102)

```

**Comment by JonathanStarup** [comment]
@jaschdoc is it fixed now?

**Comment by magnus-madsen** [comment]
I fixed it.
