### ISSUE TITLE
Crash in BoolAlg on `Type -> Eff` kind

### ISSUE THREAD

**Issue by jaschdoc** [flix/flix#8527]
```
def main(): Unit \ IO =
    println("Hello World!")

trait A[a] {
    type T: Type -> Eff
    pub def afa(x: a, f: List[a]): a \ A.T[a][a] = ???
}
```
produces
```
#
# An unexpected error has been detected by the Flix compiler:
#
#   Unexpected type: ''8876458[t8825325]'.
#
# This is a bug in the Flix compiler. Please report it here:
#
# https://github.com/flix/flix/issues
#
# -- Flix Compiler --
#
# Flix Version : 0.50.0
#   incremental: All
#
# -- Java Virtual Machine --
#
# JVM Version  : 21.0.1 (2023-10-17)
# JVM Vendor   : GraalVM Community
# JAVA_HOME    : /_/java/21.0.1-graalce
# System       : Linux
#
# -- Stack Trace --
ca.uwaterloo.flix.util.InternalCompilerException: Unexpected type: ''8876458[t8825325]'.
	at ca.uwaterloo.flix.language.phase.unification.BoolAlg.fromType(BoolAlg.scala:157)
	at ca.uwaterloo.flix.language.phase.unification.BoolAlg.fromType$(BoolAlg.scala:142)
	at ca.uwaterloo.flix.language.phase.unification.BoolFormulaAlg.fromType(BoolFormulaAlg.scala:28)
	at ca.uwaterloo.flix.language.phase.unification.EffUnification$.lookupOrSolve(EffUnification.scala:245)
	at ca.uwaterloo.flix.language.phase.unification.EffUnification$.unify(EffUnification.scala:172)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.$anonfun$resolveEquality$4(ConstraintSolver.scala:348)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.$anonfun$resolveEquality$2(ConstraintSolver.scala:347)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.resolveEquality(ConstraintSolver.scala:346)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.resolveOne(ConstraintSolver.scala:272)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.tryResolve$1(ConstraintSolver.scala:247)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.resolveOneOf(ConstraintSolver.scala:257)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.resolve(ConstraintSolver.scala:223)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.visitSpec(ConstraintSolver.scala:105)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.visitSig(ConstraintSolver.scala:63)
	at ca.uwaterloo.flix.language.phase.Typer$.visitSig(Typer.scala:240)
	at ca.uwaterloo.flix.language.phase.Typer$.$anonfun$visitTrait$2(Typer.scala:216)
	at ca.uwaterloo.flix.util.Validation$.$anonfun$fastTraverse$1(Validation.scala:284)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:619)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:617)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:935)
	at ca.uwaterloo.flix.util.Validation$.traverse(Validation.scala:283)
	at ca.uwaterloo.flix.language.phase.Typer$.visitTrait(Typer.scala:216)
	at ca.uwaterloo.flix.language.phase.Typer$.$anonfun$visitTraits$1(Typer.scala:199)
	at ca.uwaterloo.flix.util.ParOps$.$anonfun$parTraverseValues$1(ParOps.scala:106)
	at ca.uwaterloo.flix.util.ParOps$.$anonfun$parMap$2(ParOps.scala:64)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

_Originally posted by @jaschdoc in https://github.com/flix/flix/issues/8506#issuecomment-2324069582_

**Comment by JonathanStarup** [comment]
ah nice, had these but couldn't pin it down

**Comment by magnus-madsen** [comment]
Fix in master and then port the fix to your branch, @JonathanStarup

**Comment by JonathanStarup** [comment]
Fixed on master
