### ISSUE TITLE
Crash on effect signature typo

### ISSUE THREAD

**Issue by jaschdoc** [flix/flix#8551]
The program causes the compiler to crash. Notice the typo in `KeyNotFund` which should be `KeyNotFound`. This causes crashes for every keystroke when typing out `KeyNotFound`.
```scala
    @Test
    def multiple01(): Bool =
        let v = Vector#{Vector#{Vector#{1, 2, 3, 4}}};
        handler(() -> v[0][0][2] == 3)

    def handler(f: Unit -> Bool \ OutOfBounds + KeyNotFund - a): Bool = {
        try {
            f()
        } with OutOfBounds {
            def outOfBounds(_, _) = false
        } with KeyNotFound {
            def keyNotFound(_, _) = false
        }
    }

```

```
#
# An unexpected error has been detected by the Flix compiler:
#
#   Unexpected type: 'Error'.
#
# This is a bug in the Flix compiler. Please report it here:
#
# https://github.com/flix/flix/issues
#
# -- Flix Compiler --
#
# Flix Version : 0.50.0
#   incremental: All
#
# -- Java Virtual Machine --
#
# JVM Version  : 21.0.1 (2023-10-17)
# JVM Vendor   : GraalVM Community
# JAVA_HOME    : /_/java/21.0.1-graalce
# System       : Linux
#
# -- Stack Trace --
ca.uwaterloo.flix.util.InternalCompilerException: Unexpected type: 'Error'.
	at ca.uwaterloo.flix.language.phase.unification.BoolFormula$.fromEffType(BoolFormula.scala:144)
	at ca.uwaterloo.flix.language.phase.unification.BoolFormula$.fromEffType(BoolFormula.scala:139)
	at ca.uwaterloo.flix.language.phase.unification.BoolFormula$.fromEffType(BoolFormula.scala:138)
	at ca.uwaterloo.flix.language.phase.unification.BoolFormula$.fromEffType(BoolFormula.scala:138)
	at ca.uwaterloo.flix.language.phase.unification.TypeMinimization$.minimizeBoolAlg(TypeMinimization.scala:103)
	at ca.uwaterloo.flix.language.phase.unification.TypeMinimization$.minimizeType(TypeMinimization.scala:35)
	at ca.uwaterloo.flix.language.phase.unification.TypeMinimization$.minimizeType(TypeMinimization.scala:40)
	at ca.uwaterloo.flix.language.phase.unification.TypeMinimization$.minimizeType(TypeMinimization.scala:40)
	at ca.uwaterloo.flix.language.phase.unification.TypeMinimization$.minimizeType(TypeMinimization.scala:40)
	at ca.uwaterloo.flix.language.phase.unification.TypeMinimization$.minimizeType(TypeMinimization.scala:40)
	at ca.uwaterloo.flix.language.phase.unification.TypeMinimization$.minimizeType(TypeMinimization.scala:40)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.resolveOne(ConstraintSolver.scala:266)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.tryResolve$1(ConstraintSolver.scala:247)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.resolveOneOf(ConstraintSolver.scala:257)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.resolveOne(ConstraintSolver.scala:319)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.tryResolve$1(ConstraintSolver.scala:247)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.resolveOneOf(ConstraintSolver.scala:257)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.resolve(ConstraintSolver.scala:223)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.visitSpec(ConstraintSolver.scala:105)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.visitDef(ConstraintSolver.scala:51)
	at ca.uwaterloo.flix.language.phase.Typer$.visitDef(Typer.scala:185)
	at ca.uwaterloo.flix.language.phase.Typer$.$anonfun$visitDefs$1(Typer.scala:168)
	at ca.uwaterloo.flix.util.ParOps$.$anonfun$parTraverseValues$1(ParOps.scala:106)
	at ca.uwaterloo.flix.util.ParOps$.$anonfun$parMap$2(ParOps.scala:64)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

```

**Comment by magnus-madsen** [comment]
Fixed in master.
