### ISSUE TITLE
Compiler crash on A Simple Counter example from book

### ISSUE THREAD

**Issue by steshaw** [flix/flix#8662]
Hi, I am enjoying exploring Flix! I noticed that the compiler crashes on the [A Simple Counter example](https://doc.flix.dev/references.html#example-a-simple-counter) from the book.

<details>
  <summary>Unexpected type: 'Ref[Int32, e205425]' with wrong kind.</summary>

```
#
# An unexpected error has been detected by the Flix compiler:
#
#   Unexpected type: 'Ref[Int32, e205425]' with wrong kind.
#
# This is a bug in the Flix compiler. Please report it here:
#
# https://github.com/flix/flix/issues
#
# -- Flix Compiler --
#
# Flix Version : 0.50.0
#   incremental: All
#
# -- Java Virtual Machine --
#
# JVM Version  : 21.0.4 (2024-07-16)
# JVM Vendor   : Eclipse Adoptium
# JAVA_HOME    : /Users/steshaw/.sdkman/candidates/java/21.0.4-tem
# System       : Mac OS X (15.0)
#
# -- Stack Trace --
ca.uwaterloo.flix.util.InternalCompilerException: Unexpected type: 'Ref[Int32, e205425]' with wrong kind.
	at ca.uwaterloo.flix.language.phase.PatMatch$.countTypeArgs(PatMatch.scala:636)
	at ca.uwaterloo.flix.language.phase.PatMatch$.$anonfun$missingFromSig$1(PatMatch.scala:544)
	at scala.collection.StrictOptimizedIterableOps.map(StrictOptimizedIterableOps.scala:100)
	at scala.collection.StrictOptimizedIterableOps.map$(StrictOptimizedIterableOps.scala:87)
	at scala.collection.immutable.Map$Map1.map(Map.scala:259)
	at ca.uwaterloo.flix.language.phase.PatMatch$.getAllCtors$1(PatMatch.scala:543)
	at ca.uwaterloo.flix.language.phase.PatMatch$.$anonfun$missingFromSig$3(PatMatch.scala:556)
	at scala.collection.immutable.List.foldRight(List.scala:353)
	at ca.uwaterloo.flix.language.phase.PatMatch$.missingFromSig(PatMatch.scala:556)
	at ca.uwaterloo.flix.language.phase.PatMatch$.findNonMatchingPat(PatMatch.scala:319)
	at ca.uwaterloo.flix.language.phase.PatMatch$.checkRules(PatMatch.scala:295)
	at ca.uwaterloo.flix.language.phase.PatMatch$.visitExp(PatMatch.scala:159)
	at ca.uwaterloo.flix.language.phase.PatMatch$.$anonfun$run$5(PatMatch.scala:117)
	at ca.uwaterloo.flix.util.ParOps$.$anonfun$parMap$2(ParOps.scala:64)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```
</details>

When I rollback from version 0.50.0 to [0.49.0](https://github.com/flix/flix/releases/tag/v0.49.0) the example compiles fine with command-line Flix (I don't know how to use 0.49.0 from the VSCode extension).

**Comment by mlutze** [comment]
Hi @steshaw , thanks for the report and the investigative work. 

I suspect this has to do with our changing of Ref into a special case of a struct.

There's no case for struct here: https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/PatMatch.scala#L602

Perhaps we should make this an exhaustive match to prevent this in the future.

**Comment by magnus-madsen** [comment]
Do we just add that case or what? The example looks fine.

**Comment by magnus-madsen** [comment]
Also, welcome @steshaw 😀

**Comment by mlutze** [comment]
> Do we just add that case or what? The example looks fine.

Yes, I think it's a one-line fix.

**Comment by JonathanStarup** [comment]
The evils of `case _ =>`

**Comment by steshaw** [comment]
Thanks!
