### ISSUE TITLE
interpreter / interactive bug - "Undefined fully-qualified name: '$1'"

### ISSUE THREAD

**Issue by stephentetley** [flix/flix#901]
Hi.

The Flix interactive interpreter doesn't evaluate expressions in v0.8.0 (or v.0.7.0):

```
         __   _   _
    / _| | | (_)            Welcome to Flix v0.8.0
   | |_  | |  _  __  __
   |  _| | | | | \ \/ /     Enter an expression or command, and hit return.
   | |   | | | |  >  <      Type ':help' for more information.
   |_|   |_| |_| /_/\_\     Type ':quit' or press 'ctrl + d' to exit.

flix> 12
Undefined fully-qualified name: '$1'.java.lang.IllegalArgumentException: Undefined fully-qualified name: '$1'.
        at ca.uwaterloo.flix.runtime.CompilationResult.evalToString(CompilationResult.scala:87)
        at ca.uwaterloo.flix.runtime.shell.Shell.execEval(Shell.scala:207)
        at ca.uwaterloo.flix.runtime.shell.Shell.execute(Shell.scala:173)
        at ca.uwaterloo.flix.runtime.shell.Shell.loop(Shell.scala:130)
        at ca.uwaterloo.flix.Main$.main(Main.scala:128)
        at ca.uwaterloo.flix.Main.main(Main.scala)
flix> let x = 12; x + x
Undefined fully-qualified name: '$1'.java.lang.IllegalArgumentException: Undefined fully-qualified name: '$1'.
        at ca.uwaterloo.flix.runtime.CompilationResult.evalToString(CompilationResult.scala:87)
        at ca.uwaterloo.flix.runtime.shell.Shell.execEval(Shell.scala:207)
        at ca.uwaterloo.flix.runtime.shell.Shell.execute(Shell.scala:173)
        at ca.uwaterloo.flix.runtime.shell.Shell.loop(Shell.scala:130)
        at ca.uwaterloo.flix.Main$.main(Main.scala:128)
        at ca.uwaterloo.flix.Main.main(Main.scala)
flix>
```

I've tracked this down to the TreeShaker compiler pass - the special function identifier "$1" is not added to the list of reachable symbols so the TreeShaker removes all definitions from `root.defs`.

A potential fix is simply to add `$1` as a function at the same point as `main` is added:

```
    /*
     * (a) The main function is always reachable.
     */
    reachableFunctions.add(Symbol.mkDefnSym("main"))

+    reachableFunctions.add(Symbol.mkDefnSym("$1"))
```

As this is the first time I've looked at the code base, I don't know if this would have negative impact
elsewhere but it does appear to get Interactive working again.

**Comment by magnus-madsen** [comment]
Thank you for reporting this! I will have a look :)

**Comment by magnus-madsen** [comment]
Fixed the bug in master. It will appear in the next release.

**Comment by stephentetley** [comment]
Thanks. I've built from head and it's working fine.
