### ISSUE TITLE
`NullPointerException` in compiler when invoking Java methods with wrong arguments

### ISSUE THREAD

**Issue by sockmaster27** [flix/flix#9067]
Attempting to compile the following program
```flix
import java.nio.file.Files
import java.nio.file.Paths

def main(): Unit \ IO = {
    let path = Paths.get("");
    let exists = Files.exists(path);
    ()
}
```
fails with message
```
java.lang.NullPointerException: Cannot invoke "java.lang.Class.getName()" because the return value of "java.lang.Class.getSuperclass()" is null
	at org.apache.commons.lang3.reflect.MethodUtils.getMatchingAccessibleMethod(MethodUtils.java:354)
	at ca.uwaterloo.flix.language.phase.typer.TypeReduction$.retrieveMethod(TypeReduction.scala:208)
	at ca.uwaterloo.flix.language.phase.typer.TypeReduction$.lookupStaticMethod(TypeReduction.scala:202)
	at ca.uwaterloo.flix.language.phase.typer.TypeReduction$.simplify(TypeReduction.scala:148)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.$anonfun$resolveOne$2(ConstraintSolver.scala:262)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.resolveOne(ConstraintSolver.scala:261)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.tryResolve$1(ConstraintSolver.scala:241)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.resolveOneOf(ConstraintSolver.scala:251)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.resolve(ConstraintSolver.scala:217)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.visitSpec(ConstraintSolver.scala:104)
	at ca.uwaterloo.flix.language.phase.typer.ConstraintSolver$.visitDef(ConstraintSolver.scala:50)
	at ca.uwaterloo.flix.language.phase.Typer$.visitDef(Typer.scala:187)
	at ca.uwaterloo.flix.language.phase.Typer$.$anonfun$visitDefs$1(Typer.scala:168)
	at ca.uwaterloo.flix.util.ParOps$.$anonfun$parTraverseValues$1(ParOps.scala:106)
	at ca.uwaterloo.flix.util.ParOps$.$anonfun$parMap$2(ParOps.scala:64)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

This seems to be caused by the fact that `Files.exists` is missing the last vararg list.

**Comment by magnus-madsen** [comment]
A NullPtr inside their library. Great.

**Comment by magnus-madsen** [comment]
This line:

https://github.com/apache/commons-lang/blob/master/src/main/java/org/apache/commons/lang3/reflect/MethodUtils.java#L352

**Comment by magnus-madsen** [comment]
Fix here: https://issues.apache.org/jira/browse/LANG-1757

**Comment by mlutze** [comment]
I sent a mail to the mailing list to see if they'll release soon https://lists.apache.org/list.html?user@commons.apache.org

**Comment by mlutze** [comment]
Apparently they will release soon:

![Image](https://github.com/user-attachments/assets/60b607ec-b204-4c63-817b-c960c9773f1d)

**Comment by mlutze** [comment]
Appears fixed.
