### ISSUE TITLE
InternalCompilerException in the simplifier

### ISSUE THREAD

**Issue by acieroid** [flix/flix#920]
This is an *incorrect* program that makes the compiler throw an exception (while it should report the error to the user)
```
rel R1(x: Option[Int])
rel R2()

def main(): #{R1, R2} = #{
    R2() :- R1(None(_)).
  }
```

Result:
```
Exception in thread "main" ca.uwaterloo.flix.util.InternalCompilerException: Unexpected non-literal pattern _.
	at ca.uwaterloo.flix.language.phase.Simplifier$.pat2exp$1(Simplifier.scala:793)
	at ca.uwaterloo.flix.language.phase.Simplifier$.pat2exp$1(Simplifier.scala:791)
	at ca.uwaterloo.flix.language.phase.Simplifier$.pat2BodyTerm$1(Simplifier.scala:756)
	at ca.uwaterloo.flix.language.phase.Simplifier$.$anonfun$run$19(Simplifier.scala:618)
	at scala.collection.immutable.List.map(List.scala:222)
	at ca.uwaterloo.flix.language.phase.Simplifier$.visitBodyPred$1(Simplifier.scala:618)
	at ca.uwaterloo.flix.language.phase.Simplifier$.$anonfun$run$3(Simplifier.scala:49)
	at scala.collection.immutable.List.map(List.scala:222)
	at ca.uwaterloo.flix.language.phase.Simplifier$.visitConstraint$1(Simplifier.scala:49)
	at ca.uwaterloo.flix.language.phase.Simplifier$.$anonfun$run$17(Simplifier.scala:555)
	at scala.collection.immutable.List.map(List.scala:222)
	at ca.uwaterloo.flix.language.phase.Simplifier$.visitExp$1(Simplifier.scala:555)
	at ca.uwaterloo.flix.language.phase.Simplifier$.visitDef$1(Simplifier.scala:59)
	at ca.uwaterloo.flix.language.phase.Simplifier$.$anonfun$run$42(Simplifier.scala:1163)
	at scala.collection.StrictOptimizedMapOps.map(StrictOptimizedMapOps.scala:30)
	at scala.collection.StrictOptimizedMapOps.map$(StrictOptimizedMapOps.scala:29)
	at scala.collection.immutable.HashMap.map(HashMap.scala:39)
	at ca.uwaterloo.flix.language.phase.Simplifier$.$anonfun$run$1(Simplifier.scala:1163)
	at ca.uwaterloo.flix.api.Flix.phase(Flix.scala:300)
	at ca.uwaterloo.flix.language.phase.Simplifier$.run(Simplifier.scala:34)
	at ca.uwaterloo.flix.language.phase.Simplifier$.run(Simplifier.scala:30)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.$anonfun$run$1(Phase.scala:42)
	at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
	at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
	at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:74)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
	at ca.uwaterloo.flix.language.phase.Phase$$anon$1.run(Phase.scala:41)
	at ca.uwaterloo.flix.api.Flix.codeGen(Flix.scala:280)
	at ca.uwaterloo.flix.api.Flix.$anonfun$compile$1(Flix.scala:288)
	at ca.uwaterloo.flix.util.Validation.flatMap(Validation.scala:50)
	at ca.uwaterloo.flix.util.Validation.flatMap$(Validation.scala:49)
	at ca.uwaterloo.flix.util.Validation$Success.flatMap(Validation.scala:74)
	at ca.uwaterloo.flix.api.Flix.compile(Flix.scala:287)
	at ca.uwaterloo.flix.Main$.$anonfun$main$5(Main.scala:164)
	at ca.uwaterloo.flix.util.Timer.<init>(Timer.scala:28)
	at ca.uwaterloo.flix.Main$.main(Main.scala:164)
	at ca.uwaterloo.flix.Main.main(Main.scala)
```

**Comment by magnus-madsen** [comment]
Pattern matching in constraints bodies are currently not supported :( :(

**Comment by magnus-madsen** [comment]
It should be fixed, but its a significant chunk of work.

**Comment by magnus-madsen** [comment]
@acieroid Will we survive for now?

**Comment by acieroid** [comment]
Yes, we don't need it currently and I don't think we will need it! This issue is more about remembering that this specific case throws an exception rather than notifying the user that either the program is incorrect or that it uses unsupported features.

**Comment by magnus-madsen** [comment]
Roger! Thanks

**Comment by magnus-madsen** [comment]
Feel free to modify/expand the error message if it helps with the memory.

**Comment by magnus-madsen** [comment]
Fixed-- or at least you know get an error message.
