### ISSUE TITLE
assoc reduction failure

### ISSUE THREAD

**Issue by JonathanStarup** [flix/flix#9204]
```
def main(_: Indexable.Idx[a]): Unit with Indexable[a] where Indexable.Idx[a] ~ b = ()
```

```
#
# An unexpected error has been detected by the Flix compiler:
#
#   Unexpected associated type reduction failure (C:\Work\github\flix\test.flix:1:27)
#
# This is a bug in the Flix compiler. Please report it here:
#
# https://github.com/flix/flix/issues
#
# -- Flix Compiler --
#
# Flix Version : 0.52.0
#   incremental: All
#
# -- Java Virtual Machine --
#
# JVM Version  : 21.0.1 (2023-10-17)
# JVM Vendor   : Oracle Corporation
# JAVA_HOME    : C:\Program Files\Java\jdk-21.0.1
# System       : Windows 11 (10.0)
#
# -- Stack Trace --
ca.uwaterloo.flix.util.InternalCompilerException: Unexpected associated type reduction failure (C:\Work\github\flix\test.flix:1:27)
	at ca.uwaterloo.flix.language.phase.Monomorpher$.ca$uwaterloo$flix$language$phase$Monomorpher$$infallibleReduceAssocType(Monomorpher.scala:857)
	at ca.uwaterloo.flix.language.phase.Monomorpher$StrictSubstitution.apply(Monomorpher.scala:144)
	at ca.uwaterloo.flix.language.phase.Monomorpher$StrictSubstitution.apply(Monomorpher.scala:136)
	at ca.uwaterloo.flix.language.phase.Monomorpher$StrictSubstitution.apply(Monomorpher.scala:136)
	at ca.uwaterloo.flix.language.phase.Monomorpher$.visitExp(Monomorpher.scala:501)
	at ca.uwaterloo.flix.language.phase.Monomorpher$.$anonfun$visitExp$3(Monomorpher.scala:503)
	at scala.collection.immutable.List.map(List.scala:247)
	at ca.uwaterloo.flix.language.phase.Monomorpher$.visitExp(Monomorpher.scala:503)
	at ca.uwaterloo.flix.language.phase.Monomorpher$.mkFreshDefn(Monomorpher.scala:448)
	at ca.uwaterloo.flix.language.phase.Monomorpher$.$anonfun$run$3(Monomorpher.scala:345)
	at ca.uwaterloo.flix.language.phase.Monomorpher$.$anonfun$run$3$adapted(Monomorpher.scala:340)
	at ca.uwaterloo.flix.util.ParOps$.$anonfun$parMap$2(ParOps.scala:64)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)


```

**Comment by mlutze** [comment]
I'm inclined to think this should be an error because `b` is not bound anywhere, but I am not sure.

**Comment by magnus-madsen** [comment]
> I'm inclined to think this should be an error because `b` is not bound anywhere, but I am not sure.

Agreed.

**Comment by magnus-madsen** [comment]
Just ban it. Then if there is a use case, raise the point again?

**Comment by JonathanStarup** [comment]
"just ban it" doesn't sound easy though. what is the rule to add?

**Comment by JonathanStarup** [comment]
examples such as `T.Assoc[a] ~ b, T.Assoc[b] ~ a` makes bound/unbound somewhat recursive

**Comment by mlutze** [comment]
The original example:

```
def main(_: Indexable.Idx[a]): Unit with Indexable[a] where Indexable.Idx[a] ~ b = ()
```

Now compiles fine.

This example:
```
def mainn(_: Unit): Unit with Indexable[a] where Indexable.Idx[a] ~ Unit = ()
```

Fails with an undefined variable error, which is fine.
