### ISSUE TITLE
EntryPoints must support malformed types

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#9589]
```
ca.uwaterloo.flix.util.InternalCompilerException: Unexpected effect 'Error'.
	at ca.uwaterloo.flix.language.phase.EntryPoints$CheckEntryPoints$.eval(EntryPoints.scala:384)
	at ca.uwaterloo.flix.language.phase.EntryPoints$CheckEntryPoints$.isPrimitiveEffect(EntryPoints.scala:348)
```

**Comment by magnus-madsen** [comment]
@JonathanStarup Request a fix since this happens a lot :)

**Comment by JonathanStarup** [comment]
I don't understand - Error is handled gently https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/EntryPoints.scala#L371

From the line number it looks like that Apply case 🤔

**Comment by JonathanStarup** [comment]
Ah Difference is missing

**Comment by JonathanStarup** [comment]
The effect occurring here is `Apply(Cst(Error), Cst(RecordRowEmpty))`

**Comment by JonathanStarup** [comment]
So the question is - what should Entrypoints do with malformed effects? it could be

| Valid | Contains Error | Result |
| --- | --- | --- |
| Yes | Yes | Silently throw away entrypoint annotation |
| Yes | No | Do nothing |
| No | Yes | Silently throw away entrypoint annotation |
| No | No | Crash |

**Comment by magnus-madsen** [comment]
It should not crash, but I am not sure what it should do.

**Comment by JonathanStarup** [comment]
Hard to fix then 😄 I think this is born from the lack of rules in terms of resilience. From my viewpoint it feels a bit lawless 

With resilience, it becomes even more important for phases to actually say what invariants they assure and which they do not

**Comment by magnus-madsen** [comment]
Program:

```
def main(): Unit \ {IO = 
    run {
        Console.println("Please enter your name: ");
        let name = Console.readln();
        Console.println("Hello ${name}")
    } with Console.runWithIO
```

**Comment by magnus-madsen** [comment]
@JonathanStarup Why can it not just assume the error effect is a primitive effect?

**Comment by JonathanStarup** [comment]
The problem is not error, it is malformed effect formulas. Error is handled gracefully but `Apply(Cst(Error), Cst(RecordRowEmpty))` is not

**Comment by JonathanStarup** [comment]
Entrypoints is expecting a wellformed formula that might include error, like `Error + Error` or `Error` or `IO + (Crash & Error)`

So the question is - what should it do for non-wellformed formulas

**Comment by magnus-madsen** [comment]
It should continue without crashing
